### ISSUE TITLE
话说这玩意怎么没个 Firefox 版啊。。。

### ISSUE THREAD

**Issue by AndyChen2005121** [xmcp/pakku.js#1]
我是 Firefox 用户，希望你能出一个给我这样的人用的扩展。

**Comment by xmcp** [comment]
我不用firefox，也不会开发firefox扩展（讲真firefox的文档质量比chrome差好几条街），不过background.js里面的核心函数 `parse` 是不依赖于chrome的。

所以如果你会开发firefox扩展的话，稍微改一下background.js应该就行。
