### ISSUE TITLE
Any way to disable/customize the pakku's shortcut?

### ISSUE THREAD

**Issue by nonoroazoro** [xmcp/pakku.js#101]
Currently, the keyboard shortcut conflicts with my own shortcuts, I wonder if there's any way I could disable the pakku's shortcut? Thanks!

**Comment by xmcp** [comment]
The keyboard shortcut is managed by browser.
Settings are available at `chrome://extensions/shortcuts` (for Chrome) or `about:addons` (for Firefox).

**Comment by nonoroazoro** [comment]
Seems that alt+r is registered by pakku, if you choose to ignore this issue, I'd uninstall it. Thanks anyway.

**Comment by xmcp** [comment]
As mentioned, you can change or deregister this shortcut in the browser's settings.
