### ISSUE TITLE
NET! 网络错误

### ISSUE THREAD

**Issue by lishiyuwhu** [xmcp/pakku.js#103]
已经✓ 是最新版本

# 红框

网络错误

CID = 96474099

Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=96474099&pakku_request'.

Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=96474099&pakku_request'.
    at down_danmaku (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1484:13)
    at onbeforerequest (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1701:60)
    at subEventCallback (extensions::webRequestEvent:106:32)

# 蓝框

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 9.2.6

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"10","DANMU_MARK":"suffix","TAOLUS":"","FOOLBAR":"off","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1560221213817","FLASH_NOTIF":"on","_ADVANCED_USER":"off","SHRINK":"on","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","REMOVE_SEEK":"off","POPUP_BADGE":"percent","WHITELIST":"[]","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"off","PROC_TYPE7":"on","THRESHOLD":"20","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"2":{"error":"网络错误","cid":"96474099","details":"Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=96474099&pakku_request'.\n\nError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://api.bilibili.com/x/v1/dm/list.so?oid=96474099&pakku_request'.\n    at down_danmaku (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1484:13)\n    at onbeforerequest (chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/all_core.js:1701:60)\n    at subEventCallback (extensions::webRequestEvent:106:32)"}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"on","FOOLBAR":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"10","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"on","TAOLUS":"","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1560221213817"}

**Permissions:** `{"origins":["https://live.bilibili.com/*","https://www.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=2 status=complete `https://www.bilibili.com/video/av55177585`

- ID=183 status=complete `undefined`

- ID=186 status=loading `undefined`

**Request / Normal XML:** error, status=0 ``

**Request / XML With Param:** error, status=0 ``

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 69 :: 1
</details>

**Comment by xmcp** [comment]
看起来像是网络确实有问题啊。

请确认：
- 关闭pakku后弹幕能正常加载
- 更换网络环境后依然出现此问题
- 刷新或者重启浏览器后依然出现此问题
- 禁用其他插件/扩展程序/用户脚本/杀毒软件等后依然出现出现此问题
