### ISSUE TITLE
[建议] 错别字/谐音合并显示词频最高项

### ISSUE THREAD

**Issue by KumaTea** [xmcp/pakku.js#104]
#小嘴抹了蜜警告

![Issue screenshot](https://user-images.githubusercontent.com/36222458/59464103-25917000-8e5a-11e9-8c37-90da405dd22f.png)

大佬好。
如图，目前错别字、谐音弹幕时，貌似是按照第一项显示，这在第一项本身出现错别字时会显得有些不习惯。
建议在合并时，计算下（格式化后的）词频，然后显示最高项~

**Comment by xmcp** [comment]
v10.0将加入这一特性
