### ISSUE TITLE
可否加入自动屏蔽顶/底部和自动开启防挡弹幕？

### ISSUE THREAD

**Issue by catshitz** [xmcp/pakku.js#105]
v9.2.6_C 如题
![t](https://user-images.githubusercontent.com/18102209/61064336-2820be80-a434-11e9-84e1-dbf7fe3090bf.jpg)

*PS
![q](https://user-images.githubusercontent.com/18102209/61065028-74b8c980-a435-11e9-9466-306a0425ed24.jpg)
此为某脚本功能 但总是失效（基本没用） 所以想请问可否在pakku加入同类更强效功能

**Comment by xmcp** [comment]
请向该脚本的作者反馈bug
