### ISSUE TITLE
请求追加处理本地弹幕功能

### ISSUE THREAD

**Issue by liuxl8964** [xmcp/pakku.js#106]
随着B站版权越来越严再加上一些政治风险，B站已经干掉很多番剧视频了，视频可以再下，部分弹幕也有办法找回，也有专门的播放器回放弹幕，但是不能再享受pakku带来的弹幕观看体验了，请求加入本地弹幕处理并输出功能

**Comment by xmcp** [comment]
可以访问 chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/local.html

或者给它分配一个快捷键：
![image](https://user-images.githubusercontent.com/6646473/61961250-b3d04880-aff9-11e9-8753-db9318698744.png)
