### ISSUE TITLE
希望能在进度条上预览弹幕时不被遮住

### ISSUE THREAD

**Issue by aclihub** [xmcp/pakku.js#109]
请见图片
![image](https://user-images.githubusercontent.com/54567707/64001095-ac8ce500-cb39-11e9-8540-91496f15e02b.png)

**Comment by xmcp** [comment]
弹幕列表的位置修复了，虽然在两边的时候会被密度图挡住一点，忍忍就好了（

**Comment by aclihub** [comment]
感谢开发者的付出
这个插件真的非常好用，真是梦寐以求的功能
