### ISSUE TITLE
用b站自带屏蔽功能屏蔽掉的弹幕会诈尸...

### ISSUE THREAD

**Issue by mlisry** [xmcp/pakku.js#11]
我在b站屏蔽列表里有【休想】这个词
用了扩展之后弹幕里又会出现【休想x2】这样的弹幕........

**Comment by mlisry** [comment]
另外可不可以有个白名单......
比如【前方高能】这个词.............
胆小群众表示没有弹幕护体真的好方脏............∑(っ °Д °;)っ

**Comment by xmcp** [comment]
一般来说除非你弹幕屏蔽用的是正则表达式，否则应该不会诈尸的呀。

比如如果你屏蔽词是 `休想$`，那确实匹配不上 `休想 [x2]`，pakku设置里面“弹幕数量标记”就是为了这个设计的，改成“不显示”就没问题了（但不显示[xN]标记确实不太方便就是了）。

白名单这个思路不错，可以考虑一下。

**Comment by mlisry** [comment]
啊确实是正则QAQ 
插件真的好用！ 我把正则都搬进插件设置里应该就好了ww

谢谢白名单！！

**Comment by xmcp** [comment]
一般我的做法是在屏蔽规则里特判后缀，比如 `休想(\s\[x\d+\])?$`

**Comment by xmcp** [comment]
v6.8的黑名单功能解决了这个问题
