### ISSUE TITLE
被遮住的弹幕无法选择

### ISSUE THREAD

**Issue by aclihub** [xmcp/pakku.js#110]
可以看到绿色圈中黄色的弹幕无法被选中
![2](https://user-images.githubusercontent.com/54567707/64005618-59b82b00-cb43-11e9-8ae6-3e3848a24a77.png)
无法被选中
![1](https://user-images.githubusercontent.com/54567707/64005710-7bb1ad80-cb43-11e9-9dbc-868362e8f97c.png)
个人认为可以学习bilibili官方
![3](https://user-images.githubusercontent.com/54567707/64005896-c9c6b100-cb43-11e9-9a3b-4bca3d357bf4.png)

**Comment by aclihub** [comment]
图一鼠标可能有点歪了，但是我说的这个问题是有的

**Comment by xmcp** [comment]
被遮住的弹幕确实无法选择。

弄成右键菜单这样挺麻烦的，还需要避免跟B站播放器冲突，不想做。

**Comment by aclihub** [comment]
### **_理解万岁_**
