### ISSUE TITLE
部分专题页面播放器增强功能失效

### ISSUE THREAD

**Issue by aclihub** [xmcp/pakku.js#111]
调试信息不附了，问题如下图
![bug](https://user-images.githubusercontent.com/54567707/66020451-b0859b80-e519-11e9-9876-2e95b090822a.png)
网页内flash播放器弹幕密度条只显示一半
页面如下
[![09edef7cd0dd765e0a45faca502848cc375037b0](https://user-images.githubusercontent.com/54567707/66020585-1c680400-e51a-11e9-8430-ee68a49b7e75.jpg)
https://www.bilibili.com/blackboard/topic/Railgun_10years_web.html

**Comment by xmcp** [comment]
这个专题页面内嵌了多个播放器，同时加载了多个视频。pakku会误认为是页面内多次跳转，从而重复注入脚本，造成功能失效。

考虑到此类专题页面的罕见性和无规律性，暂时不修复此bug。之后如果B站广泛允许一个页面内嵌多个播放器，再进行适配。
