### ISSUE TITLE
[建议] 能否给予一个阈值，超过才进行合并

### ISSUE THREAD

**Issue by qmzmdqs** [xmcp/pakku.js#113]
因为某视频刚出来的时候，弹幕数量较少。初期重复、相似概率还是蛮高的。
对于我来说，想屏蔽重复弹幕大部分情况是因为过多导致影响观感了，小部分才是恶意刷屏。

如果弹幕不影响观感（自定阈值），不进行合并，超过才进行合并。这样新视频时不至于太冷清

**Comment by xmcp** [comment]
如果你想要这种”不冷清“的氛围的话，可以在看弹幕比较少的视频的时候暂时关闭pakku（点“工作中”那个开关，默认的快捷键是 <kbd>Alt+R</kbd>）。
