### ISSUE TITLE
讨论一下怎么合并人名地名

### ISSUE THREAD

**Issue by excosy** [xmcp/pakku.js#116]
我的想法是，当某个时段弹幕密度明显增大(>300%)时，统计弹幕里重复出现10次以上的词，将包含了关键词的弹幕合并，类似于相似弹幕合并的功能，只是这个字据取得更宽(2-5字)并且关键词位置固定(一般位于句尾)。
比如在某区域内连续出现了：李子明别撸了，章子怡别撸了……这类，"别撸了"重复次数超过了10次，就可以把所有包含了这个关键字的所有弹幕合并。此外为了避免误伤对于某一话题集中讨论的弹幕，初步考虑只合并句子长度<10且关键字位于句尾的。
ps：关键字可以放宽到只有一个字

**Comment by xmcp** [comment]
能用正则表达式表示的简单规则可以在设置里面输入
