### ISSUE TITLE
 pakku：哔哩哔哩弹幕过滤器 與 哔哩哔哩助手 擴展功能互相衝突

### ISSUE THREAD

**Issue by tkp206093** [xmcp/pakku.js#118]
RT

詳情可以參考 哔哩哔哩助手 的Github

https://github.com/bilibili-helper/bilibili-helper/issues/646

https://github.com/bilibili-helper/bilibili-helper/issues/654

**Comment by xmcp** [comment]
由于chrome的限制，pakku为了修改弹幕请求进行了大量魔改（相比之下firefox提供了官方的修改响应正文的API所以科学很多），所以确实会误伤第三方插件。

**Comment by jjj201200** [comment]
有什么办法像原来那样兼容一下吗

**Comment by xmcp** [comment]
@jjj201200

装了 chrome web store 版本的助手看了一下，问题好像出在 pakku 通过 xhr hook 使得原本页面发出的 HTTP 请求变成了由 pakku 的 background page 发出，所以其他扩展就没法用 `chrome.webRequest` 拦截到了。

“HTTP 请求变成由 pakku 的 background page 发出”这个事实肯定是改不了的……要不然 pakku 也没法修改弹幕了。

助手要想兼容的话，可以试试不用现在的 `chrome.webRequest` Hook 获取 CID，改成通过 content script 获取试试？视频页面里 `window.cid` 和 `window.__INITIAL_STATE__.videoData.cid` 这两个变量都可以用，助手在 content script 里向 `document.body` `appendChild` 一个 `<script>` 就可以读到。

**Comment by jjj201200** [comment]
> @jjj201200
> 
> 装了 chrome web store 版本的助手看了一下，问题好像出在 pakku 通过 xhr hook 使得原本页面发出的 HTTP 请求变成了由 pakku 的 background page 发出，所以其他扩展就没法用 `chrome.webRequest` 拦截到了。
> 
> “HTTP 请求变成由 pakku 的 background page 发出”这个事实肯定是改不了的……要不然 pakku 也没法修改弹幕了。
> 
> 助手要想兼容的话，可以试试不用现在的 `chrome.webRequest` Hook 获取 CID，改成通过 content script 获取试试？视频页面里 `window.cid` 和 `window.__INITIAL_STATE__.videoData.cid` 这两个变量都可以用，助手在 content script 里向 `document.body` `appendChild` 一个 `<script>` 就可以读到。

了解了，感谢
