### ISSUE TITLE
新的相似弹幕判定规则

### ISSUE THREAD

**Issue by xmcp** [xmcp/pakku.js#12]
![image](https://cloud.githubusercontent.com/assets/6646473/26684909/235060f4-471b-11e7-8902-0dbc001492df.png)

截图为 [《潜行吧！阿里郎 OP》](http://www.bilibili.com/video/av442411/) 片段。在所选片段中，有一些刷屏弹幕没有被完美合并。它们是：

```
yeah!~yeah!~
yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah [x2]
yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah [x2]
yeah!~yeah!~yeah!~yeah [x2]
yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~
yeah!~yeah!~yeah!~yeah!~yeah!~yeah [x2]
yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah [x2]
```

它们之间的编辑距离并不是特别小，所以 pakku.js 的相似弹幕判定机制 (#2) 对其无效。

因此，我们需要引入新的机制来处理这种模式的相似弹幕。

我目前的想法是：如果两条弹幕的字符集（即所有出现的字符的集合，比如上图例子中的字符集是 `{y, e, a, h, !, ~}` 相同，就认为它们是相同的（当然，选项里的开关还是要有的）。

不过我目前并不清楚这种做法的识别率和误伤率，因此在此征求各位的建议。不知各位认为

- pakku.js 是否应该合并这种刷屏弹幕？
- 上述基于字符集的做法是否足够完美、优雅？
- 是否有更好的算法可以识别这样的弹幕？

希望各位多多发表建议（因为我也很迷茫呀）

**Comment by dramforever** [comment]
更一般的，可以设计一下 [`edit_distance`](https://github.com/xmcp/pakku.js/blob/master/core/edit_distance.js#L19-L27) 里面计算字符集差异的打分方法，比如：

| P 中出现次数 | Q 中出现次数 | 现在打的分数 | 理想状况下分数 |
|--------------|--------------|--------------|----------------|
| 1 | 0 | 1 | 最高 |
| 3 | 2 | 1 | 其次 |
| 10 | 9 | 1 | 最低 |

**以下口胡，请小心阅读**

记某字符 `c` 在 `P` 和 `Q` 中出现次数为 `u` 和 `v`，那么：

- **现在的**：`|u - v|`
- **dram 口胡的**：`|u - v| / min{u, v}`

还有什么别的思路么？

**Comment by xmcp** [comment]
@dramforever
[JS Bin](http://jsbin.com/gadavazaco/edit?js,console)

提供一些样例如下：

**A组：完全重复，编辑距离应该非常小（甚至为0）**
```javascript
edit_distance('yeah!~','yeah!~yeah!~yeah!~'); //A1
edit_distance('yeah!~','yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~'); //A2
edit_distance('yeah!~yeah!~','yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~yeah!~'); //A3
```

**B组：部分相似，编辑距离应该比较小**
```javascript
edit_distance('少看书，少看书，少看那些没用的书','少看那些没用的书'); //B1
edit_distance('少看那些没用的书','少干那些没用的鼠'); //B2
edit_distance('梅--露梅露梅露梅露梅露梅露梅','梅露露'); //B3
```

**C组：基本不一样，编辑距离应该超大**
```javascript
edit_distance('没有未来的未来不是我要的未来','未来いない未来は 私が欲しくないんだ'); //C1
edit_distance('没有未来的未来不是我要的未来','上面说未来的你给我过来'); //C2
edit_distance('萌娘百科欢迎您参与完善本条目','萌娘百科祝您在本站度过愉快的时光'); //C3
```

`Math.abs(u-v)/(u+v)` 基本可以接受，不过遗憾地并没有区分开A组和B组。

`Math.abs(u-v)/(1+Math.min(u+v))` 原地爆炸，3个B都比3个A还相似。

**Comment by celeron533** [comment]
额，碰到这种情况我一般直接屏蔽用户或者就关弹幕了。
个人觉得pakku只要完成基本过滤功能。太复杂的话，一来影响性能，而来误杀率会增加。

**Comment by dramforever** [comment]
是不是应该给其中一个打分高点什么的……

**Comment by dramforever** [comment]
我认为 B 组就应该是不同部分贡献正常的编辑距离，剩下的贡献少一些……要不你想个别的？

**Comment by xmcp** [comment]
@celeron533 屏蔽用户治标不治本呀，而且pakku存在的意义就是让你在面对海量刷屏的时候也不用关弹幕（笑，所以我觉得对于此类刷屏弹幕的识别是有必要的。

至于性能，即使是在我3代i3的辣鸡电脑上，pakku都可以在1s之内扫完一个视频的弹幕，比[我设的几十个正则屏蔽词](https://github.com/xmcp/bilibili-ban-list)跑得都快，而且这种小patch应该不会对性能有太大的负面影响。

至于误杀率，这个肯定是要想办法降低到合理的程度的。不过反正迄今为止这些可能误杀的判定规则在设置里都可以关掉嘛（逃

**Comment by xmcp** [comment]
@dramforever 观察B1和B3，我觉得估价函数应该考虑到字符之间的连接顺序。

没准可以把所有[x..x+1]的子串弄出来算编辑距离，结果与原来的edit_distance取min。或者之类的方法瞎搞。

**Comment by dramforever** [comment]
你指的是从统计字符集变成统计 `hash(每个 k-gram)`？看起来不错

**Comment by xmcp** [comment]
目前觉得 [Fu Eric](https://www.zhihu.com/people/fu-eric-61) 在 [我发的文章](https://zhuanlan.zhihu.com/p/27227647) 下面评论的思路实现的效果还可以。

> 试一下：
> 1.统计每个字/词的频率
> 2.将每个字符串换成词频向量（先normalize向量，消除字符串长度不一致的影响）
> > （comment：都上夹角了为啥还要 normalize 呀）
> 
> 3.用向量夹角公式判断两个字符串的相似度
> 可以参考一下这篇文章：http://www.ruanyifeng.com/blog/2013/03/cosine_similarity.html

[JS Bin](http://jsbin.com/lijatawayu/1/edit?js,console)，A组和B组中大部分内容都能区分出来。

**Comment by dramforever** [comment]
吼啊

**Comment by fanthos** [comment]
加入了一些其他变化
http://jsbin.com/qemozul

**Comment by xmcp** [comment]
我觉得要是加 cosine distance 判断的话，设置里可以提供阈值的选项。
目前觉得比较合适的几个阈值：0.5、0.7、0.9、0.99（基本相当于关闭这个功能）

**Comment by fanthos** [comment]
可以考虑过滤掉所有标点符号emoji，并且考虑循环，比如test会考虑成为testt来计算，testtest->testtestt。加入这些之后能够更有效的过滤重复字符串

https://jsperf.com/fts-test1
http://jsbin.com/qemozul/edit?js,console

**Comment by xmcp** [comment]
[qemozul](http://jsbin.com/qemozul/edit?js,console) 里面 A6 的结果是 NaN 这明显不清真啊 :smirk: 

另外这做法有问题吧……A1和A2的confidence都掉到0.75了，都被B1超过去了呀……

**Comment by fanthos** [comment]
之前主要在jsperf里面改代码
现在jsbin里面改完了，可以看一下结果
返回的距离没有开方运算，是距离^2

http://jsbin.com/qemozul/edit?js,console

**Comment by xmcp** [comment]
卧槽这么一改果然极好呀。

**Comment by fanthos** [comment]
距离计算不用1用出现次数效果更好
https://jsperf.com/fts-test1 里面的new3
http://jsbin.com/qemozul/edit?js,console

**Comment by xmcp** [comment]
这个距离函数目前的最大问题：

**怎么把它合并到现有的 `edit_distance` 里？**

如果直接取 min，BKTree的三角不等式就保证不了了（但实际使用应该也不会出太大的乱子）。
直接用余弦距离替代原来的距离显然也不好，因为余弦距离对错别字的容忍度非常差。
如果把两个距离加权相加，THRESHOLD要怎么设也是一个问题。

**Comment by fanthos** [comment]
我认为可以这两个函数有一个非常相似就认为是相同的

**Comment by xmcp** [comment]
那就是取min呀。

这样有一个小问题：考虑A和B的向量距离很小、编辑距离很大；B和C的向量距离很大、编辑距离很小。那么，A和C是否会被合并将取决于BKTree的形态（因为三角不等式被打破了）。

不过如果真出现这种情况，A和C合并不合并应该都看不出来什么明显的bug（逃
所以就这样了。

**Comment by xmcp** [comment]
5.0版终于弄出来了，另外自从5.0把BKTree（#5）扔掉之后，过滤效果好像得到了长足的提升啊 :rofl: 

![image](https://user-images.githubusercontent.com/6646473/26986113-bb494188-4d78-11e7-89bf-1ee95a851632.png)
