### ISSUE TITLE
[建议] 增加按照用户等级屏蔽功能

### ISSUE THREAD

**Issue by Wickyan** [xmcp/pakku.js#120]
b站弹幕质量每况愈下，希望拓展此功能，以此挽救b站孤寡老人。

ps：想要屏蔽合并之后的某几个弹幕用户（例如x10），如何操作？

**Comment by xmcp** [comment]
https://github.com/xmcp/pakku-advanced-filter

`d.sender_info.current_level` 是等级。
为了缩短加载时间，对于合并之后的弹幕，只会加载其中第一条弹幕的发送者信息（我觉得区分其中的不同发送者意义不大）。
