### ISSUE TITLE
希望加入合并后弹幕及小数字字体选择

### ISSUE THREAD

**Issue by SyuueenN** [xmcp/pakku.js#121]
希望加入合并后弹幕及小数字字体选择，弹幕正文的英文字体变了，小数字也不堪入目，希望给一个改字体的选项。

**Comment by xmcp** [comment]
https://github.com/xmcp/pakku.js/issues/51

**Comment by SyuueenN** [comment]
> #51

发现扩展往弹幕字体设置里加了个“Segoe UI Symbol”，希望针对有字体定制需求的用户加一个“不进行修复”的选项。

**Comment by xmcp** [comment]
字体修复操作只会进行一次，如果需要定制字体请自行修改播放器设置。

关于新版B站播放器无法修改字体的问题请移步B站反馈渠道 http://link.acg.tv/
