### ISSUE TITLE
关于合并弹幕的显示时间优化的建议

### ISSUE THREAD

**Issue by DaiYuxiang233** [xmcp/pakku.js#122]
建议可以新增1个功能：在合并滚动弹幕的同时，可以减缓弹幕划过屏幕的速度，如我将10秒内的10条重复弹幕（如：万恶之源）合并，就可以减缓被合并弹幕（万恶之源（10））的划过屏幕速度（如从正常的5秒调到10秒）

**Comment by xmcp** [comment]
做不到
