### ISSUE TITLE
弹幕没有被折叠

### ISSUE THREAD

**Issue by Wings-Fantasy** [xmcp/pakku.js#126]
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 9.2.9

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"suffix","CLOUD_SYNC":"off","BLACKLIST":"[[\".{50}\",\"\"],[\"^[\\\\.。,，\\\\/\\\\?？!！~～@\\\\^、+=\\\\-_ ]+$\",\"\"],[\"^[^\\\\u4E00-\\\\u9FA5]$\",\"\"],[\"弹\\\\s*[屏幕][^护]*$\",\"\"],[\"倍速\",\"\"],[\"[3３三立]\\\\s+[dDＤ体體]\",\"\"],[\"(^|是)..[红橙黄绿青蓝紫黑白灰].{0,2}$\",\"\"],[\"^[第前]([0-9零一二两三四五六七八九十百千万亿].{0,6})?$\",\"\"],[\"^.{1,6}[天时点分钟秒]前\",\"\"],[\"^[0-9零一二两三四五六七八九十百千万亿nN]{1,4}(刷|周[木目])$\",\"\"],[\"破.*[wW万萬]\",\"\"],[\"[wW万萬]助攻\",\"\"],[\"钟的?诅咒\",\"\"],[\"口[气氣].*[集级]\",\"\"],[\"完结\",\"\"],[\"撒花\",\"\"],[\"从左到右\",\"\"],[\"[0-9万名].{1,6}[伴你们人友]($|.*[豪嚎号好])\",\"\"],[\"降.{0,3}(成功|失败|完美)\",\"\"],[\"完美空降\",\"\"],[\"空难(现场|$)\",\"\"],[\"[漂飘飄飙][移逸遗]\",\"\"],[\"[左右][漂飘飄飙]\",\"\"],[\"(\\\\s|^|[我怎来会].?)[漂飘飄飙]+($|.?[～~?？。，啊]|\\\\s)\",\"\"],[\"\\\\s{5}\",\"\"],[\"入(宅|坑$)\",\"\"],[\"^什么[!\\\\?！？，,、~\\\\s]\",\"\"],[\"^《.*》$\",\"\"],[\"^告诉.*[我还永]\",\"\"],[\"暴[露漏]((补番)?时间)?[了乐啦拉]\",\"\"],[\"周目($|.*(我|回|起|报|人|过|来|此))\",\"\"],[\"つロ|[干肝乾]杯\",\"\"],[\"[马馬][冬东]|[冬东]梅|[马馬]什么梅\",\"\"],[\"[fF]{3}.*(真爱|百合|基|性恋)\",\"\"],[\"豆腐.*[酸甜苦辣咸臭糖盐醋吃加]\",\"\"],[\"[酸甜苦辣咸臭糖盐醋吃加].*豆腐\",\"\"],[\"我的?(床上|老婆)\",\"\"],[\"我选\",\"\"],[\"(\\\\d{1,2}|十|十?[一二三四五六七八九十])([\\\\.,\\\\/:：、，；点\\\\-月。]|\\\\s+)(\\\\d{1,2}|[二三]?十|[二三]?十?[一二三四五六七八九]).{0,4}($|[日的过我别你上午夜晨])\",\"\"],[\"\\\\d\\\\d(\\\\d\\\\d)?([\\\\.,。，、\\\\/\\\\-年—*]|\\\\s+)\\\\d(\\\\d)?([\\\\.,。，、\\\\/\\\\-月—*]|\\\\s+)\\\\d\",\"\"],[\"^(2([^3]\\\\d|3[^3])|6([^6]\\\\d|6[^6])|[^26]\\\\d{2})\\\\d{0,5}$\",\"\"],[\"(元旦|年|国庆|春|秋|圣诞).?快乐\",\"\"]]","_LAST_UPDATE_TIME":"1583814089009","FLASH_NOTIF":"on","_ADVANCED_USER":"on","SHRINK":"on","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","REMOVE_SEEK":"on","POPUP_BADGE":"off","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","WHITELIST":"[]","PROC_TYPE7":"on","THRESHOLD":"20","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"20","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"62":{"identical":24,"edit_distance":26,"pinyin_distance":2,"cosine_distance":7,"player_seek":0,"blacklist":55,"count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":4,"shrink":0,"scroll":0,"taolu":2,"total":289,"onscreen":175,"maxcombo":11,"maxdispval":35.0717061803088,"error":null,"cid":"168714905","parse_time_ms":41},"63":{"identical":12,"edit_distance":4,"pinyin_distance":2,"cosine_distance":0,"player_seek":0,"blacklist":8,"count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":0,"scroll":0,"taolu":5,"total":189,"onscreen":163,"maxcombo":4,"maxdispval":16.957688306653694,"error":null,"cid":"168768448","parse_time_ms":18},"113":{"identical":0,"edit_distance":0,"pinyin_distance":0,"cosine_distance":0,"player_seek":0,"blacklist":0,"count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":0,"scroll":0,"taolu":0,"total":1,"onscreen":1,"maxcombo":1,"maxdispval":4.358898943540674,"error":null,"cid":"42470238","parse_time_ms":1},"273":{"identical":59,"edit_distance":467,"pinyin_distance":1,"cosine_distance":15,"player_seek":0,"blacklist":16,"count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":12,"shrink":48,"scroll":0,"taolu":0,"total":1000,"onscreen":442,"maxcombo":131,"maxdispval":131.8966495204814,"error":null,"cid":"169317052","parse_time_ms":188},"276":{"identical":0,"edit_distance":0,"pinyin_distance":0,"cosine_distance":0,"player_seek":0,"blacklist":0,"count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":0,"scroll":0,"taolu":0,"total":0,"onscreen":0,"maxcombo":0,"maxdispval":0,"error":null,"cid":"168859720","parse_time_ms":0}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=205 status=complete `undefined`

- ID=263 status=complete `https://space.bilibili.com/19871226/favlist?fid=114960326&ftype=create`

- ID=270 status=complete `https://www.bilibili.com/video/BV1j741127Et`

- ID=273 status=complete `https://www.bilibili.com/video/BV1X7411y7Kv`

- ID=508 status=complete `undefined`

- ID=512 status=loading `undefined`

- ID=291 status=complete `undefined`

- ID=294 status=complete `undefined`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[[\".{50}\",\"\"],[\"^[\\\\.。,，\\\\/\\\\?？!！~～@\\\\^、+=\\\\-_ ]+$\",\"\"],[\"^[^\\\\u4E00-\\\\u9FA5]$\",\"\"],[\"弹\\\\s*[屏幕][^护]*$\",\"\"],[\"倍速\",\"\"],[\"[3３三立]\\\\s+[dDＤ体體]\",\"\"],[\"(^|是)..[红橙黄绿青蓝紫黑白灰].{0,2}$\",\"\"],[\"^[第前]([0-9零一二两三四五六七八九十百千万亿].{0,6})?$\",\"\"],[\"^.{1,6}[天时点分钟秒]前\",\"\"],[\"^[0-9零一二两三四五六七八九十百千万亿nN]{1,4}(刷|周[木目])$\",\"\"],[\"破.*[wW万萬]\",\"\"],[\"[wW万萬]助攻\",\"\"],[\"钟的?诅咒\",\"\"],[\"口[气氣].*[集级]\",\"\"],[\"完结\",\"\"],[\"撒花\",\"\"],[\"从左到右\",\"\"],[\"[0-9万名].{1,6}[伴你们人友]($|.*[豪嚎号好])\",\"\"],[\"降.{0,3}(成功|失败|完美)\",\"\"],[\"完美空降\",\"\"],[\"空难(现场|$)\",\"\"],[\"[漂飘飄飙][移逸遗]\",\"\"],[\"[左右][漂飘飄飙]\",\"\"],[\"(\\\\s|^|[我怎来会].?)[漂飘飄飙]+($|.?[～~?？。，啊]|\\\\s)\",\"\"],[\"\\\\s{5}\",\"\"],[\"入(宅|坑$)\",\"\"],[\"^什么[!\\\\?！？，,、~\\\\s]\",\"\"],[\"^《.*》$\",\"\"],[\"^告诉.*[我还永]\",\"\"],[\"暴[露漏]((补番)?时间)?[了乐啦拉]\",\"\"],[\"周目($|.*(我|回|起|报|人|过|来|此))\",\"\"],[\"つロ|[干肝乾]杯\",\"\"],[\"[马馬][冬东]|[冬东]梅|[马馬]什么梅\",\"\"],[\"[fF]{3}.*(真爱|百合|基|性恋)\",\"\"],[\"豆腐.*[酸甜苦辣咸臭糖盐醋吃加]\",\"\"],[\"[酸甜苦辣咸臭糖盐醋吃加].*豆腐\",\"\"],[\"我的?(床上|老婆)\",\"\"],[\"我选\",\"\"],[\"(\\\\d{1,2}|十|十?[一二三四五六七八九十])([\\\\.,\\\\/:：、，；点\\\\-月。]|\\\\s+)(\\\\d{1,2}|[二三]?十|[二三]?十?[一二三四五六七八九]).{0,4}($|[日的过我别你上午夜晨])\",\"\"],[\"\\\\d\\\\d(\\\\d\\\\d)?([\\\\.,。，、\\\\/\\\\-年—*]|\\\\s+)\\\\d(\\\\d)?([\\\\.,。，、\\\\/\\\\-月—*]|\\\\s+)\\\\d\",\"\"],[\"^(2([^3]\\\\d|3[^3])|6([^6]\\\\d|6[^6])|[^26]\\\\d{2})\\\\d{0,5}$\",\"\"],[\"(元旦|年|国庆|春|秋|圣诞).?快乐\",\"\"]]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"on","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"off","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"on","REPRESENTATIVE_PERCENT":"20","SCROLL_THRESHOLD":"1200","SHRINK":"on","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1583814089009"}

**Request / Normal XML:** load, status=200 `<i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>e-r</source><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[₍₂₎</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好(13行FFT路过)₍₂₎</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>e-r</source><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 69 :: 1
</details>
<div><img src="https://s1.ax1x.com/2020/03/25/8vKjWF.png"></div>
上图中的“谢谢老师”没有被折叠，视频地址：https://www.bilibili.com/video/BV1X7411y7Kv

**Comment by xmcp** [comment]
在观看视频中动态产生的弹幕无法被pakku处理，建议勾选这个设置：
![image](https://user-images.githubusercontent.com/6646473/77535851-4cdf9800-6ed6-11ea-922c-83a056d9dc95.png)
