### ISSUE TITLE
弹幕信息显示框在macOS上失效

### ISSUE THREAD

**Issue by Sheey11** [xmcp/pakku.js#127]
在mac上 `control + 左键` = `右键`, 所以信息框只能看按住 `control` 的时候看见，一旦按下左键就无了，建议添加一个自定义按键  
![a](https://user-images.githubusercontent.com/13375959/79988882-c5d80c80-84e1-11ea-9b04-3d60b12a0494.gif)

**Comment by xmcp** [comment]
macOS 把 ctrl+左键强制重定向为右键好坑啊……

作为Workaround，**Ctrl+Cmd+左键** 试试。

**Comment by Sheey11** [comment]
- control command + 左键
- control option + 左键
都不行，只要带control就会被识别成右键
