### ISSUE TITLE
HTTPS模式下，有时候会显示一直在处理中

### ISSUE THREAD

**Issue by kang3185** [xmcp/pakku.js#13]
![image](https://cloud.githubusercontent.com/assets/12120052/26714273/63c2ff6a-47a3-11e7-8c87-bb623898668e.png)

**Comment by celeron533** [comment]
跨域问题？

**Comment by xmcp** [comment]
奇怪，在我这https一直没问题呀？……建议你提供以下信息以供调试：

- 扩展程序的版本号（目前最新的是4.0.1，如果不是就升级到最新的）
- pakku右上角的图标是否有任何角标文字（`FL!`, `NET!`, `SVR!`, 'JS!`, `...` 等）


以下页面的截图：

- b站视频页面的network面板（如果请求太多截不下就filter一下`.xml`）
- pakku.js背景页的network面板和console面板

> ps. 点这里打开pakku.js背景页的devtools：
> ![image](https://cloud.githubusercontent.com/assets/6646473/26721996/ba0992c2-47c0-11e7-8c25-d49991d1fe2e.png)


以及访问如下URL得到的结果：
- `https://comment.bilibili.com/1.xml`
- `https://comment.bilibili.com/1.debug.xml`
- `http://comment.bilibili.com/1.xml`
- `http://comment.bilibili.com/1.debug.xml`

**Comment by dramforever** [comment]
等下，这个 `api.bilibili.com` 不对啊……

@celeron533 扩展请求的“跨域”和页面的域无关，而且“有时”就比较尴尬了

**Comment by xmcp** [comment]
@dramforever 这报错跟pakku一点关系都没有，就是说视野范围内并没有pakku相关的异常。

但是如果pakku出现异常，会显示到background.html的console里而不是视频页的console里，所以这也是正常现象。（所以我需要background.html的console截图）

**Comment by xmcp** [comment]
我是滞胀。

这跟https一点关系都没有，其实是因为我在4.0里改了 `localStorage['TAOLUS']` 的格式，然后忘了 migrate 老用户的数据了……

总之，我是滞胀。

v4.1 终于加上了 migrate，所以更新到 4.1 或者手动清空一下 `localStorage['TAOLUS']` 再重启 chrome 就行了。
