### ISSUE TITLE
按住Ctrl时弹幕黄色底色问题

### ISSUE THREAD

**Issue by lidoworld** [xmcp/pakku.js#130]
开启插件后按住Ctrl键，弹幕底色会变黄。
不知道这是出于什么原因的设计。

对于我们习惯用Ctrl+Alt+A进行QQ截图的人来说，有点难受，不得不寻早其他截图工具避免这个问题。

**Comment by xmcp** [comment]
是”播放器增强“中的”弹幕信息显示框“，可以关闭
