### ISSUE TITLE
合并规则改进建议

### ISSUE THREAD

**Issue by LTHPKBTE** [xmcp/pakku.js#131]
如果弹幕大部分带空格，合并时会错误合并完全不相关的弹幕。
![图片](https://user-images.githubusercontent.com/53574505/80872535-1242f980-8ce5-11ea-9abe-b4053d40f439.png)
建议合并时忽略空格

**Comment by LTHPKBTE** [comment]
设置里的忽略空格是打开的

**Comment by xmcp** [comment]
看了下默认情况下这些弹幕不会被合并。你是不是设置了一些强制合并规则？

**Comment by LTHPKBTE** [comment]
没有怎么修改默认的规则
这是强制合并规则的截图
![图片](https://user-images.githubusercontent.com/53574505/80899164-89a57700-8d3f-11ea-8fe5-2f0e98f59df2.png)

**Comment by xmcp** [comment]
不知道怎么回事，建议贴一下完整设置和视频链接

**Comment by LTHPKBTE** [comment]
视频地址av54310679，截的是03:26秒时的顶部弹幕
完整设置贴图：
![图片](https://user-images.githubusercontent.com/53574505/80911272-e3ba3280-8d67-11ea-91d4-e52f0ed7411b.png)
![图片](https://user-images.githubusercontent.com/53574505/80911285-f2084e80-8d67-11ea-96eb-1c3b27864483.png)
![图片](https://user-images.githubusercontent.com/53574505/80911290-fa608980-8d67-11ea-9886-4ceed95c0b80.png)
