### ISSUE TITLE
[Enhancement]按照时间日期的早晚区间进行屏蔽处理

### ISSUE THREAD

**Issue by gaieepo** [xmcp/pakku.js#132]
目的：
1. 有部分视频有重投弹幕整合痕迹
2. 有部分视频或电影有太多时代感了，早两年和晚两年的关注很可能是不同的：如周杰伦的听妈妈的话关于小朋友是否有很多问号等多出自新梗。此服务于长期视频，电影的观者。

设计：
还没想好怎么整合。前期可作为全局参数在“设置页”进行设定。可以简单定为A-B区间式加可取反，屏蔽老弹幕，新弹幕和只关注一段时间内弹幕等。

**Comment by xmcp** [comment]
个性化的屏蔽需求建议使用 https://greasyfork.org/zh-CN/scripts/42635-pakku-advanced-filter 等
