### ISSUE TITLE
播放卡顿

### ISSUE THREAD

**Issue by SanceTb** [xmcp/pakku.js#136]
如题，播放时会出现弹幕卡顿的情况，具体来说就是滚动弹幕会停滞一会儿。但是视频本身播放流畅。关闭本插件后弹幕回复流畅。卡顿频率与视频码率无关。
环境Win10 Pro 64bit，Firefox最新版，已关闭其他所有插件。硬件i7-10700k + GTX1650

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 9.3.1

**Channel:** firefox

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0`

**Incognito:** `false`

**localStorage:** `{"FLUCTLIGHT":"off","BREAK_UPDATE":"off","MAX_COSINE":"60","TRIM_SPACE":"on","DANMU_SUBSCRIPT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","TRIM_PINYIN":"on","POPUP_BADGE":"percent","REMOVE_SEEK":"off","TOOLTIP":"on","MAX_DIST":"5","SCROLL_THRESHOLD":"1200","WHITELIST":"[]","REPRESENTATIVE_PERCENT":"0","MODE_ELEVATION":"on","DANMU_MARK":"prefix","PROC_TYPE7":"on","SHRINK":"on","TRIM_ENDING":"on","MARK_THRESHOLD":"3","CROSS_MODE":"on","PROC_POOL1":"off","ENLARGE":"on","BLACKLIST":"[]","AUTO_DISABLE_DANMU":"off","TAOLUS":"","_LAST_UPDATE_TIME":"1591517638664","AUTO_DANMU_LIST":"off","PROC_TYPE4":"on","TRIM_WIDTH":"on","HIDE_THRESHOLD":"0","FLASH_NOTIF":"on","THRESHOLD":"15","CLOUD_SYNC":"off","_ADVANCED_USER":"on"}`

**Views:**

- `moz-extension://805ea3da-ed5c-4f21-8b40-30e31922f751/core/background.html`

- `moz-extension://805ea3da-ed5c-4f21-8b40-30e31922f751/page/options.html`

- `moz-extension://805ea3da-ed5c-4f21-8b40-30e31922f751/page/troubleshooting.html`

**Background / IS_FIREFOX:** true

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{}`

**Permissions:** `{"origins":["*://*.bilibili.com/*","ws://*.bilibili.com/*","wss://*.bilibili.com/*"],"permissions":["webRequest","webRequestBlocking","notifications","storage"]}`

**Storage / Sync:** {"_LAST_UPDATE_TIME":"1591517638664","_ADVANCED_USER":"on","THRESHOLD":"15","TAOLUS":"","SHRINK":"on","MARK_THRESHOLD":"3","REPRESENTATIVE_PERCENT":"0","FLUCTLIGHT":"off","DANMU_MARK":"prefix","WHITELIST":"[]","TRIM_WIDTH":"on","TRIM_SPACE":"on","TRIM_PINYIN":"on","TRIM_ENDING":"on","TOOLTIP":"on","SCROLL_THRESHOLD":"1200","REMOVE_SEEK":"off","PROC_TYPE7":"on","PROC_TYPE4":"on","PROC_POOL1":"off","POPUP_BADGE":"percent","MODE_ELEVATION":"on","MAX_DIST":"5","MAX_COSINE":"60","HIDE_THRESHOLD":"0","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","FLASH_NOTIF":"on","ENLARGE":"on","DANMU_SUBSCRIPT":"on","CROSS_MODE":"on","CLOUD_SYNC":"off","BREAK_UPDATE":"off","BLACKLIST":"[]","AUTO_DISABLE_DANMU":"off","AUTO_DANMU_LIST":"off"}

**Tabs:**

- ID=3 status=complete `undefined`

- ID=4 status=complete `undefined`

- ID=5 status=complete `undefined`

- ID=6 status=complete `undefined`

- ID=7 status=complete `undefined`

- ID=8 status=complete `undefined`

- ID=9 status=complete `undefined`

- ID=10 status=complete `undefined`

- ID=11 status=complete `undefined`

- ID=12 status=complete `undefined`

- ID=13 status=complete `undefined`

- ID=101 status=complete `undefined`

- ID=103 status=complete `undefined`

- ID=104 status=complete `undefined`

- ID=105 status=complete `undefined`

- ID=107 status=complete `undefined`

- ID=247 status=complete `undefined`

- ID=249 status=complete `undefined`

- ID=251 status=complete `undefined`

- ID=261 status=complete `undefined`

- ID=108 status=complete `undefined`

- ID=109 status=complete `undefined`

- ID=111 status=complete `undefined`

- ID=115 status=complete `undefined`

- ID=119 status=complete `undefined`

- ID=253 status=complete `undefined`

- ID=256 status=complete `undefined`

- ID=257 status=complete `undefined`

- ID=260 status=complete `undefined`

- ID=14 status=complete `undefined`

- ID=15 status=complete `undefined`

- ID=2 status=complete `undefined`

- ID=16 status=complete `undefined`

- ID=133 status=complete `undefined`

- ID=134 status=complete `undefined`

- ID=18 status=complete `undefined`

- ID=39 status=complete `undefined`

- ID=40 status=complete `undefined`

- ID=41 status=complete `undefined`

- ID=43 status=complete `undefined`

- ID=155 status=complete `undefined`

- ID=51 status=complete `undefined`

- ID=296 status=complete `undefined`

- ID=136 status=complete `undefined`

- ID=137 status=complete `undefined`

- ID=145 status=complete `undefined`

- ID=146 status=complete `undefined`

- ID=96 status=complete `undefined`

- ID=148 status=complete `undefined`

- ID=149 status=complete `undefined`

- ID=150 status=complete `undefined`

- ID=151 status=complete `undefined`

- ID=63 status=complete `undefined`

- ID=65 status=complete `undefined`

- ID=67 status=complete `undefined`

- ID=68 status=complete `undefined`

- ID=69 status=complete `undefined`

- ID=71 status=complete `undefined`

- ID=72 status=complete `undefined`

- ID=73 status=complete `undefined`

- ID=74 status=complete `undefined`

- ID=45 status=complete `undefined`

- ID=113 status=complete `undefined`

- ID=297 status=complete `undefined`

- ID=298 status=loading `undefined`

- ID=120 status=complete `undefined`

- ID=122 status=complete `undefined`

- ID=123 status=complete `undefined`

- ID=124 status=complete `undefined`

- ID=125 status=complete `undefined`

- ID=126 status=complete `undefined`

- ID=156 status=complete `undefined`

- ID=157 status=complete `undefined`

- ID=164 status=complete `undefined`

- ID=165 status=complete `undefined`

- ID=158 status=complete `undefined`

- ID=160 status=complete `undefined`

- ID=163 status=complete `undefined`

- ID=166 status=complete `undefined`

- ID=167 status=complete `undefined`

- ID=168 status=complete `undefined`

- ID=178 status=complete `undefined`

- ID=242 status=complete `undefined`

- ID=246 status=complete `undefined`

- ID=262 status=complete `undefined`

- ID=129 status=complete `undefined`

- ID=131 status=complete `undefined`

- ID=132 status=complete `undefined`

- ID=227 status=complete `undefined`

- ID=228 status=complete `undefined`

- ID=230 status=complete `undefined`

- ID=234 status=complete `undefined`

- ID=241 status=complete `undefined`

- ID=252 status=complete `undefined`

- ID=203 status=complete `undefined`

- ID=204 status=complete `undefined`

- ID=206 status=complete `undefined`

- ID=214 status=complete `undefined`

- ID=215 status=complete `undefined`

- ID=218 status=complete `undefined`

- ID=221 status=complete `undefined`

- ID=223 status=complete `undefined`

- ID=224 status=complete `undefined`

- ID=207 status=complete `undefined`

- ID=210 status=complete `undefined`

- ID=225 status=complete `undefined`

- ID=226 status=complete `undefined`

- ID=213 status=complete `undefined`

- ID=235 status=complete `undefined`

- ID=236 status=complete `undefined`

- ID=237 status=complete `undefined`

- ID=238 status=complete `undefined`

- ID=239 status=complete `undefined`

- ID=264 status=complete `undefined`

- ID=265 status=complete `undefined`

- ID=266 status=complete `undefined`

- ID=267 status=complete `undefined`

- ID=283 status=complete `undefined`

- ID=284 status=complete `undefined`

- ID=268 status=complete `undefined`

- ID=285 status=complete `undefined`

- ID=269 status=complete `undefined`

- ID=278 status=complete `undefined`

- ID=280 status=complete `undefined`

- ID=281 status=complete `undefined`

- ID=282 status=complete `undefined`

- ID=279 status=complete `undefined`

- ID=286 status=complete `undefined`

- ID=287 status=complete `undefined`

- ID=288 status=complete `undefined`

- ID=289 status=complete `undefined`

- ID=290 status=complete `undefined`

- ID=291 status=complete `undefined`

- ID=292 status=complete `undefined`

- ID=293 status=complete `undefined`

- ID=294 status=complete `undefined`

- ID=274 status=complete `undefined`

- ID=275 status=complete `undefined`

- ID=276 status=complete `undefined`

- ID=295 status=complete `undefined`

- ID=270 status=complete `undefined`

- ID=271 status=complete `undefined`

- ID=272 status=complete `undefined`

- ID=273 status=complete `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>e-r</source><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d></i>`

**Request / Normal XML:** load, status=200 `<i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>e-r</source><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d></i>`

**! Exception:** `ReferenceError: test_error_log is not defined`

`moz-extension://805ea3da-ed5c-4f21-8b40-30e31922f751/page/troubleshooting.js` :: 2 :: 2228

</details>

**Comment by SanceTb** [comment]
多播了几个视频，<b>似乎</b>舞蹈区卡顿尤甚？猜测是舞蹈区开了弹幕防遮挡功能？

**Comment by SanceTb** [comment]
有一说一，您这个回复有点令人困惑

**Comment by xmcp** [comment]
pakku只是修改了弹幕数据，没有参与渲染过程，应该不是pakku的锅，而且没法复现，所以close。
