### ISSUE TITLE
如何根据弹幕列表获取到发送者信息

### ISSUE THREAD

**Issue by consideration-ak** [xmcp/pakku.js#138]
想问一下是如何根据弹幕列表获取到发送者信息的, 看了那些参数没看出可用的信息

**Comment by xmcp** [comment]
？

**Comment by consideration-ak** [comment]
就是扩展怎么根据https://api.bilibili.com/x/v1/dm/list.so?oid=183886114
里面的这些参数<d p="16.06100,1,25,16777215,1587974167,0,4982e0a0,31893483871010821">喵喵我来啦！</d>获取到uid信息的

**Comment by consideration-ak** [comment]
不需要了, 我懂了
