### ISSUE TITLE
关于看不清预览弹幕

### ISSUE THREAD

**Issue by Cirsth** [xmcp/pakku.js#139]
弹幕密度分析图上面的预览弹幕和背景色的颜色接近，请问能修改弹幕字体颜色么？
![J}7`8Q_TH3{ H@GV42RT{Q](https://user-images.githubusercontent.com/52486051/87007378-c2a51080-c1f4-11ea-837a-0cc9935ef423.png)

**Comment by xmcp** [comment]
![image](https://user-images.githubusercontent.com/6646473/87024737-1707ba80-c20c-11ea-8da0-f1f761327eff.png)
颜色应当是黑色的，显示成灰色可能是你用了其他修改页面样式的脚本
