### ISSUE TITLE
弹幕时间全部清零

### ISSUE THREAD

**Issue by LTHPKBTE** [xmcp/pakku.js#140]
昨天还用的很正常，今天凌晨开始打开pakku会导致弹幕全部都被定位在视频开头的0:00，基本排除其他插件造成的问题，关掉pakku就恢复正常。
正常状态的弹幕列表：
![图片](https://user-images.githubusercontent.com/53574505/87181360-c760e600-c314-11ea-8aed-ed47f7571547.png)
打开pakku后的弹幕列表：
![图片](https://user-images.githubusercontent.com/53574505/87181499-05f6a080-c315-11ea-8c6d-f2937ee54157.png)
版本pakku v10.0_F
调试信息：
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.0

**Channel:** firefox

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0`

**Incognito:** `false`

**localStorage:** `{"FLUCTLIGHT":"off","BREAK_UPDATE":"off","MAX_COSINE":"85","TRIM_SPACE":"on","DANMU_SUBSCRIPT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","TRIM_PINYIN":"on","POPUP_BADGE":"percent","REMOVE_SEEK":"off","TOOLTIP":"on","MAX_DIST":"3","SCROLL_THRESHOLD":"1200","WHITELIST":"[]","REPRESENTATIVE_PERCENT":"20","MODE_ELEVATION":"on","DANMU_MARK":"suffix","PROC_TYPE7":"on","SHRINK":"off","TRIM_ENDING":"on","MARK_THRESHOLD":"1","CROSS_MODE":"on","PROC_POOL1":"off","ENLARGE":"on","BLACKLIST":"[]","AUTO_DISABLE_DANMU":"off","TAOLUS":"","_LAST_UPDATE_TIME":"1589392901842","AUTO_DANMU_LIST":"off","PROC_TYPE4":"on","TRIM_WIDTH":"on","_pakku_stats_time":"120/6/11","HIDE_THRESHOLD":"0","FLASH_NOTIF":"on","THRESHOLD":"20","CLOUD_SYNC":"off","_ADVANCED_USER":"off"}`

**Views:**

- `moz-extension://4dbaac03-99a9-4525-bbe4-fb7e3e7b4edd/core/background.html`

- `moz-extension://4dbaac03-99a9-4525-bbe4-fb7e3e7b4edd/page/options.html`

- `moz-extension://4dbaac03-99a9-4525-bbe4-fb7e3e7b4edd/page/troubleshooting.html`

**Background / IS_FIREFOX:** true

**Background / GLOBAL_SWITCH:** false

**Background / HISTORY:** `{"7":{"identical":471,"edit_distance":355,"pinyin_distance":67,"cosine_distance":21,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":2,"total":6000,"onscreen":5086,"maxcombo":16,"maxdispval":"","error":null,"cid":"131021612","parse_time_ms":229},"8":{"identical":0,"edit_distance":0,"pinyin_distance":0,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":0,"total":0,"onscreen":0,"maxcombo":0,"maxdispval":"","error":null,"cid":"54859635","parse_time_ms":1},"9":{"identical":33,"edit_distance":25,"pinyin_distance":1,"cosine_distance":11,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":3,"total":804,"onscreen":734,"maxcombo":19,"maxdispval":"","error":null,"cid":"210628845","parse_time_ms":22},"12":{"identical":1,"edit_distance":1,"pinyin_distance":0,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":0,"total":9,"onscreen":7,"maxcombo":2,"maxdispval":"","error":null,"cid":"12664443","parse_time_ms":2}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*","ws://*.bilibili.com/*","wss://*.bilibili.com/*"],"permissions":["webRequest","webRequestBlocking","notifications","storage"]}`

**Storage / Sync:** {"_LAST_UPDATE_TIME":"1589392901842","TAOLUS":"","REPRESENTATIVE_PERCENT":"20","MAX_DIST":"3","MAX_COSINE":"85","DANMU_MARK":"suffix","_pakku_stats_time":"120/4/3","_ADVANCED_USER":"off","WHITELIST":"[]","TRIM_WIDTH":"on","TRIM_SPACE":"on","TRIM_PINYIN":"on","TRIM_ENDING":"on","TOOLTIP":"on","THRESHOLD":"20","SHRINK":"off","SCROLL_THRESHOLD":"1200","REMOVE_SEEK":"off","PROC_TYPE7":"on","PROC_TYPE4":"on","PROC_POOL1":"off","POPUP_BADGE":"percent","MODE_ELEVATION":"on","MARK_THRESHOLD":"1","HIDE_THRESHOLD":"0","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","FLUCTLIGHT":"off","FLASH_NOTIF":"on","ENLARGE":"on","DANMU_SUBSCRIPT":"on","CROSS_MODE":"on","CLOUD_SYNC":"off","BREAK_UPDATE":"off","BLACKLIST":"[]","AUTO_DISABLE_DANMU":"off","AUTO_DANMU_LIST":"off"}

**Tabs:**

- ID=1 status=complete `undefined`

- ID=7 status=complete `undefined`

- ID=14 status=complete `undefined`

- ID=20 status=complete `undefined`

- ID=21 status=loading `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d></i>`

**! Exception:** `ReferenceError: test_error_log is not defined`

`moz-extension://4dbaac03-99a9-4525-bbe4-fb7e3e7b4edd/page/troubleshooting.js` :: 2 :: 2228

</details>

**Comment by f1ume** [comment]
我找到是 合并后的弹幕显示于 那里，只有最先出现是正常的。20% 50%都变成排在00:00

**Comment by sandyhxu** [comment]
设置合并后的弹幕显示于20%/50%出现的时间时，所有弹幕（无论是否为多条合并）的时间均为00:00，相似弹幕合并前每条的时间未受影响

**Comment by zhuoyw** [comment]
+1

**Comment by xmcp** [comment]
v10.0.1版本已修复。
（v10.0更新比较大，可能有一些bug）
