### ISSUE TITLE
希望加入屏蔽用户功能

### ISSUE THREAD

**Issue by Noomob** [xmcp/pakku.js#141]
b站云端同步的屏蔽用户上限是1333个，看几部电影屏蔽完发“第一”之类的用户已经超上限了，而且最关键的是不知为何有时会自动取消一些用户的屏蔽。

**Comment by xmcp** [comment]
此需求与pakku主要功能无关。如果确实有这种需求可以尝试自己写用户脚本来完成，参考 https://github.com/xmcp/pakku-advanced-filter
