### ISSUE TITLE
哔哩哔哩播放器改版后，按住Ctrl高亮并可以选中弹幕的功能失效

### ISSUE THREAD

**Issue by CKylinMC** [xmcp/pakku.js#143]
哔哩哔哩播放器改版了，之后以前的按住Ctrl高亮弹幕的功能失效，表现是Ctrl按住时没有任何反应。

其他功能目前没发现问题

版本号：v10.0.1_C

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.0.1

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"prefix","TAOLUS":"","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1589098475281","FLASH_NOTIF":"on","_ADVANCED_USER":"on","SHRINK":"on","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","REMOVE_SEEK":"off","POPUP_BADGE":"percent","WHITELIST":"[]","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"on","PROC_TYPE7":"on","THRESHOLD":"20","TRIM_WIDTH":"on","PROC_POOL1":"on","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"153":{"identical":790,"edit_distance":244,"pinyin_distance":7,"cosine_distance":111,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":"","script":0,"enlarge":29,"shrink":474,"scroll":1,"taolu":76,"total":3000,"onscreen":1848,"maxcombo":331,"maxdispval":147.36711652980418,"error":null,"cid":"218049736","parse_time_ms":123},"160":{"identical":0,"edit_distance":0,"pinyin_distance":0,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":"","script":0,"enlarge":0,"shrink":0,"scroll":0,"taolu":0,"total":2,"onscreen":2,"maxcombo":1,"maxdispval":4.23606797749979,"error":null,"cid":"218177055","parse_time_ms":1},"168":{"identical":68,"edit_distance":112,"pinyin_distance":9,"cosine_distance":2,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":"","script":0,"enlarge":5,"shrink":55,"scroll":0,"taolu":9,"total":1518,"onscreen":1327,"maxcombo":14,"maxdispval":121.8477113259126,"error":null,"cid":"65988254","parse_time_ms":99},"208":{"identical":327,"edit_distance":232,"pinyin_distance":26,"cosine_distance":299,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":"","script":0,"enlarge":28,"shrink":237,"scroll":0,"taolu":39,"total":2000,"onscreen":1116,"maxcombo":172,"maxdispval":151.9632536430824,"error":null,"cid":"123611012","parse_time_ms":116}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"on","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"on","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1589098475281"}

**Tabs:**

- ID=2 status=complete `https://www.bilibili.com/`

- ID=168 status=complete `https://www.bilibili.com/video/av4714372`

- ID=205 status=complete `https://space.bilibili.com/108592/dynamic`

- ID=199 status=complete `undefined`

- ID=438 status=loading `undefined`

- ID=153 status=complete `https://www.bilibili.com/video/av711608708`

- ID=401 status=complete `undefined`

- ID=404 status=complete `undefined`

- ID=435 status=complete `undefined`

- ID=414 status=complete `undefined`

- ID=426 status=complete `undefined`

- ID=429 status=complete `undefined`

- ID=432 status=complete `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by xmcp** [comment]
v10.0.2已修复该问题。Chrome和Firefox将很快更新，Edge可能要等最多一周。
