### ISSUE TITLE
NET!正在下载弹幕文件

### ISSUE THREAD

**Issue by xxemojtr** [xmcp/pakku.js#145]
无法正常合并弹幕，
使用时图标上显示红色NET！，
浮动标签显示“正在下载弹幕...”，
点击图标显示
“网络错误

CID = 218667185

undefined

undefined”

调试信息如下
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.0.1

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"prefix","CLOUD_SYNC":"off","BLACKLIST":"[]","_LAST_UPDATE_TIME":"0","_ADVANCED_USER":"off","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","REMOVE_SEEK":"off","POPUP_BADGE":"percent","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","WHITELIST":"[]","PROC_TYPE7":"on","THRESHOLD":"20","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"60":{"error":"网络错误","cid":"218667185","details":"undefined\n\nundefined"}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"0"}

**Permissions:** `{"origins":["https://www.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=2 status=complete `undefined`

- ID=60 status=complete `https://www.bilibili.com/video/BV1Eh411Z7yu?spm_id_from=333.851.b_7265706f7274466972737431.9`

- ID=64 status=complete `undefined`

- ID=67 status=loading `undefined`

**Request / Normal XML:** error, status=0 ``

**Request / XML With Param:** error, status=0 ``

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

chrome浏览器扩展程序页面显示错误，信息如下
A cookie associated with a cross-site resource at http://xmcp.ml/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

A cookie associated with a cross-site resource at http://s.xmcp.ml/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

pakku: [to developers] Web Worker is disabled for compatibility reasons

Access to XMLHttpRequest at 'https://api.bilibili.com/x/v2/dm/web/view?type=1&oid=218667185&pid=201540404&pakku_request' from origin 'chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Access to XMLHttpRequest at 'https://api.bilibili.com/x/v2/dm/web/seg.so?type=1&oid=218667185&pid=201540404&segment_index=1&pakku_request' from origin 'chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Uncaught (in promise) #<ProgressEvent>

A cookie associated with a cross-site resource at http://xmcp.ml/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

A cookie associated with a cross-site resource at http://s.xmcp.ml/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

Uncaught ReferenceError: test_error_log is not defined

Access to XMLHttpRequest at 'https://comment.bilibili.com/12664443.xml' from origin 'chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Access to XMLHttpRequest at 'https://comment.bilibili.com/12664443.xml?foo' from origin 'chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by xmcp** [comment]
参见 #144
不知道你是否修改了pakku的权限设置，还是chrome又出了什么bug。请如图所示打开下面的权限开关，否则请求不了弹幕↓
![image](https://user-images.githubusercontent.com/6646473/89094927-82077400-d3fb-11ea-9e79-bfe8754864b1.png)

**Comment by xxemojtr** [comment]
好了，感觉是chrome背锅，之前正常的，不知道在哪一次浏览器更新之后出问题了。也许可以把这一条写到介绍页里？

**Comment by xmcp** [comment]
![image](https://user-images.githubusercontent.com/6646473/89095716-2345f880-d403-11ea-8bcc-410ab7d00510.png)
你有没有点过这个选项？我发现只要点一下它，pakku的权限就会从*.bilibili.com变成www.bilibili.com（然后弹幕请求就挂了）
下个版本我加个提示吧……这太恶心了

**Comment by xxemojtr** [comment]
应该没有，我已经至少间隔了两三次chrome更新的时间没动过pakku了（指根本没用B站看视频）。这几天发现问题之后我还特意更新了chrome和插件，发现都不行才来反馈的。
