### ISSUE TITLE
[feature request] 请求推出 Safari 版

### ISSUE THREAD

**Issue by doooooit** [xmcp/pakku.js#146]
请求移植到 Safari 平台，而且 macOS Big Sur 中到 Safari 提供了 WebExtensions API

**Comment by xmcp** [comment]
没有macOS开发环境，暂不考虑。

**Comment by yjc567** [comment]
@xmcp 请问您允许有条件的开发者根据源码编译插件并在mac app store 里面发布吗？

**Comment by xmcp** [comment]
@yjc567  遵循GPL就行。
另外我看了WWDC20的几个session video，感觉扩展移植可能会遇到很多safari特有的权限问题，祝好运（
