### ISSUE TITLE
视频切换分p时偶发的不断重复下载/拉取/刷新(?)弹幕文件或无弹幕的问题

### ISSUE THREAD

**Issue by DuskShadows** [xmcp/pakku.js#147]
该情况发现于chrome浏览器，其他浏览器情况未测试

视频切换分p或番剧作品切换集数时偶尔出现，现发现有两种情况：
1.弹幕文件不断被重新加载(?)，具体表现为右上角图标蓝绿框不断高速切换；功能正常，但cpu性能占用急剧升高，关闭浏览器后重启或暂停后继续播放可恢复
2.弹幕列表显示为空，弹幕内容为空，图标显示为未侦测到B站播放器；该情况多发生于情况1发生时采用暂停后继续播放或刷新页面的方法后，重新切换分p或级数可恢复

该问题并不会导致完全无法使用，姑且附上调试信息：

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.0.2

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"suffix","CLOUD_SYNC":"off","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1596513549432","_ADVANCED_USER":"on","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","REMOVE_SEEK":"off","POPUP_BADGE":"percent","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","WHITELIST":"[]","PROC_TYPE7":"on","THRESHOLD":"15","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"off","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"21":{"identical":24,"edit_distance":98,"pinyin_distance":2,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":6,"shrink":"","scroll":0,"taolu":4,"total":1102,"onscreen":978,"maxcombo":9,"maxdispval":116.38963631656159,"error":null,"cid":"138215044","parse_time_ms":63},"70":{"identical":173,"edit_distance":399,"pinyin_distance":17,"cosine_distance":80,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":23,"shrink":"","scroll":0,"taolu":7,"total":3000,"onscreen":2331,"maxcombo":35,"maxdispval":125.41831480917793,"error":null,"cid":"136487525","parse_time_ms":59},"78":{"identical":395,"edit_distance":802,"pinyin_distance":26,"cosine_distance":53,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":50,"shrink":"","scroll":0,"taolu":12,"total":6000,"onscreen":4724,"maxcombo":16,"maxdispval":212.85159298584696,"error":null,"cid":"123556724","parse_time_ms":169}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"off","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"15","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1596513549432"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=2 status=complete `undefined`

- ID=14 status=complete `undefined`

- ID=15 status=complete `undefined`

- ID=16 status=complete `undefined`

- ID=18 status=complete `https://www.bilibili.com/`

- ID=78 status=complete `https://www.bilibili.com/bangumi/play/ep285193`

- ID=90 status=loading `undefined`

- ID=93 status=loading `undefined`

- ID=75 status=complete `https://search.bilibili.com/all?keyword=%E9%87%8D%E5%90%AF%E5%92%B2%E8%89%AF%E7%94%B0`

- ID=20 status=complete `https://www.bilibili.com/bangumi/media/md28226651/`

- ID=21 status=complete `https://www.bilibili.com/bangumi/play/ep306593`

- ID=49 status=complete `undefined`

- ID=54 status=complete `undefined`

- ID=84 status=complete `undefined`

- ID=81 status=complete `undefined`

- ID=87 status=complete `undefined`

- ID=60 status=complete `undefined`

- ID=55 status=complete `undefined`

- ID=67 status=complete `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by xmcp** [comment]
无法复现这个bug

**Comment by DuskShadows** [comment]
快速切换集数后刷新极容易触发情况2，且无法通过点下一集切换集数；快速切换集数容易触发情况1
![弹幕栏空白且弹幕不显示](https://user-images.githubusercontent.com/65220815/89437947-c6d43780-d77a-11ea-9a7b-3acf620662cb.png)
上图为情况2，右上角弹幕栏不显示且播放时无弹幕，在该情况下关闭插件刷新仍无法正常显示弹幕
![情况1时具体表现](https://user-images.githubusercontent.com/65220815/89438784-d3a55b00-d77b-11ea-838e-41935ea1ef14.png)
上图为情况1，弹幕偶然出现不显示的情况
![较高的性能占用](https://user-images.githubusercontent.com/65220815/89438909-fe8faf00-d77b-11ea-9569-886a3503812b.png)
出现该情况时只打开了视频页面及该页面，最高时对cpu占用达到100%

测试过程中出现1次B站播放器因频繁切换集数并开始播放崩溃的情况

**Comment by xmcp** [comment]
“在该情况下关闭插件刷新仍无法正常显示弹幕”
关闭pakku都显示不出来弹幕，看起来像b站的bug？

**Comment by DuskShadows** [comment]
个人推测可能是因为快速切换视频使B站播放器处于持续加载弹幕的情况无法恢复，从而导致弹幕不断被过滤或是处于无法显示的状态

**Comment by xmcp** [comment]
所以即使不使用pakku，快速换P的时候弹幕也有问题是吗？如果是那这就是B站播放器的bug（而不是我的

**Comment by DuskShadows** [comment]
在关闭插件时频繁切换分集后开始播放确实会出现弹幕无法显示的问题(情况2)，看起来应该是B站播放器的问题，情况1估计也是由B站播放器引起
