### ISSUE TITLE
扩展无法正常工作，无论是在http还是https下

### ISSUE THREAD

**Issue by qjzcj2008** [xmcp/pakku.js#15]
扩展程序的版本号 4.0.1 
Chrome版本号58.0.3029.110 (正式版本) （64 位）
Windows 10 1703
pakku右上角的图标有JS!角标文字  
![2017-06-03_005614](https://cloud.githubusercontent.com/assets/16514953/26736616/738b1ed6-47f9-11e7-8032-68b90b0f88ec.png)
这个问题是每次都会出现
这个问题在所有视频里出现
以及复现bug时以下页面的截图：

b站视频页面的network面板（如果请求太多截不下就filter一下.xml）
![2017-06-03_011108](https://cloud.githubusercontent.com/assets/16514953/26736641/8f77d71a-47f9-11e7-9ff2-f1e0079e3164.png)

pakku.js背景页的network面板和console面板
![2017-06-03_011206](https://cloud.githubusercontent.com/assets/16514953/26736686/c9a72e90-47f9-11e7-9578-d946a500cff2.png)
![2017-06-03_011215](https://cloud.githubusercontent.com/assets/16514953/26736688/cc06f788-47f9-11e7-8221-e4e3c377c741.png)

以及在chrome里直接访问如下URL得到的结果：

https://comment.bilibili.com/1.xml 正常
https://comment.bilibili.com/1.debug.xml 404
http://comment.bilibili.com/1.xml 正常
http://comment.bilibili.com/1.debug.xml 404

**Comment by xmcp** [comment]
#13
