### ISSUE TITLE
可以增加一个弹幕移花接木的功能吗？

### ISSUE THREAD

**Issue by CodesHunger** [xmcp/pakku.js#150]
发现有些相同的视频，一个没字幕但是很多弹幕，另一个则没弹幕但是有字幕，请问可以增加一个功能，把弹幕嫁接在另一个视频上吗？

**Comment by xmcp** [comment]
这种场景过于特殊的需求pakku一般不做，不过提供了userscript的接口，如果需要可以自己实现一下。示例参见 https://github.com/xmcp/pakku-advanced-filter

**Comment by CodesHunger** [comment]
感谢回复，速度好快……
知道能做到就好，抓瞎，得学一下怎么写脚本了
