### ISSUE TITLE
[bug]弹幕覆盖层失效

### ISSUE THREAD

**Issue by LTHPKBTE** [xmcp/pakku.js#151]
关于：弹幕信息显示框
描述：现在把鼠标放在弹幕上面会优先弹出点赞和举报键，按住Ctrl点击弹幕显示详情的功能被覆盖导致失效了
版本：v10.0.2_F

**Comment by xmcp** [comment]
已修复，请更新到v10.0.4版本（Chrome和Edge商店需要审核可能会晚一些时间）
