### ISSUE TITLE
弹幕查询发送者问题

### ISSUE THREAD

**Issue by just-automatic** [xmcp/pakku.js#154]
为什么 [这个视频](https://www.bilibili.com/video/av287638605) 下面的弹幕查询发送者提示 `UID不存在`

调试信息: 
> pakku injector: root_elem not found

 > ![console截图](https://i.loli.net/2020/11/14/LovZ6rWJ9fVmOwC.png)

**Comment by xmcp** [comment]
B站的UID突破10位数了，现在pakku只支持计算9位数以内的UID（当时写的时候没想到B站用户能有这么多……）。
改一行代码就能解决，下个版本修复吧。

**Comment by consideration-ak** [comment]
好的, 谢谢大佬答复
