### ISSUE TITLE
→ 官方安利 ← 的弹幕黑名单正则里有一条会把空降指挥部炸了

### ISSUE THREAD

**Issue by StarXu** [xmcp/pakku.js#155]
找了下似乎是这条会屏蔽所有时间弹幕而不只是日期弹幕
  < 日期相关 >
(\d{1,2}|十|十?[一二三四五六七八九十])([\.,\/:：、，；点\-月。]|\s+)(\d{1,2}|[二三]?十|[二三]?十?[一二三四五六七八九]).{0,4}($|[日的过我别你上午夜晨])

**Comment by xmcp** [comment]
那就删掉这条规则呗
