### ISSUE TITLE
请求添加新功能

### ISSUE THREAD

**Issue by PairZhu** [xmcp/pakku.js#156]
能不能添加一个弹幕密度开关的功能：当弹幕密度高于设定的某一阈值时，脚本才开始工作

**Comment by ljcbaby** [comment]
确实，本来有些视频的弹幕就少的可怜，没必要合并

**Comment by 784017670** [comment]
有没有办法改变弹幕的显示区域范围，目前最小的1/4屏幕对我来说，其实还是太多了，大部分情况下，我只想显示两到三行，窄窄的，跟电影字幕一样，而不是挡住视频本身。

**Comment by xmcp** [comment]
可以升级到 [v2024.3.1](https://github.com/xmcp/pakku.js/releases/tag/2024.3.1) 后通过 [用户脚本](https://github.com/xmcp/pakku.js/blob/master/userscript_docs/README.md) 实现此功能
