### ISSUE TITLE
Alt+R 关闭过滤后网页只请求3000条弹幕 长视频有点少

### ISSUE THREAD

**Issue by cmmdwl** [xmcp/pakku.js#157]

**Comment by cmmdwl** [comment]
![GIF 2020-12-28 16-36-44](https://user-images.githubusercontent.com/21263352/103201472-f1da4600-492a-11eb-8bb8-04b24e6d7eab.gif)

**Comment by xmcp** [comment]
这是b站自身的问题。
pakku的动态切换是通过模拟点击今天的“历史弹幕”按钮实现的，然而b站直接加载弹幕会请求v2的API，历史弹幕会请求v1的API，v1返回的弹幕数量比较少。
在b站解决这个差异之前可以考虑手动刷新页面……

**Comment by xmcp** [comment]
Will probably be fixed after #162 is fixed
