### ISSUE TITLE
新型弹幕适配

### ISSUE THREAD

**Issue by just-automatic** [xmcp/pakku.js#159]
新型弹幕--UP 主弹幕按住 Ctrl 然后 hover 的时候无法显示弹幕发送者信息, 虽然都已经知道是 UP 主弹幕了也没啥必要查询发送者信息, 但是也算是一个小 bug 吧, 所以提一下
![QQ图片20210128230356](https://user-images.githubusercontent.com/67540802/106157576-b7d1af00-6137-11eb-8e1c-7750ffde3cf2.png)
![QQ图片20210128230409](https://user-images.githubusercontent.com/67540802/106157610-bd2ef980-6137-11eb-92a2-6a9de521e4c5.png)
视频链接: https://www.bilibili.com/video/av843424904/, 弹幕出现在 25s 左右

**Comment by xmcp** [comment]
B站的UP主弹幕目前是跟其他播放器命令（`commandDms`）一起下发的，是在 `/x/v2/dm/web/view` 这个请求里。
而pakku处理的弹幕池是在 `/x/v2/dm/web/seg.so` 这个请求里。pakku只拦截 `seg.so` 请求，不拦截 `view` 请求。

说人话就是pakku现在根本不处理UP主弹幕，所以显示不了相关的信息。

目前来看UP主弹幕还比较罕见，不值得为此对 `view` 加一个新的hook（`view` 请求还包括其他播放器设置，所以hook它的话pakku以后需要跟B站前端同步更新，不然可能导致播放器出问题）。以后如果确实需要hook `view` 再考虑做这个功能。

**Comment by just-automatic** [comment]
了解
