### ISSUE TITLE
看起来好像不是api的问题，我又试了一下，CONSOLE如下：

### ISSUE THREAD

**Issue by Meihina** [xmcp/pakku.js#164]
看起来好像不是api的问题，我又试了一下，CONSOLE如下：  

![W319U}7P9GK2EF((C%{XGUK](https://user-images.githubusercontent.com/50244072/106793940-11cff880-6693-11eb-90da-b2d74a267e95.png)

不太懂插件，粗略看了一下代码似乎是 ‘pakku_set_danmaku_bounce’ 事件上出了问题，可能关联代码在 /pakkujs/injected/do_inject.js line125 或者 /pakkujs/injected/utils.js，看样子是没有把弹幕reload上？
 另外CONSOLE下还打印出了 ‘pakku injector: root_elem not found’，不知道有没有关联

_Originally posted by @Meihina in https://github.com/xmcp/pakku.js/issues/162#issuecomment-772724787_

**Comment by xmcp** [comment]
`root_elem not found` 是正常的。上面那句log “got tampered response for ...” 应该表示加载正常才对。我本地测试也没有问题。

看看扩展程序的console里面有没有报错？
![image](https://user-images.githubusercontent.com/6646473/106846337-a5331900-66e7-11eb-9340-9032b91d85b6.png)

然后重启浏览器多试几次，如果bug能稳定复现的话可以把URL发给我看看。

**Comment by xmcp** [comment]
另外试试禁用掉其他 user script 和扩展程序，看看是不是有冲突。

**Comment by Meihina** [comment]
emmm....   
开启脚本下**会多出一个** “ got tampered response for https://api.bilibili.com/x/v2/dm/web/history/seg.so?type=1&oid=75963025&date=1970-01-03 ” ，这个拿到的内容是空的，估计是这个原因？
复现十分稳定，所有视频都是一样的情况，devtools里也没有报错，并且没有其他油猴脚本或扩展程序干扰。

**Comment by Meihina** [comment]
> emmm....
> 开启脚本下**会多出一个** “ got tampered response for https://api.bilibili.com/x/v2/dm/web/history/seg.so?type=1&oid=75963025&date=1970-01-03 ” ，这个拿到的内容是空的，估计是这个原因？
> 复现十分稳定，所有视频都是一样的情况，devtools里也没有报错，并且没有其他油猴脚本或扩展程序干扰。

附图

![R%J4 )}O6}V{ }E{T_Y59P1](https://user-images.githubusercontent.com/50244072/106874806-f73c6480-6710-11eb-917e-d5acd40fdfc7.png)

**Comment by xmcp** [comment]
不知道是什么情况。关掉user script只开pakku能正常加载弹幕吗？

**Comment by Meihina** [comment]
> 不知道是什么情况。关掉user script只开pakku能正常加载弹幕吗？

是的可以，或者在脚本里注释掉 ‘pakku_set_danmaku_bounce’ 那段也可以正常跑，只是没有自定义过滤。
![_WWJZ}L6}4$N5M`JZ UY$02](https://user-images.githubusercontent.com/50244072/106878958-86e41200-6715-11eb-8c5e-cf753ab04d0c.png)

**Comment by xmcp** [comment]
这句的作用就是触发pakku重新加载弹幕。
我这里用起来没有问题，复现不了这个bug，不知道咱俩环境有什么区别。

**Comment by Meihina** [comment]
好怪哦 我是chorme最新版，油猴4.11
找个时间上firefox上试试吧，现在先这么用了
