### ISSUE TITLE
请问这个对弹幕数量是不是也是有限制的

### ISSUE THREAD

**Issue by rendingdong** [xmcp/pakku.js#165]
某个视频有一万多条弹幕，点击后生成的文件里面只有前面的一部分，再看插件，上面显示的总弹幕数也变成了8000，我尝试过3种不同的工具，都差不是一样的效果，看到B站里某条评论，好像确实限制为7999，这个有办法解决吗。

**Comment by xmcp** [comment]
你是说点击popup窗口 “过滤后xxx条” 链接得到的弹幕数量比播放器显示的要少？
这是因为B站有两个版本的API，旧的XML格式的API和新的protobuf格式的API。播放器现在用的是后者，点击 “过滤后xx条” 默认请求的是前者。前者的弹幕数量限制通常更低。

要与播放器保持一致，一个暂时的workaround是修改 “过滤后xx条” 页面的URL。

原来的URL长这样：
`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/parse_url.html?ret_type=xml&url=http%3A%2F%2Fcomment.bilibili.com%2F【CID号】.xml`

改成这样：
`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/parse_url.html?ret_type=xml&url=https%3A%2F%2Fapi.bilibili.com%2Fx%2Fv2%2Fdm%2Fweb%2Fseg.so%3Ftype%3D1%26oid%3D【CID号】%26pid%3D【AV号】%26segment_index%3D1`
