### ISSUE TITLE
无法检测到课程页面的播放器

### ISSUE THREAD

**Issue by CKylinMC** [xmcp/pakku.js#166]
课程页面的播放器与平时的播放器不是同一个，所以完全不能被识别。

另见我在另一个问题里的回复：
https://github.com/the1812/Bilibili-Evolved/issues/1560#issuecomment-780319714

**Comment by xmcp** [comment]
![image](https://user-images.githubusercontent.com/6646473/108193801-cf0d2680-7150-11eb-8332-a204132f3361.png)
我这里没有遇到相关问题。如果确实识别不到播放器，请提供可以复现的链接。

**Comment by CKylinMC** [comment]
![image](https://user-images.githubusercontent.com/11648014/108308482-c5d09800-71ea-11eb-948f-69bdabd17f57.png)
[高定军:高中物理必修二 (人教版)](https://www.bilibili.com/cheese/play/ep2259)
这是搜索课程关键字后的第一个推荐。
截图时是无痕模式，为了排除其他插件冲突的可能性，只开了pakku和switchomega(这个是以前开的)。

<details>
<summary>Console部分截图</summary>

![普通模式](https://user-images.githubusercontent.com/11648014/108308754-41324980-71eb-11eb-9669-055259c611e6.png)

![无痕模式](https://user-images.githubusercontent.com/11648014/108308845-6de66100-71eb-11eb-9ad5-515e9c24bfd3.png)

</details>

插件页面显示：
`v10.0.5_C by @xmcp  ✓ 是最新版本`
所以应该不是版本过低的问题。

~也有可能是b站又在灰度什么~所以实在无法复现的话就没办法了。课程区域弹幕还是比较克制的，不会很影响使用。

**Comment by xmcp** [comment]
看log像是B站换了加载弹幕的方式。我这几天关注一下，能复现了就修。

**Comment by CKylinMC** [comment]
> 看log像是B站换了加载弹幕的方式。我这几天关注一下，能复现了就修。

主站的播放器没事，b站可能是对课程区有新的想法。
(b站的灰度到底是什么鬼机制...)
