### ISSUE TITLE
开启"弹幕信息显示框"后,输入弹幕时无法使用ctrl键

### ISSUE THREAD

**Issue by 0xbba** [xmcp/pakku.js#170]
打开`弹幕信息显示框`功能后,输入弹幕时无法使用复制粘贴等功能.按下Ctrl会高亮弹幕,隐藏弹幕输入框
关闭该功能以后正常
尝试过关闭其余所有插件,还是这样

**Comment by xmcp** [comment]
因为设定是按住ctrl点击弹幕可以查看详情，所以按下ctrl时会隐藏视频上下的遮罩方便选择，此时输入框也被隐藏了。
后续版本会判断键盘焦点是否在输入框，在输入弹幕时不激活该功能。
目前你可以退出全屏模式再复制粘贴内容。

**Comment by xmcp** [comment]
v10.0.6版本已修复此问题。
Firefox平台已经更新，Chrome和Edg平台因为有人工审核大概将于一周内完成更新。
