### ISSUE TITLE
弹幕密度分析图显示异常

### ISSUE THREAD

**Issue by myillustrious** [xmcp/pakku.js#171]
在长时间的视频（我个人试下来，时长超过一个小时的视频）时，只加载了开头一小段的弹幕的密度图，并且覆盖了整个进度条
油猴脚本和别的b站相关插件都关闭了，版本也是最新的，但是还是有这个问题，日志如下

**Comment by xmcp** [comment]
bug可以复现，是脚本解析视频时间的逻辑有错误，导致当时长超过1小时的时候把HH:MM:SS当MM:SS去解析了。
有空就修。

**Comment by myillustrious** [comment]
好滴，谢谢大佬

**Comment by xmcp** [comment]
v10.0.6版本已修复此问题。
Firefox平台已经更新，Chrome和Edg平台因为有人工审核大概将于一周内完成更新。
