### ISSUE TITLE
弹幕显示异常

### ISSUE THREAD

**Issue by wjwisaking** [xmcp/pakku.js#172]
弹幕左侧移动后，最后会全都挤在左侧边缘，
![QQ截图20210424152619](https://user-images.githubusercontent.com/83112191/115951233-2a251600-a512-11eb-9db6-191cf8ed1ec9.jpg)
通常是留一点尾巴[x2][x3]这样的
不会消失，一直存在

**Comment by xmcp** [comment]
无法复现此问题。
pakku只修改了B站API返回的弹幕信息，不影响播放器显示弹幕的过程。
建议检查浏览器版本、B站播放器设置或者其他插件，可以向B站反馈播放器bug。
