### ISSUE TITLE
按住ctrl点击弹幕后,显示个人信息加载失败.

### ISSUE THREAD

**Issue by lolisix** [xmcp/pakku.js#175]
命令台
<a href="https://sm.ms/image/GcP6qMhFi798Vrw" target="_blank"><img src="https://i.loli.net/2021/04/29/GcP6qMhFi798Vrw.png" ></a>

**Comment by xmcp** [comment]
无法复现，可能是B站API请求频率过快，被临时限制了，或者B站又在灰度什么东西。

显示个人信息并非pakku的重要功能，先close了。
如果你知道问题具体在哪里可以交PR，如果我可以复现了将重新open。
