### ISSUE TITLE
弹幕密度分析图疑似在看电影时失效

### ISSUE THREAD

**Issue by gaotongsh** [xmcp/pakku.js#176]
弹幕密度分析图疑似在看电影时失效。如在观看[《指环王1》](https://www.bilibili.com/bangumi/play/ep317022)时，密度图表现如下：
![截屏2021-05-02 14 34 48](https://user-images.githubusercontent.com/12027397/116804756-fbcbba00-ab53-11eb-8149-4d1e81104e2c.png)

可以看到，作为一部四小时的电影，这个密度图很平缓。当鼠标指向1:20:00左右时，看到热门弹幕为“力量之戒”，这一看就应该是魔戒第一次出场时的弹幕，而不会在1:20:00才出现。猜测这个情况是因为不知为何插件只截取了电影最开始时的弹幕，再将生成的密度图拉伸到整个坐标轴上。

看其他电影时也有类似情况。

调试信息：
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.0.5

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36 Edg/90.0.818.51`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"suffix","CLOUD_SYNC":"off","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1619937268227","FLASH_NOTIF":"on","_ADVANCED_USER":"off","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","REMOVE_SEEK":"off","POPUP_BADGE":"percent","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","WHITELIST":"[]","PROC_TYPE7":"off","THRESHOLD":"20","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"off","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"off","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html#show-advanced`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"371":{"identical":157,"edit_distance":532,"pinyin_distance":7,"cosine_distance":79,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":36,"shrink":"","scroll":4,"taolu":0,"total":6005,"onscreen":5230,"maxcombo":33,"maxdispval":211.56020001909252,"error":null,"cid":"330430839","parse_time_ms":455},"1078":{"identical":18,"edit_distance":26,"pinyin_distance":4,"cosine_distance":7,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":1,"shrink":"","scroll":0,"taolu":3,"total":871,"onscreen":816,"maxcombo":7,"maxdispval":36.605826354690095,"error":null,"cid":"323519202","parse_time_ms":30},"1090":{"identical":557,"edit_distance":899,"pinyin_distance":21,"cosine_distance":192,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":46,"shrink":"","scroll":8,"taolu":32,"total":16000,"onscreen":14331,"maxcombo":59,"maxdispval":157.2547844951604,"error":null,"cid":"173541443","parse_time_ms":346}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"off","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"off","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"off","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"off","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1619937268227"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=750 status=complete `undefined`

- ID=844 status=complete `undefined`

- ID=982 status=complete `undefined`

- ID=994 status=complete `undefined`

- ID=1090 status=complete `https://www.bilibili.com/bangumi/play/ep317022?theme=movie&from_spmid=666.7`

- ID=1101 status=complete `undefined`

- ID=1109 status=loading `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by gaotongsh** [comment]
抱歉开了之后才意识到#171已有人提出这个问题。关闭。

**Comment by xmcp** [comment]
是的，10.0.6已修复此问题。Edge商店仍在审核，大概几天后会更新。
