### ISSUE TITLE
我一直是用旧版播放页的，最近一段时间pakku突然失效了

### ISSUE THREAD

**Issue by ciriue** [xmcp/pakku.js#180]
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.0.8

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"_ADVANCED_USER":"off","DANMU_MARK":"prefix","BLACKLIST":"[]","_LAST_UPDATE_TIME":"0","MARK_THRESHOLD":"1","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","REMOVE_SEEK":"off","THRESHOLD":"20","POPUP_BADGE":"percent","WHITELIST":"[]","TRIM_WIDTH":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"off","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","REPRESENTATIVE_PERCENT":"0","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","FLUCTLIGHT":"off","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"111":{"identical":56,"edit_distance":51,"pinyin_distance":4,"cosine_distance":6,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":6,"shrink":"","scroll":0,"taolu":1,"total":386,"onscreen":269,"maxcombo":13,"maxdispval":98.31630324669385,"error":null,"cid":"335037893","parse_time_ms":48}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"0"}

**Tabs:**

- ID=19 status=complete `https://www.bilibili.com/`

- ID=111 status=complete `https://www.bilibili.com/video/av930494813`

- ID=20 status=complete `https://space.bilibili.com/27534330`

- ID=21 status=complete `https://space.bilibili.com/165918/video`

- ID=22 status=complete `https://www.bilibili.com/anime/index/#season_version=-1&area=-1&is_finish=-1&copyright=-1&season_status=-1&season_month=7&year=%5B2016%2C2017)&style_id=-1&order=3&st=1&sort=0&page=1`

- ID=104 status=complete `undefined`

- ID=107 status=complete `undefined`

- ID=119 status=loading `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by xmcp** [comment]
v10.0.7 为了修复最新播放器的严重兼容问题（#179），去除了对旧版播放器的兼容措施，因为B站已经不再使用旧版播放器很长时间了。

如果你是使用的用户脚本之类的方式手动切换到的旧版播放器，请在脚本里增加以下代码：

```javascript
window.Worker = null;
```

**Comment by ciriue** [comment]
非常感谢

**Comment by yelan6166** [comment]
这行代码要放到脚本里的哪行？

**Comment by xmcp** [comment]
尽量早执行就行，最好在 `document-start`

**Comment by yelan6166** [comment]
> 尽量早就行，最好在 `document-start`

在 document-start 里填了，效果变成先进入新版页面再跳转旧版播放器。是我搞错了吗？
