### ISSUE TITLE
【功能请求】弹幕过密减小字号不对底部弹幕生效

### ISSUE THREAD

**Issue by WhiverFichos** [xmcp/pakku.js#181]
RT
还有，底部弹幕的数量标记希望单独设置显示（或数量阈值）。
感谢作者。

**Comment by xmcp** [comment]
可以升级到 [v2024.3.1](https://github.com/xmcp/pakku.js/releases/tag/2024.3.1) 后通过 [用户脚本](https://github.com/xmcp/pakku.js/blob/master/userscript_docs/README.md) 实现此功能
