### ISSUE TITLE
点击空降弹幕 无法跳转

### ISSUE THREAD

**Issue by ImLEEROY** [xmcp/pakku.js#183]

**Comment by xmcp** [comment]
请提供复现方式

**Comment by ImLEEROY** [comment]
点击空降弹幕 并无跳转
![image](https://user-images.githubusercontent.com/66423087/122219557-22ff0080-cee2-11eb-9614-6371b5c80d9f.png)

**Comment by xmcp** [comment]
嗯，你说得对

**Comment by wadecoding** [comment]
你好，我在使用[Bilibili Evolved](https://github.com/the1812/Bilibili-Evolved)这个插件，这个插件可以在Web端实现Android端的空降功能，但是搭配这个扩展之后点击空降字幕和上图的情况一样，能不能针对这个问题改动一下

**Comment by xmcp** [comment]
试试在设置里面把“弹幕信息显示框”关掉

**Comment by Sciroccogti** [comment]
是否有可能可以限制 弹幕信息 仅在 弹幕列表 中显示？

**Comment by xmcp** [comment]
有可能，下个版本再说

**Comment by xmcp** [comment]
v10.1增加了相关设置，取消勾选“点击展开弹幕信息”即可关闭ctrl+点击快捷键
