### ISSUE TITLE
可以把选项界面的正则表达式做成inplace editing吗？

### ISSUE THREAD

**Issue by chenlianMT** [xmcp/pakku.js#19]
感谢作者！插件超级好用！：）

在测试修改弹幕套路的正则表达式时，现在的流程需要复制粘贴套路 -> 添加新套路 -> 删除旧套路。可不可以增加一个编辑套路的功能，把修改表达式变成inplace editing的形式呢？比如X-editable的这个demo（https://vitalets.github.io/x-editable/demo-bs3.html?c=inline ）。

**Comment by xmcp** [comment]
可以考虑。
其实现在这个形式主要是实现方便，毕竟弹幕套路（我）不会经常改（，而且我改要是想改就直接写到默认选项里了23333）。
不过既然有现成的控件，加上也无妨。

**Comment by xmcp** [comment]
等下 这货要jQuery呀……
我还是自己实现一个吧

**Comment by fanthos** [comment]
几行代码搞个能用的就行了（毕竟不是主要功能

**Comment by xmcp** [comment]
拿 contenteditable 随便搞了一个出来。
ps. 如果你同时改了多行内容，只有点“保存”按钮的那个能成功修改，其他的修改会回滚。这不是bug，是feature。
