### ISSUE TITLE
h5播放器3.0版本开插件在工作却不显示任何弹幕

### ISSUE THREAD

**Issue by ArtOriation** [xmcp/pakku.js#192]
**是否可以稳定复现：**

关闭插件刷新出现弹幕

**复现步骤：**

1. 启用插件，点开h5播放器3.0的视频（基本上都是番剧）旧的没问题
2. 

**预期行为：**

弹幕不显示

**实际行为：**

![QQ截图20210729125747](https://user-images.githubusercontent.com/36293591/127434680-65553a3f-efcf-4df9-9f02-95267aebc185.png)

**系统环境：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.1.1

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537.36 Core/1.70.3872.400 QQBrowser/10.8.4455.400`

**Incognito:** `false`

**localStorage:** `{"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"0"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"1964730982":{"identical":382,"edit_distance":150,"pinyin_distance":6,"cosine_distance":15,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":14,"shrink":"","scroll":0,"taolu":3,"total":1430,"onscreen":877,"maxcombo":162,"maxdispval":58.530495370527994,"error":null,"cid":"377672316","parse_time_ms":93}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"0"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=1964730449 status=complete `undefined`

- ID=1964730511 status=complete `undefined`

- ID=1964730450 status=complete `https://www.bilibili.com/`

- ID=1964730982 status=complete `https://www.bilibili.com/bangumi/play/ep413514`

- ID=1964731032 status=complete `undefined`

- ID=1964731033 status=loading `undefined`

- ID=1964731017 status=complete `undefined`

- ID=1964731018 status=complete `undefined`

- ID=1964730607 status=complete `https://www.bilibili.com/bangumi/play/ep408844`

- ID=1964730986 status=complete `https://member.bilibili.com/platform/home`

- ID=1964730452 status=complete `undefined`

- ID=1964730905 status=complete `undefined`

- ID=1964730962 status=complete `undefined`

- ID=1964730981 status=complete `undefined`

- ID=1964731008 status=complete `undefined`

- ID=1964731013 status=complete `undefined`

- ID=1964731021 status=complete `undefined`

- ID=1964731024 status=complete `undefined`

- ID=1964731027 status=complete `undefined`

- ID=1964731029 status=complete `undefined`

- ID=1964731030 status=complete `undefined`

- ID=1964731031 status=complete `undefined`

- ID=1964730479 status=complete `https://live.bilibili.com/10112?broadcast_type=0`

- ID=1964730824 status=complete `undefined`

- ID=1964730849 status=complete `undefined`

- ID=1964730847 status=complete `undefined`

- ID=1964730835 status=complete `undefined`

- ID=1964730830 status=complete `undefined`

- ID=1964730846 status=complete `undefined`

- ID=1964730834 status=complete `undefined`

- ID=1964730833 status=complete `undefined`

- ID=1964730828 status=complete `undefined`

- ID=1964730861 status=complete `undefined`

- ID=1964730829 status=complete `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,10">好强啊</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,10">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,10">   FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,10"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,10"> FFT大法好（13行FFT路过）</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,7">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,4">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,0">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,0">你们都好强啊~~~ orz orz orz orz</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,10">好强啊</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,10">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,10">   FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,10"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,10"> FFT大法好（13行FFT路过）</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,7">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,4">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,0">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,0">你们都好强啊~~~ orz orz orz orz</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

浏览器版本过低？以前没这问题

**Comment by ArtOriation** [comment]
![QQ截图20210729130542](https://user-images.githubusercontent.com/36293591/127434845-b0e86ba4-f1cd-417c-8f25-edfb3abd6307.png)

**Comment by ArtOriation** [comment]
开浏览器无痕隐身启用插件是正常的

**Comment by xmcp** [comment]
如果隐身模式下是正常的，是不是跟其他插件（或者浏览器自带的什么功能）冲突啊？

**Comment by ArtOriation** [comment]
![QQ截图20210802112456](https://user-images.githubusercontent.com/36293591/127800895-7e84fe43-1dce-496a-80c8-19b994e03964.png)
![QQ截图20210802112440](https://user-images.githubusercontent.com/36293591/127800896-16fd19a3-804a-4be6-9672-230087c9fc4b.png)
收集错误如图所示

**Comment by ArtOriation** [comment]
> 如果隐身模式下是正常的，是不是跟其他插件（或者浏览器自带的什么功能）冲突啊？

感谢，一个个插件试过去了，是个旧插件冲突了，更新好像就好了。抱歉
