### ISSUE TITLE
根据弹幕数量动态切换配置（乃至禁用）

### ISSUE THREAD

**Issue by liangjiancang** [xmcp/pakku.js#194]
最基本的就是如题目所言。再扩大化一下：
1. 引入配置预设功能，可通过点击扩展图标等方式手动切换。
2. 引入自动切换功能，可配置各种切换规则（如弹幕数量、UP 主UID 等），根据规则切换预设。

总之就是类似 SwitchyOmega 那样的情景模式自动切换。

**Comment by xmcp** [comment]
可以升级到 [v2024.3.1](https://github.com/xmcp/pakku.js/releases/tag/2024.3.1) 后通过 [用户脚本](https://github.com/xmcp/pakku.js/blob/master/userscript_docs/README.md) 实现此功能
