### ISSUE TITLE
是否可以显示已被合并弹幕的被点赞数量？

### ISSUE THREAD

**Issue by HaloWang** [xmcp/pakku.js#195]
如图所示，下图为关闭 pakku 后，B 站可显示该该弹幕被点赞的数量
![Screenshot 2021-08-31 135638](https://user-images.githubusercontent.com/7344724/131450058-c3d5f6be-e183-43e1-bef1-5de1b8c2173f.png)
开启 pakku 后，我只能看到该弹幕被点赞数量为 1

**Comment by xmcp** [comment]
合并后点赞数量等元信息会采用被所有合并的弹幕中的其中一个

**Comment by HaloWang** [comment]
我个人期望还是能显示点赞总量的加和，这样信息传达的可能会更准确些。因为我认为，某种程度上来说，我给这个弹幕点赞也可以理解为我发送了和这个弹幕相同的内容，而相同的内容会被 pakku 统计到角标中的数量中去的。~🤣你就一写代码的，懂什么pakku.js.jpg~🤗当然我完全尊重你的想法。
