### ISSUE TITLE
今天看直播发现插件不能用

### ISSUE THREAD

**Issue by HDDDHHDDDD** [xmcp/pakku.js#196]
B站普通视频能用，看B站的一些直播插件显示本页面没有发现B站播放器

**Comment by xmcp** [comment]
你说得对

**Comment by xmcp** [comment]
参见 [FAQ](https://s.xmcp.ltd/pakkujs/)：
> 支持过滤直播间弹幕吗？ → 不支持。

**Comment by HDDDHHDDDD** [comment]
请问以后会升级支持吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月16日(周四) 晚上6:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xmcp/pakku.js] 今天看直播发现插件不能用 (#196)




 
参见 FAQ：
  
支持过滤直播间弹幕吗？ → 不支持。
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
