### ISSUE TITLE
弹幕信息与跳转功能冲突

### ISSUE THREAD

**Issue by lifeleewhisper** [xmcp/pakku.js#198]
开启弹幕信息显示框后，不能实现 点击跳转弹幕 至指定时间点，建议使用特定按键实现弹幕信息显示框的功能

**Comment by xmcp** [comment]
在设置中关闭 “点击展开弹幕信息” 选项可以避免 ctrl+点击 快捷键与其他插件冲突。

此时如果还想查看弹幕信息，可以
1. 右键点击弹幕，展开菜单
2. 点击弹幕文字（将在弹幕列表中定位到该项）
3. 再弹幕列表里再次点击弹幕
