### ISSUE TITLE
要不把一些相似度特高的弹幕也合并？

### ISSUE THREAD

**Issue by LawrencePeng** [xmcp/pakku.js#2]
算Edit Distance

**Comment by xmcp** [comment]
我曾经考虑过这个问题，不过有一个硬伤。举例来说，现在有如下弹幕：
- “LL大法好”
- ”LL大法好！“
- “LL大法号”
- “ll大法”

那么，它们应该被合并成“LL大法好 [x4]”呢，还是“LL大法好！[x4]”呢，还是“LL大法号 [x4]”呢，还是“ll大法 [x4]”呢？

**Comment by celeron533** [comment]
选最长的？
选出现频率最高的？

如果长度和出现频率都不相上下，选第一个出现的，哈哈

**Comment by dramforever** [comment]
按 @celeron533 说的，然后加个选项

**Comment by xmcp** [comment]
@dramforever 话说这个怎么实现呀？要是把15秒之内的弹幕都扫一遍判编辑距离，岂不是就`O(n)`变`O(n^2)`了？

**Comment by LawrencePeng** [comment]
试试BK树？https://zhuanlan.zhihu.com/p/20101194

**Comment by LawrencePeng** [comment]
字幕大部分都不长，编辑距离计算时间不会很大。
加上BK数排除掉一些无关结点，最后花销应该不会很大。

**Comment by xmcp** [comment]
BK树好像没法删除节点啊，只能给节点加删除标记？不过应该还不至于退化到一万（以内）个弹幕都跑不过。
可以有空的时候尝试实现一下。

**Comment by LawrencePeng** [comment]
恩恩，Optional。

**Comment by dramforever** [comment]
走过路过不要错过啦，懂怎么加载解包扩展的（其实 unpacked 应该是“未打包的”）来 #5 试一下喽。

**Comment by xmcp** [comment]
+1

在merge #5 之前急需测试人员
