### ISSUE TITLE
能支持其他播放平台吗？

### ISSUE THREAD

**Issue by yyxgiub** [xmcp/pakku.js#200]
如标题，希望在其他平台也能用。习惯pakku后，其他平台的弹幕不忍直视……

**Comment by xmcp** [comment]
pakku的主要工作量在于hook B站播放器的弹幕逻辑、处理弹幕的各种属性，以及其他播放器增强功能。真正处理弹幕的代码只占总代码量的大概10%到20%。
因此在其他平台实现类似功能基本相当于从头重写一遍。如果你有兴趣可以自己做这种事（
