### ISSUE TITLE
希望可以根据弹幕字符串长度屏蔽弹幕

### ISSUE THREAD

**Issue by salvatore-w** [xmcp/pakku.js#201]
有些弹幕写得特别长，有时候一整行长长的文字滚过，既不想看也看不过来（有长篇大论抒发为什么不去评论区……），希望可以增加按照弹幕字符串长度过滤弹幕。
谢谢！

**Comment by xmcp** [comment]
弹幕屏蔽可以直接通过播放器的屏蔽规则实现
参考规则：[`^.{50,}$`](https://regexper.com/#%5E.%7B50%2C%7D%24)
