### ISSUE TITLE
增加弹幕空降功能/兼容Bilibili Evolved的空降功能

### ISSUE THREAD

**Issue by Silverteal** [xmcp/pakku.js#202]
根据目前的测试，无论是否开启 弹幕信息显示框 功能，Bilibili Evolved的弹幕空降功能都是能正常显示下划线，但是单击跳转不可用的状态。希望能够原生支持空降或者尝试兼容Bilibili Evolved的空降功能。

**Comment by 424778940z** [comment]
同样问题 折腾了半天设置 貌似不行
根据b站意思 如果多个空降弹幕 仅显示三个 估计这几个被跟别的合并一起去了 导致空降失败
建议直接插件自己处理空降然后跳转播放器进度

**Comment by gongfuture** [comment]
同样问题+1，请求兼容或支持
