### ISSUE TITLE
希望能新增例外设置

### ISSUE THREAD

**Issue by ChurchEChan** [xmcp/pakku.js#203]
**高赞弹幕**
[“一、假装接电话”](https://www.bilibili.com/video/BV1qW411X7js?p=2&t=20.7)
过滤前高赞弹幕前面会有一个大拇指的图标，过滤后则没有

**特殊弹幕**（因为没找到对应的更新文档，我也不知道是不是叫这个）
[“前方高能”](https://www.bilibili.com/video/BV1XZ4y1S7H2?t=211.5)
过滤前的弹幕是特殊外观的、EVA 风格的弹幕，过滤后的则会变成[前方高能]，类似的还有[OHHHH]

**Comment by xmcp** [comment]
可以升级到 [v2024.3.1](https://github.com/xmcp/pakku.js/releases/tag/2024.3.1) 后通过 [用户脚本](https://github.com/xmcp/pakku.js/blob/master/userscript_docs/README.md) 实现此功能
