### ISSUE TITLE
出现多重弹幕

### ISSUE THREAD

**Issue by lvess** [xmcp/pakku.js#205]
**是否可以稳定复现：是

**复现步骤：打开番剧过几秒右侧弹幕列表就是加载一次，就打开番剧加载一次，过几秒又加载一次

**实际行为：出现双重弹幕
![微信图片_20220217173101](https://user-images.githubusercontent.com/54264702/154447069-dccd8ff7-24cc-4ee2-a215-cc575c7c8d76.png)

**系统环境：**
<!-<summary>[调试信息]</summary>

**版本：** 10.1.1

**频道：** 铬

**用户代理：** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36`

**隐身：** `false`

**localStorage:** `{"_ADVANCED_USER":"off","D
ANMU_MARK":"prefix","CLOUD_SYNC":"off","TOOLTIP_KEYBINDING":"on","BLACKLIST":"[]"," _LAST_UPDATE_TIME":"1645089442030","MARK_THRESHOLD":"1","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST" :"off","MAX_COSINE":"60","REMOVE_SEEK":"off","THRESHOLD":"20","POPUP_BADGE":"percent","TRIM_WIDTH":"on","FORCELIST":" [[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\" ^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$ \",\"yoo...\"]]","WHITELIST":"[]","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD ":"0","BREAK_UPDATE":"off","REPRESENTATIVE_PERCENT":"0","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE": "on","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","FLUCTLIGHT":"on","SCROLL_THRESHOLD":"1200"}`^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","WHITELIST":"[]","PROC_TYPE7":"on","PROC_POOL1" :"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","REPRESENTATIVE_PERCENT":"0","DANMU_SUBSCRIPT":"on","PROC_TYPE4":" on","TRIM_PINYIN":"on","ENLARGE":"on","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","FLUCTLIGHT":"on" "SCROLL_THRESHOLD":"1200"}`^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","WHITELIST":"[]","PROC_TYPE7":"on","PROC_POOL1" :"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","REPRESENTATIVE_PERCENT":"0","DANMU_SUBSCRIPT":"on","PROC_TYPE4":" on","TRIM_PINYIN":"on","ENLARGE":"on","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","FLUCTLIGHT":"on" "SCROLL_THRESHOLD":"1200"}`"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","REPRESENTATIVE_PERCENT":"0","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on ","TRIM_PINYIN":"on","ENLARGE":"on","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","FLUCTLIGHT":"on", “SCROLL_THRESHOLD”：“1200”}`"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","REPRESENTATIVE_PERCENT":"0","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on ","TRIM_PINYIN":"on","ENLARGE":"on","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","FLUCTLIGHT":"on", “SCROLL_THRESHOLD”：“1200”}`ENLARGE":"on","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","FLUCTLIGHT":"on","SCROLL_THRESHOLD":"1200"}`ENLARGE":"on","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","FLUCTLIGHT":"on","SCROLL_THRESHOLD":"1200"}`

**观看次数：**

-`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

-`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

-`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**背景/IS_FIREFOX：** 假

**背景/GLOBAL_SWITCH：**真

**背景/历史：** `{"80":{"identical":746,"edit_distance":2050,"pinyin_distance":47,"cosine_distance":73,"player_seek":"","blacklist": "","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":134,"shrink":"","scroll":0,"taolu ":35,"total":10300,"onscreen":7384,"maxcombo":37,"maxdispval":187.8253541188871,"error":null,"cid":"102476481","parse_time_ms":451}}`

**权限：** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]} `

**标签：**

- ID=2 状态=完成`https://www.bilibili.com/`

- ID=80 status=complete `https://www.bilibili.com/bangumi/play/ep234407?from=search&seid=3100455419715868214&spm_id_from=333.337.0.0`

- ID=110 状态=完成 `未定义`

- ID=113 状态=正在加载“未定义”

- ID=95 状态=完成 `未定义`

**存储/同步：** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off", "CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^ 23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+ $\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s ~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5" ,"MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT ":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING": "on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":" 1645089442030"}百分比","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200" ,"SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on"," TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1645089442030"}百分比","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200" ,"SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on"," TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1645089442030"}off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on" ,"TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off", "_LAST_UPDATE_TIME":"1645089442030"}off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on" ,"TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off", "_LAST_UPDATE_TIME":"1645089442030"}TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1645089442030"}TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1645089442030"}

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid >12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>kv</source><dp=" 0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,11">]]][[[</d><dp="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090, ">]][[</d><dp="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><dp="14.63900,1,25,16777215 ,1482851465,0,f571e8a8,2788066725,11">神™·MIDI</d><dp="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,1">测试！@#$​​%^&*()_+-={}[];':",./<>?</d><dp="65.91800,1,25,16777215,1482851467,0, f571e8a8,2788072713,1">你们都好强啊~~~ orz orz orz orz</d><dp="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">FFT大法好（13行FFT路过）</d><dp="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,1">陶笛的好声音</d><dp="20.53300,1,25, 16777215,1482851465,0,f571e8a8,2788068017,1">FFT大法好（13行FFT路过）</d></i>`f571e8a8,2788070737,1">陶笛的好声音指标</d><dp="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1">FFT大法好（13行FFT路过）</d> d></i>`f571e8a8,2788070737,1">陶笛的好声音指标</d><dp="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1">FFT大法好（13行FFT路过）</d> d></i>`

**请求/普通 XML：** 加载，状态=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid> 12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>kv</source><dp="0.00000 ,1,25,16777215,1524407554,0,91d6b7d0,4480703586,11">]]][[[</d><dp="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,11" >]][[</d><dp="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><dp="14.63900,1,25,16777215, 1482851465,0,f571e8a8,2788066725,11">神™·MIDI</d><dp="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,1">测试！@#$​​%^&*()_+-={}[];':",./<>?</d><dp="65.91800,1,25,16777215,1482851467,0, f571e8a8,2788072713,1">你们都好强啊~~~ orz orz orz orz</d><dp="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">FFT大法好（13行FFT路过）</d><dp="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,1">陶笛的好声音</d><dp="20.53300,1,25, 16777215,1482851465,0,f571e8a8,2788068017,1">FFT大法好（13行FFT路过）</d></i>`f571e8a8,2788070737,1">陶笛的好声音指标</d><dp="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1">FFT大法好（13行FFT路过）</d> d></i>`f571e8a8,2788070737,1">陶笛的好声音指标</d><dp="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1">FFT大法好（13行FFT路过）</d> d></i>`

**！异常：** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</详情>
 -->
![微信图片_20220217173539](https://user-images.githubusercontent.com/54264702/154447554-d0a53662-e070-4421-bd22-8be84a30d030.png)
上图为点击分p后的弹幕
大佬，用pakku看番剧会出现双重弹幕，其他视频就不会，还有就是如果在一个视频里点相关推荐的视频的话也会出现多重弹幕，分p也会，只能f5刷新才会变回正常

**Comment by xmcp** [comment]
unable to reproduce, probably fixed after #206 is fixed
