### ISSUE TITLE
在新版播放器 3.6.7时 插件检测不到b站播放器

### ISSUE THREAD

**Issue by Aragamiz** [xmcp/pakku.js#206]
b站播放器版本
3.6.7 播放策略默认

插件错误信息
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.1.1

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"prefix","TOOLTIP_KEYBINDING":"on","TAOLUS":"","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1590390228724","FLASH_NOTIF":"on","_ADVANCED_USER":"on","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","REMOVE_SEEK":"off","POPUP_BADGE":"percent","WHITELIST":"[]","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"off","PROC_TYPE7":"on","THRESHOLD":"20","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"off","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"59":{"identical":2,"edit_distance":1,"pinyin_distance":1,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":1,"total":35,"onscreen":31,"maxcombo":3,"maxdispval":14.25943507011223,"error":null,"cid":"553176415","parse_time_ms":0},"307":{"identical":0,"edit_distance":3,"pinyin_distance":0,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":1,"total":57,"onscreen":54,"maxcombo":3,"maxdispval":15.102379125862104,"error":null,"cid":"550842478","parse_time_ms":1},"409":{"identical":17,"edit_distance":37,"pinyin_distance":2,"cosine_distance":11,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":6,"shrink":"","scroll":0,"taolu":3,"total":122,"onscreen":55,"maxcombo":12,"maxdispval":21.614285496676224,"error":null,"cid":"426436763","parse_time_ms":2},"430":{"identical":9,"edit_distance":2,"pinyin_distance":0,"cosine_distance":2,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":0,"total":49,"onscreen":36,"maxcombo":4,"maxdispval":8.938280050948535,"error":null,"cid":"502016886","parse_time_ms":1},"465":{"identical":12,"edit_distance":38,"pinyin_distance":4,"cosine_distance":12,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":1,"script":0,"enlarge":5,"shrink":"","scroll":0,"taolu":3,"total":259,"onscreen":193,"maxcombo":10,"maxdispval":79.76045058597214,"error":null,"cid":"552892680","parse_time_ms":7},"468":{"identical":0,"edit_distance":0,"pinyin_distance":0,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":0,"total":13,"onscreen":13,"maxcombo":1,"maxdispval":10.673377997758292,"error":null,"cid":"542372025","parse_time_ms":0},"471":{"identical":279,"edit_distance":204,"pinyin_distance":36,"cosine_distance":22,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":28,"shrink":"","scroll":0,"taolu":6,"total":1996,"onscreen":1455,"maxcombo":21,"maxdispval":55.465259717927296,"error":null,"cid":"517403953","parse_time_ms":23},"474":{"identical":2,"edit_distance":1,"pinyin_distance":1,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":1,"total":35,"onscreen":31,"maxcombo":3,"maxdispval":14.25943507011223,"error":null,"cid":"553176415","parse_time_ms":0}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"off","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1590390228724"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=44 status=complete `undefined`

- ID=45 status=complete `undefined`

- ID=46 status=complete `undefined`

- ID=47 status=complete `undefined`

- ID=48 status=complete `undefined`

- ID=49 status=complete `undefined`

- ID=50 status=complete `undefined`

- ID=56 status=complete `undefined`

- ID=57 status=complete `undefined`

- ID=58 status=complete `undefined`

- ID=59 status=complete `https://www.bilibili.com/`

- ID=465 status=complete `https://www.bilibili.com/video/BV1ea411t7BV`

- ID=477 status=complete `https://space.bilibili.com/308459`

- ID=471 status=complete `https://www.bilibili.com/video/BV1VT4y1Q7eu`

- ID=474 status=complete `https://www.bilibili.com/video/BV1MS4y1g7Bg`

- ID=495 status=complete `https://space.bilibili.com/246274649/dynamic`

- ID=60 status=complete `https://t.bilibili.com/?tab=8`

- ID=459 status=complete `https://www.bilibili.com/video/BV1234y1t7E6`

- ID=462 status=complete `https://www.bilibili.com/video/BV1m34y1t7Ef`

- ID=382 status=complete `https://search.bilibili.com/all?keyword=%E5%BA%93%E5%BA%93`

- ID=485 status=complete `undefined`

- ID=502 status=loading `undefined`

- ID=492 status=complete `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,11">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,11">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,1">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,1">你们都好强啊~~~ orz orz orz orz</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,1">Ocarina的声音好奇怪</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,11">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,11">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,1">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,1">你们都好强啊~~~ orz orz orz orz</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,1">Ocarina的声音好奇怪</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by ziranjiang** [comment]
确实如此，而且有时候会出现只能加载前6分钟弹幕的问题

**Comment by chtholist** [comment]
+1，edge也一样，播到一半突然弹幕就没了，显示检测不到b站播放器

**Comment by drinkingmore** [comment]
+1，底部密度条失效，弹幕只能加载6min左右后全部消失。
在chrome/edge上都测试过了。

**Comment by Ano-yau** [comment]
补充，番剧可以正常加载全部弹幕

**Comment by olduck** [comment]
播放器版本3.7，问题存在

**Comment by xmcp** [comment]
v3.7.6可以复现（之前b站一直不灰度我，没法复现也没法修），我周末有空看看

**Comment by xmcp** [comment]
周末被更到了v3.7.8好像又没问题了，b站这个版本号左右横跳真是麻烦

**Comment by xmcp** [comment]
我现在又到3.7.14了，还是没问题……等我这里问题能复现了就修

**Comment by u2shana** [comment]
> 我现在又到3.7.14了，还是没问题……等我这里问题能复现了就修

我看了下,我也是3.7.14,还是有这个问题,其他b站相关脚本和插件都已经禁用了

**Comment by olduck** [comment]
这问题是概率出现的，如果是刷新后自动跳转到上次观看的进度这种会超高概率出现6分钟bug

**Comment by ziranjiang** [comment]
不能稳定复现确实挺麻烦的。

**Comment by xmcp** [comment]
v10.1.2应该已修复对新版播放器的兼容问题，目前firefox平台已经更新，chrome和edge平台将在审核通过后逐步灰度更新。

由于改动较大，可能会有一些小bug。

目前有一个已知bug：反复切换启用禁用后每个弹幕会重复出现很多次。这是由于B站播放器自身的bug（就算关闭pakku，在播放器里反复切换历史弹幕也会导致弹幕重复出现），暂时难以修复。
