### ISSUE TITLE
希望加入导入本地弹幕和其他视频弹幕的功能

### ISSUE THREAD

**Issue by C8H17OH** [xmcp/pakku.js#208]
前者可以用于给视频装填弹幕；后者可以用于导入相同内容的其他视频的弹幕，比如不同源的老番、内地版和港澳台版的新番（如无删减）。

似乎有点“与pakku本身功能关联不大、适用范围不广”，但pakku是我唯一能找到的拦截、注入(?)弹幕库的插件了，自己看代码也研究不明白，姑且发在这里，权当给开发者大佬们未来开发新功能提供可能的方向好了qwq

**Comment by RyoLee** [comment]
https://github.com/RyoLee/emby-danmaku/issues/12

最近在做emby的弹幕插件,刚想问问pakku有没有API可以调,看这个issue没有关闭所以答案应该是没用吧...

**Comment by Ethkuil** [comment]
或者「能在本地视频里使用pakku」应该也就可以了

**Comment by xmcp** [comment]
pakku有一个用于测试的处理本地弹幕的功能，把选项页面的options.html改成parse_local.html即可使用。

因为pakku 90%的代码都是在处理B站播放器的逻辑适配，且跟B站的弹幕格式比较耦合，而实际的算法部分很简单，做成API可能意义不大。不如自己实现一个。
