### ISSUE TITLE
无法加载弹幕列表和弹幕

### ISSUE THREAD

**Issue by yokinanya** [xmcp/pakku.js#209]
**是否可以稳定复现：**

是

**复现步骤：**

1. 打开任意视频

**预期行为：**

弹幕列表和弹幕正常加载

**实际行为：**

弹幕列表长期处于加载状态，无法正常加载弹幕，观察扩展程序弹出窗口可发现，实际上pakku可读取到弹幕
![image](https://user-images.githubusercontent.com/30362789/164126212-36fc765b-df4e-40af-a757-8e9fec1792f5.png)
![image](https://user-images.githubusercontent.com/30362789/164126363-a8346822-db81-4128-b98c-29c916851fd6.png)

**系统环境：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"suffix","TOOLTIP_KEYBINDING":"on","TAOLUS":"","FOOLBAR":"off","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1650416459559","FLASH_NOTIF":"on","_ADVANCED_USER":"on","SHRINK":"on","TRIM_SPACE":"on","MAX_DIST":"8","TRIM_ENDING":"on","AUTO_DANMU_LIST":"on","MAX_COSINE":"30","REMOVE_SEEK":"off","POPUP_BADGE":"count","WHITELIST":"[]","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"],[\"^.*bilibili- ( ゜- ゜)つロ 干杯~.*$\",\"bilibili- ( ゜- ゜)つロ 乾杯~\"],[\"^.*bilibili干杯.*$\",\"bilibili- ( ゜- ゜)つロ 乾杯~\"],[\"^.*哔哩哔哩干杯.*$\",\"bilibili- ( ゜- ゜)つロ 乾杯~\"]]","CLOUD_SYNC":"on","PROC_TYPE7":"off","THRESHOLD":"20","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","REPRESENTATIVE_PERCENT":"0","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"off","MODE_ELEVATION":"on","TOOLTIP":"off","AUTO_DISABLE_DANMU":"off","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"341":{"identical":0,"edit_distance":0,"pinyin_distance":0,"cosine_distance":0,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":1,"total":7,"onscreen":7,"maxcombo":1,"maxdispval":5.656854249492381,"error":null,"cid":"580332802","parse_time_ms":2}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"on","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"on","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"on","ENLARGE":"off","FLASH_NOTIF":"on","FLUCTLIGHT":"off","FOOLBAR":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"],[\"^.*bilibili- ( ゜- ゜)つロ 干杯~.*$\",\"bilibili- ( ゜- ゜)つロ 乾杯~\"],[\"^.*bilibili干杯.*$\",\"bilibili- ( ゜- ゜)つロ 乾杯~\"],[\"^.*哔哩哔哩干杯.*$\",\"bilibili- ( ゜- ゜)つロ 乾杯~\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"30","MAX_DIST":"8","MODE_ELEVATION":"on","POPUP_BADGE":"count","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"off","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"on","TAOLUS":"","THRESHOLD":"20","TOOLTIP":"off","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1650416459559"}

**Tabs:**

- ID=289 status=complete `undefined`

- ID=341 status=complete `https://www.bilibili.com/video/BV1ja411v7ZS`

- ID=385 status=complete `undefined`

- ID=407 status=complete `undefined`

- ID=411 status=loading `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,11">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,11">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,1">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,1">你们都好强啊~~~ orz orz orz orz</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,1">Ocarina的声音好奇怪</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,11">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,11">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,1">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,1">你们都好强啊~~~ orz orz orz orz</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,1">Ocarina的声音好奇怪</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

可能与哔哩哔哩更新视频播放器有关，播放器版本号：3.7.18-3077c72c

**Comment by xmcp** [comment]
请提供一下播放器版本号（视频上右键可得）和页面完整报错信息（按F12点console）

**Comment by yokinanya** [comment]
播放器版本号：3.7.18-3077c72c
控制台log：
[www.bilibili.com-1650431636461.log](https://github.com/xmcp/pakku.js/files/8518445/www.bilibili.com-1650431636461.log)

**Comment by xmcp** [comment]
建议检查下是否和其他插件/userscript冲突

**Comment by yokinanya** [comment]
确实是冲突了，和 [图片助手(ImageAssistant) 批量图片下载器](https://chrome.google.com/webstore/detail/imageassistant-batch-imag/dbjbempljhcmhlfpfacalomonjpalpko) 这个插件冲突了

**Comment by xmcp** [comment]
问题原因是pakku和这个插件都hook了XMLHttpRequest导致不兼容，几天内将发布v10.2.1修复此问题，在此之前建议避免同时使用这两个扩展
