### ISSUE TITLE
插件与js脚本Bilibili旧播放页有兼容问题，无法获取全部弹幕池

### ISSUE THREAD

**Issue by foxnfo** [xmcp/pakku.js#210]
同时使用本插件与旧播放页脚本会出现只能获取部分弹幕池，只有关闭其中一个才能获取完整弹幕池
对方项目issues也有人反馈过
相关讨论链接：https://github.com/MotooriKashin/Bilibili-Old/issues/283

**Comment by xmcp** [comment]
为了解决新版B站播放器上的问题（#206 #207），pakku更改了弹幕分块的方式，现在应该是与官方播放器逻辑一致。

这也导致了 bilibili-old 之前的反向兼容逻辑失效。他们那边把这部分反向兼容去掉应该就好了。
