### ISSUE TITLE
安装插件后，无法在“稍后再看”播放界面发送弹幕

### ISSUE THREAD

**Issue by dingpamaoo** [xmcp/pakku.js#211]
**是否可以稳定复现：**
可以稳定复现，每次都出现，刷新无效，重启浏览器无效，公司和家里电脑都有此现象，重装无效。

**复现步骤：**
1. 安装扩展
2. 登录bilibili
3. 将视频加入稍后再看
4. 从“收藏”界面进入“稍后再看”播放界面
5. 在“稍后再看”播放界面发送弹幕

**预期行为：**
发送的弹幕会出现在播放器中

**实际行为：**
发送按钮会倒计时，但弹幕没有出现在播放器和弹幕列表中

**系统环境：**
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"off","CLOUD_SYNC":"on","TOOLTIP_KEYBINDING":"on","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1650538431710","_ADVANCED_USER":"off","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","THRESHOLD":"20","POPUP_BADGE":"percent","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","WHITELIST":"[]","PROC_TYPE7":"off","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"off","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"41":{"identical":43,"edit_distance":91,"pinyin_distance":0,"cosine_distance":7,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":5,"shrink":"","scroll":0,"taolu":3,"total":761,"onscreen":620,"maxcombo":17,"maxdispval":122.81469024950697,"error":null,"cid":"580907587","parse_time_ms":21}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"off","DANMU_MARK":"off","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1650538431710"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=33 status=complete `undefined`

- ID=34 status=unloaded `undefined`

- ID=35 status=unloaded `undefined`

- ID=36 status=unloaded `undefined`

- ID=37 status=unloaded `undefined`

- ID=38 status=complete `undefined`

- ID=39 status=unloaded `undefined`

- ID=40 status=complete `https://www.bilibili.com/`

- ID=246 status=complete `https://space.bilibili.com/48223/favlist?spm_id_from=333.1007.0.0`

- ID=41 status=complete `https://www.bilibili.com/medialist/play/watchlater/BV1QL4y1G7YP`

- ID=42 status=complete `undefined`

- ID=251 status=complete `undefined`

- ID=254 status=loading `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,11">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,11">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,1">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,1">你们都好强啊~~~ orz orz orz orz</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,1">Ocarina的声音好奇怪</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,11">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,11">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,11"> 神™·MIDI</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,1">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,1">你们都好强啊~~~ orz orz orz orz</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,1">Ocarina的声音好奇怪</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

**Comment by xmcp** [comment]
将在几天内的v10.2.1版本修复
