### ISSUE TITLE
edge浏览器无法显示弹幕密度分布图

### ISSUE THREAD

**Issue by grace-yh** [xmcp/pakku.js#213]
edge浏览器无法显示弹幕密度分布图，已关闭所有扩展程序，仍无法显示，刷新重启，重新安装都试过了，其他功能正常，就是弹幕密度分布图不显示

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.1.1

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.50`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"prefix","CLOUD_SYNC":"off","TOOLTIP_KEYBINDING":"on","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1650898398820","_ADVANCED_USER":"on","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","REMOVE_SEEK":"off","POPUP_BADGE":"percent","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","WHITELIST":"[]","PROC_TYPE7":"on","THRESHOLD":"3","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"148":{"identical":0,"edit_distance":1,"pinyin_distance":0,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":0,"total":114,"onscreen":113,"maxcombo":2,"maxdispval":24.82292156051326,"error":null,"cid":"71766645","parse_time_ms":4},"150":{"identical":0,"edit_distance":0,"pinyin_distance":0,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":0,"total":0,"onscreen":0,"maxcombo":0,"maxdispval":"","error":null,"cid":"572343099","parse_time_ms":0},"152":{"identical":4802,"edit_distance":6973,"pinyin_distance":307,"cosine_distance":4938,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":772,"shrink":"","scroll":22,"taolu":256,"total":42354,"onscreen":25334,"maxcombo":137,"maxdispval":801.6293623483779,"error":null,"cid":"578274992","parse_time_ms":728},"154":{"identical":7,"edit_distance":110,"pinyin_distance":1,"cosine_distance":2,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":5,"shrink":"","scroll":0,"taolu":0,"total":590,"onscreen":470,"maxcombo":10,"maxdispval":160.32818969950216,"error":null,"cid":"576496799","parse_time_ms":10}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=37 status=complete `https://www.bilibili.com/`

- ID=154 status=complete `https://www.bilibili.com/video/BV1zi4y1U7ut?spm_id_from=333.1007.partition_recommend.content.click`

- ID=38 status=complete `https://search.bilibili.com/all?keyword=%E9%AB%98%E8%83%BD%E8%BF%9B%E5%BA%A6%E6%9D%A1%E5%8A%9F%E8%83%BD&from_source=webtop_search&spm_id_from=333.1007`

- ID=39 status=complete `https://search.bilibili.com/all?vt=96841671&keyword=AKB%E5%8D%81%E5%91%A8%E5%B9%B4&from_source=webtop_search&spm_id_from=333.1007`

- ID=40 status=complete `https://www.bilibili.com/video/BV1VD4y1X7vM?spm_id_from=333.337.search-card.all.click`

- ID=41 status=complete `https://www.bilibili.com/video/BV1YE411n7Rd?p=1`

- ID=42 status=complete `undefined`

- ID=43 status=complete `undefined`

- ID=44 status=complete `undefined`

- ID=46 status=loading `undefined`

- ID=144 status=complete `undefined`

- ID=146 status=complete `undefined`

- ID=145 status=complete `undefined`

- ID=148 status=complete `https://www.bilibili.com/video/BV1Wt411p7hj?p=8`

- ID=149 status=complete `undefined`

- ID=157 status=complete `undefined`

- ID=162 status=complete `undefined`

- ID=163 status=loading `undefined`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"3","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1650898398820"}

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,11">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,11">Ocarina的声音好奇怪</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,10">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,7">]]][[[</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,4"> 神™·MIDI</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,11">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,11">Ocarina的声音好奇怪</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,10">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,7">]]][[[</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,4"> 神™·MIDI</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by xmcp** [comment]
此问题已修复并在5天前将新版提交edge商店，目前状况如图所示：

![image](https://user-images.githubusercontent.com/6646473/165121293-7e24c1b8-1e8c-4169-acdc-b5e77bd01ea6.png)

鉴定为微软全责
