### ISSUE TITLE
开着扩展，无法发弹幕了。

### ISSUE THREAD

**Issue by PyRookie1** [xmcp/pakku.js#215]
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36 Edg/101.0.1210.32`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","DANMU_MARK":"prefix","CLOUD_SYNC":"off","TOOLTIP_KEYBINDING":"on","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1651476012730","_ADVANCED_USER":"off","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","THRESHOLD":"60","POPUP_BADGE":"percent","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","WHITELIST":"[]","PROC_TYPE7":"on","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=2 status=complete `https://www.bilibili.com/medialist/play/watchlater/BV1pA4y1Q7Ed`

- ID=106 status=complete `undefined`

- ID=107 status=complete `undefined`

- ID=114 status=complete `undefined`

- ID=117 status=loading `undefined`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"60","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1651476012730"}

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,11">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,11">Ocarina的声音好奇怪</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,10">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,7">]]][[[</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,4"> 神™·MIDI</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,11">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,11">Ocarina的声音好奇怪</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,10">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,7">]]][[[</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,4"> 神™·MIDI</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by xmcp** [comment]
这是v10.2版本的已知问题，目前已经修复且于4月29日提交微软审核。按照历史经验，该版本大概会在下周（5月10日左右）通过审核。

![image](https://user-images.githubusercontent.com/6646473/166213107-66d66e36-e1d0-4962-a998-afbc07e77d0d.png)

**Comment by PyRookie1** [comment]
好的，非常感谢。

**Comment by PyRookie1** [comment]
好的，非常感谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xmcp/pakku.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 下午5:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xmcp/pakku.js] 开着扩展，无法发弹幕了。 (Issue #215)





 
这是v10.2版本的已知问题，目前已经修复且于4月29日提交微软审核。按照历史经验，该版本大概会在下周（5月10日左右）通过审核。
