### ISSUE TITLE
希望能增加一个简单的同屏弹幕密度调整的功能

### ISSUE THREAD

**Issue by zealousfool** [xmcp/pakku.js#217]
老版本的视频播放器的同屏弹幕密度功能很好用，现在更新之后没有了，既然pakku已经能够统计弹幕密度了，那么增加一个按照密度随机过滤的功能应该不麻烦，作者能否考虑一下

**Comment by xmcp** [comment]
可以尝试B站播放器设置的“弹幕区域”和pakku的“弹幕密度过大时减小字号”等功能，与这个效果类似

**Comment by zealousfool** [comment]
我一直也是设置1/4区域弹幕的，即使这样有些视频弹幕还是很多，非常影响观看，

**Comment by zealousfool** [comment]
而且字号太小什么都看不清楚
