### ISSUE TITLE
配合pakku advanced filter脚本使用时出现多重弹幕

### ISSUE THREAD

**Issue by DanielW10001** [xmcp/pakku.js#218]
配合[`pakku advanced filter`](https://greasyfork.org/scripts/42635-pakku-advanced-filter)脚本 (未修改的初始代码) 使用时, 打开分P的视频页面后出现多重弹幕:
1. 视频开始播放且没有弹幕显示, 此时pakku显示 "正在下载弹幕文件"
2. pakku下载完弹幕文件后, 图标显示为弹幕过滤比率, 此时弹幕正常显示
3. 视频旁的 "弹幕列表" 组件自动展开, 显示 "弹幕列表填充中", 此时弹幕消失
4. "弹幕列表" 组件加载弹幕完成后, 弹幕重新出现, 此时出现两重或三重弹幕

![image](https://user-images.githubusercontent.com/44944011/170837892-958674f7-bca5-48f4-a7b3-4d342e883b32.png)

注意到对于不分P的视频页面则不会出现多重弹幕.

此bug可稳定复现 (哪怕删除其他所有插件及脚本也依然出现):

- 对分P的视频或番剧, 出现多重弹幕: [视频 (播放器2.78.5-04bf8055)](https://www.bilibili.com/video/BV1YT4y1r7XK), [番剧 (播放器3.8.11-e522ba57)](https://www.bilibili.com/bangumi/play/ss2667)
- 对不分P的视频, 不出现多重弹幕: [视频 (播放器2.78.5-04bf8055)](https://www.bilibili.com/video/BV1Q5411X7Ty)

不论如何改动pakku各项设置该bug仍然出现, 且禁用`pakku advanced filter`脚本或pakku插件后不再出现.
#205 也曾报告过类似的bug.

<details>

<summary>[Debug Info]</summary>

**Version:** 10.2.3

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"3","DANMU_MARK":"suffix","CLOUD_SYNC":"on","TOOLTIP_KEYBINDING":"on","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1653759970797","_ADVANCED_USER":"on","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","MAX_COSINE":"60","THRESHOLD":"20","POPUP_BADGE":"percent","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","WHITELIST":"[]","PROC_TYPE7":"on","TRIM_WIDTH":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","AUTO_DISABLE_DANMU":"off","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"90":{"identical":889,"edit_distance":2970,"pinyin_distance":51,"cosine_distance":42,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":158,"shrink":"","scroll":1,"taolu":19,"total":15674,"onscreen":11722,"maxcombo":73,"maxdispval":368.88107269825304,"error":null,"cid":"95274040","parse_time_ms":1500},"116":{"identical":1249,"edit_distance":4908,"pinyin_distance":40,"cosine_distance":34,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":291,"shrink":"","scroll":2,"taolu":8,"total":24546,"onscreen":18315,"maxcombo":52,"maxdispval":374.4022236242444,"error":null,"cid":"95274040","parse_time_ms":2687},"143":{"identical":1243,"edit_distance":4924,"pinyin_distance":40,"cosine_distance":35,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":293,"shrink":"","scroll":2,"taolu":7,"total":24698,"onscreen":18456,"maxcombo":49,"maxdispval":400.1703568544067,"error":null,"cid":"95274040","parse_time_ms":2874},"146":{"identical":173,"edit_distance":270,"pinyin_distance":3,"cosine_distance":68,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":24,"shrink":"","scroll":0,"taolu":8,"total":1744,"onscreen":1230,"maxcombo":83,"maxdispval":101.03895496510786,"error":null,"cid":"731474761","parse_time_ms":39},"149":{"identical":2689,"edit_distance":3595,"pinyin_distance":179,"cosine_distance":414,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":269,"shrink":"","scroll":9,"taolu":94,"total":26995,"onscreen":20118,"maxcombo":217,"maxdispval":243.84341436983976,"error":null,"cid":"585914385","parse_time_ms":820},"152":{"identical":173,"edit_distance":277,"pinyin_distance":3,"cosine_distance":59,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":25,"shrink":"","scroll":0,"taolu":8,"total":1745,"onscreen":1233,"maxcombo":83,"maxdispval":101.03895496510788,"error":null,"cid":"731474761","parse_time_ms":34}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*","ws://*.bilibili.com/*","wss://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"on","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"3","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1653759970797"}

**Tabs:**

- ID=2 status=complete `undefined`

- ID=81 status=complete `undefined`

- ID=87 status=complete `https://www.bilibili.com/`

- ID=146 status=complete `https://www.bilibili.com/video/BV1Q5411X7Ty`

- ID=152 status=complete `https://www.bilibili.com/video/BV1Q5411X7Ty`

- ID=149 status=complete `https://www.bilibili.com/video/BV1YT4y1r7XK`

- ID=143 status=complete `https://www.bilibili.com/bangumi/play/ss2667`

- ID=116 status=complete `https://www.bilibili.com/bangumi/play/ss2667?t=780`

- ID=128 status=complete `undefined`

- ID=113 status=complete `undefined`

- ID=155 status=loading `undefined`

- ID=158 status=loading `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,10">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,10">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,10">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,10">Ocarina的声音好奇怪</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,7">]]][[[</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,4"> 神™·MIDI</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,10">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,10">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,10">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,10">Ocarina的声音好奇怪</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,7">]]][[[</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,4"> 神™·MIDI</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059

</details>

<details>

<summary>所使用的pakku advanced filter初始代码</summary>

```javascript
// ==UserScript==
// @name         pakku advanced filter
// @namespace    http://s.xmcp.ml/pakkujs/
// @version      0.3
// @description  弹幕屏蔽Pro+
// @author       xmcp
// @match        *://*.bilibili.com/*
// @grant        none
// ==/UserScript==

// 请先安装 [pakku](http://s.xmcp.ml/pakkujs/)

const NEED_UID = true; // 是否需要使用 cracked_uid 属性（慢）

// 屏蔽规则写在这个函数里
function do_filter(D) {
    var ret = [];
    D.forEach((d) => {
        ret.push(d.ir_obj);
    });
    return ret;
}

(function() {
    'use strict';

    function comp_ver(ver1, ver2) {
        ver1 = ver1.split('.').map( s => s.padStart(10) ).join('.');
        ver2 = ver2.split('.').map( s => s.padStart(10) ).join('.');
        return ver1 < ver2;
    }
    function check_ver(ver) {
        if(comp_ver(ver, '10.0'))
            alert('此版本的 pakku advanced filter 用户脚本依赖于 pakku 10.0 或更高版本');
    }

    let COMPLETED_TIME=-10000;

    addEventListener('message', function(e) {
        if(e.data.type==='pakku_event_danmaku_loaded') {
            if((+new Date())-COMPLETED_TIME<5000) return;
            check_ver(e.data.pakku_version||'0');
            if(NEED_UID) {
                postMessage({type: 'pakku_get_danmaku_with_uid'},'*');
            } else {
                postMessage({type: 'pakku_get_danmaku'},'*');
            }
        } else if(e.data.type==='pakku_got_danmaku') {
            const D=do_filter(e.data.resp);
            console.log('pakku advanced filter: '+D.length+' danmakus left');
            COMPLETED_TIME=(+new Date());
            window.postMessage({type: 'pakku_set_danmaku_bounce', danmakus: D},'*');
        }
    });
})();
```

</details>

**Comment by xmcp** [comment]
这应该是B站新版播放器的bug，而不是pakku。

确认方式：
- 禁用所有扩展程序（包括pakku）
- 随便打开一个B站视频
- 在弹幕列表下方点击“查看历史弹幕”，随便选择一个日期
- 重复上一步多次
- 发现出现了多重弹幕

建议找B站反映这个问题。话是这么说，但我也不知道找谁反映，这个bug已经存在至少一个月了。

**Comment by DanielW10001** [comment]
经确认, 禁用所有扩展程序和脚本的情况下, 通过反复切换历史弹幕, 可以在[番剧 (播放器3.8.11-e522ba57)](https://www.bilibili.com/bangumi/play/ss2667)中复现该bug, 但无法在[视频 (播放器2.78.5-04bf8055)](https://www.bilibili.com/video/BV1YT4y1r7XK)中复现该bug.
目前可行的解决方法可能是暂且禁用`pakku advanced filter`, 仅启用pakku插件, 同时等待B站修复.
供后来者参考.
