### ISSUE TITLE
最近B站出了一个很恶心的弹幕类型,目前的功能无法屏蔽

### ISSUE THREAD

**Issue by 233YUZI** [xmcp/pakku.js#219]
bv1PB4y1S7ud视频第一次见,广告弹幕,会识别关键词自动转换成广告弹幕
![image](https://user-images.githubusercontent.com/69708373/173173487-711d4696-111f-4575-a4ae-38acc081c8ee.png)

**Comment by xmcp** [comment]
这是B站已有的弹幕类型，类似于之前的“梗弹幕”功能，会把匹配某些规则的弹幕替换成图片。
![image](https://user-images.githubusercontent.com/6646473/173174705-d11bc043-18f5-404b-9b08-51401ebaa090.png)


pakku可以正常合并这类弹幕。
![image](https://user-images.githubusercontent.com/6646473/173174692-f6a2c375-7fa9-40e9-8490-dc6c6e82025f.png)

如果你仍看到重复的弹幕，可能是打开视频后动态加载的实时弹幕。pakku目前无法合并这些弹幕（因为B站播放器并未向第三方程序提供修改已有弹幕的接口），但是可以在pakku设置中勾选【阻止弹幕动态更新】来阻止加载实时弹幕的行为（播放器将仅显示打开视频时已有的弹幕）。

**Comment by 233YUZI** [comment]
哦,我想表达的是,这种"梗弹幕"的匹配规则用户是不知晓的,也就是说不知道什么时候会弹出这种弹幕,总不可能每次都手动找关键词屏蔽或者正则屏蔽吧,能否加一个直接干掉所有"梗弹幕"的功能

**Comment by 233YUZI** [comment]
> 这是B站已有的弹幕类型，类似于之前的“梗弹幕”功能，会把匹配某些规则的弹幕替换成图片。 ![image](https://user-images.githubusercontent.com/6646473/173174705-d11bc043-18f5-404b-9b08-51401ebaa090.png)
> 
> pakku可以正常合并这类弹幕。 ![image](https://user-images.githubusercontent.com/6646473/173174692-f6a2c375-7fa9-40e9-8490-dc6c6e82025f.png)
> 
> 如果你仍看到重复的弹幕，可能是打开视频后动态加载的实时弹幕。pakku目前无法合并这些弹幕（因为B站播放器并未向第三方程序提供修改已有弹幕的接口），但是可以在pakku设置中勾选【阻止弹幕动态更新】来阻止加载实时弹幕的行为（播放器将仅显示打开视频时已有的弹幕）。

哦,我想表达的是,这种"梗弹幕"的匹配规则用户是不知晓的,也就是说不知道什么时候会弹出这种弹幕,总不可能每次都手动找关键词屏蔽或者正则屏蔽吧,能否加一个直接干掉所有"梗弹幕"的功能

**Comment by xmcp** [comment]
感觉梗弹幕本身对用户的干扰不大（只是把文字替换成图片，替换后占据屏幕空间实际上还减少了），梗弹幕只有在大量刷屏时才会影响观感，但pakku已经能解决这种情况（多个梗弹幕合并之后因为文字发生了变化，将不再是梗弹幕）。

之前好像听说过打开播放器的屏蔽高级弹幕设置之后可以屏蔽梗弹幕。

**Comment by 233YUZI** [comment]
我是把计数功能关闭了,还有合并越多越大打开了,只是觉得这些非文字图标挺碍眼的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月11日(星期六) 下午2:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xmcp/pakku.js] 最近B站出了一个很恶心的弹幕类型,目前的功能无法屏蔽 (Issue #219)





 
感觉梗弹幕本身对用户的干扰不大（只是把文字替换成图片，替换后占据屏幕空间实际上还减少了），梗弹幕只有在大量刷屏时才会影响观感，但pakku已经能解决这种情况（多个梗弹幕合并之后因为文字发生了变化，将不再是梗弹幕）。
 
之前好像听说过打开播放器的屏蔽高级弹幕设置之后可以屏蔽梗弹幕。
