### ISSUE TITLE
全半角字符合并

### ISSUE THREAD

**Issue by jeffswt** [xmcp/pakku.js#22]
https://bangumi.bilibili.com/anime/5998/play#103897

![image](https://user-images.githubusercontent.com/18145331/27759857-fd5762c6-5e6c-11e7-8411-0108c75807cb.png)

有没有这类的库一类的啊...

**Comment by fanthos** [comment]
太麻烦了，在判断之前删掉所有符号就好了

**Comment by xmcp** [comment]
@fanthos 删掉所有符号有点暴力呀……比如说：
- `+1s` 和 `-1s` 会被认为是完全相同的
- `233` 和 `２３３` 仍然会被认为是不同的

如果要处理全半角转换的话，我觉得可以把 [`detaolu`](https://github.com/xmcp/pakku.js/blob/master/pakkujs/core/core.js#L42-L43) 里面的两个正则直接改成一个for扫过去，效率上也会提高。

**Comment by celeron533** [comment]
只能做个字符映射表了。。。全都替换成统一字符

**Comment by fanthos** [comment]
刚查了一下，好像有更好的合并方法
https://stackoverflow.com/questions/20486551/javascript-function-to-convert-utf8-string-between-fullwidth-and-halfwidth-forms
如果字符的unicode在0xFF01到0xFF5E中间，减去0xFFE0就好了

**Comment by fanthos** [comment]
```javascript
 str1.replace(/[\uff01-\uff5e]/g, (_x) => String.fromCharCode(_x[0] - 0xfee0));
```

**Comment by jeffswt** [comment]
やばり `won't fix` か...

**Comment by xmcp** [comment]
@jeffswt 3e940ad1e70d4fce52d1079147fdd2d8d33a1daa 实现了 TRIM_WIDTH
