### ISSUE TITLE
将鼠标放在弹幕上时, 会显示那三种按钮.

### ISSUE THREAD

**Issue by lolisix** [xmcp/pakku.js#223]
将鼠标放在弹幕上时, 会显示那三种按钮. 比如下面图片的右上角位置.
<img src="https://s2.loli.net/2022/08/04/ua6spmE7MNFXRSz.png" alt="三种按钮"/>
**是否可以稳定复现：**

可以

**复现步骤：**

1. 将视频全屏.
2. 将鼠标放在弹幕上.

**预期行为：**

什么都不显示

**B站播放器版本号：**

3.15.4-50c8e7e6

**pakku调试信息：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.3

**Channel:** firefox

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0`

**Incognito:** `false`

**localStorage:** `{"FLUCTLIGHT":"on","BREAK_UPDATE":"off","PROC_TYPE7":"off","TRIM_SPACE":"on","DANMU_SUBSCRIPT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","TRIM_PINYIN":"on","POPUP_BADGE":"percent","REMOVE_SEEK":"off","TOOLTIP":"on","MAX_DIST":"3","SCROLL_THRESHOLD":"1200","WHITELIST":"[]","REPRESENTATIVE_PERCENT":"20","MODE_ELEVATION":"off","DANMU_MARK":"prefix","SHRINK":"on","TRIM_ENDING":"on","MARK_THRESHOLD":"1","CROSS_MODE":"off","MAX_COSINE":"85","BLACKLIST":"[]","PROC_POOL1":"off","ENLARGE":"on","TRIM_WIDTH":"on","AUTO_DISABLE_DANMU":"off","TAOLUS":"","TOOLTIP_KEYBINDING":"on","_LAST_UPDATE_TIME":"1659607853276","AUTO_DANMU_LIST":"off","PROC_TYPE4":"on","HIDE_THRESHOLD":"0","FLASH_NOTIF":"on","THRESHOLD":"5","CLOUD_SYNC":"off","_ADVANCED_USER":"on"}`

**Views:**

- `moz-extension://de226ba9-8437-4793-b41d-259b7dbbc694/core/background.html`

- `moz-extension://de226ba9-8437-4793-b41d-259b7dbbc694/page/options.html#threshold`

- `moz-extension://de226ba9-8437-4793-b41d-259b7dbbc694/page/troubleshooting.html`

**Background / IS_FIREFOX:** true

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"1":{"identical":185,"edit_distance":150,"pinyin_distance":14,"cosine_distance":234,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":31,"shrink":262,"scroll":2,"taolu":16,"total":2208,"onscreen":1625,"maxcombo":27,"maxdispval":152.37523253852416,"error":null,"cid":"792671920","parse_time_ms":27}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*","ws://*.bilibili.com/*","wss://*.bilibili.com/*"],"permissions":["webRequest","webRequestBlocking","notifications","storage"]}`

**Storage / Sync:** {"PROC_TYPE4":"on","HIDE_THRESHOLD":"0","FLASH_NOTIF":"on","THRESHOLD":"5","TRIM_SPACE":"on","FLUCTLIGHT":"on","DANMU_SUBSCRIPT":"on","TRIM_ENDING":"on","PROC_TYPE7":"off","TAOLUS":"","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","BREAK_UPDATE":"off","POPUP_BADGE":"percent","REMOVE_SEEK":"off","TOOLTIP":"on","MAX_DIST":"3","SCROLL_THRESHOLD":"1200","WHITELIST":"[]","CLOUD_SYNC":"off","REPRESENTATIVE_PERCENT":"20","MODE_ELEVATION":"off","DANMU_MARK":"prefix","SHRINK":"on","MARK_THRESHOLD":"1","CROSS_MODE":"off","MAX_COSINE":"85","PROC_POOL1":"off","ENLARGE":"on","TRIM_WIDTH":"on","AUTO_DISABLE_DANMU":"off","TOOLTIP_KEYBINDING":"on","_LAST_UPDATE_TIME":"1659607853276","AUTO_DANMU_LIST":"off","BLACKLIST":"[]","TRIM_PINYIN":"on","_ADVANCED_USER":"on"}

**Tabs:**

- ID=3 status=complete `undefined`

- ID=1 status=complete `https://www.bilibili.com/video/BV1WU4y1Y7Vt?vd_source=6c6ee6ed729ba2eb177f90d724ec0f55`

- ID=25 status=complete `moz-extension://de226ba9-8437-4793-b41d-259b7dbbc694/page/options.html#threshold`

- ID=26 status=loading `moz-extension://de226ba9-8437-4793-b41d-259b7dbbc694/page/troubleshooting.html`

- ID=19 status=complete `undefined`

- ID=20 status=complete `undefined`

- ID=21 status=complete `undefined`

- ID=22 status=complete `undefined`

- ID=23 status=complete `undefined`

**Request / Normal XML:** load, status=200 `<i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><d p="0,1,25,16777215,1524407554,0,91d6b7d0,4480703586">₍₂₎]]][[[</d><d p="0.034,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="14.639,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.533,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.725,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.377,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.918,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.264,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,11">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,11">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,11">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,11">Ocarina的声音好奇怪</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,10"> 神™·MIDI</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,1">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,1">]][[</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,1">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,1"> FFT大法好（13行FFT路过）</d></i>`

**! Exception:** `ReferenceError: test_error_log is not defined`

`moz-extension://de226ba9-8437-4793-b41d-259b7dbbc694/page/troubleshooting.js` :: 2 :: 2228

</details>
控制台信息:
<a href="https://sm.ms/image/Tb9OvIYFEhWtsVa" target="_blank"><img src="https://s2.loli.net/2022/08/04/Tb9OvIYFEhWtsVa.png" ></a>

**Comment by xmcp** [comment]
这是B站播放器的功能，与pakku无关
