### ISSUE TITLE
突然无法查看弹幕用户ID 显示找不到弹幕详细

### ISSUE THREAD

**Issue by jianshunjiang** [xmcp/pakku.js#224]
突然无法查看弹幕用户ID
显示找不到弹幕详细
![image](https://user-images.githubusercontent.com/31506869/192284286-3fa9bfe6-126f-439b-8675-3bd2f06fe489.png)

**Comment by xmcp** [comment]
可能是视频载入后新出现的弹幕，这些后来产生的弹幕无法被pakku处理，所以会显示成这样

**Comment by jianshunjiang** [comment]
> 可能是视频载入后新出现的弹幕，这些后来产生的弹幕无法被pakku处理，所以会显示成这样

 但是好像我发现是所有弹幕都这样显示。。。是不是有B站关了某些API。

**Comment by xmcp** [comment]
这个报错是本地没匹配上这条弹幕，跟B站API无关。目前我这里无法复现。给一个视频链接和播放器版本号？

**Comment by jianshunjiang** [comment]
> 这个报错是本地没匹配上这条弹幕，跟B站API无关。目前我这里无法复现。给一个视频链接和播放器版本号？

可能是我浏览器问题，前几周都有这情况，今天我再试就正常了。谢谢作者
