### ISSUE TITLE
预览右侧的推荐视频，会导致弹幕密度图的弹幕异常变成预览视频的弹幕

### ISSUE THREAD

**Issue by qmzmdqs** [xmcp/pakku.js#227]
chrome 当前最新版本稳定重现。

印象中这个问题有一段时间了，之前以为是偶然情况。

**Comment by xmcp** [comment]
新版播放器预览右侧视频也会加载弹幕，而且和切换视频后播放器正常加载弹幕的URL完全一样导致pakku以为切换了视频。我看看怎么处理一下……

**Comment by xmcp** [comment]
v10.2.4已修复此问题，chrome web store大概要审核一小时到几天的时间，更新之后问题应该就解决了。
