### ISSUE TITLE
[enhancement]按字符数屏蔽

### ISSUE THREAD

**Issue by dyxang** [xmcp/pakku.js#229]
请求添加按字符数屏蔽的功能，原因来自于以下情况：

- 有些弹幕只有一两个字且与视频无关，比如:啊\哦\嗯\乐\额\好
- 有些弹幕是评分弹幕，纯数字：1-5
- 还有些弹幕是纯标点符号弹幕，完全没有用处，属于是乱按或者误触，杂乱还影响观感，比如`，，，。。`或`。。。。。`或`、。‘`

如果这个功能优先级低的话我会关闭这个ISSUE的

**Comment by DeltaFlyerW** [comment]
这个功能可以用b站的弹幕屏蔽嘛
1. /^.{1,2}$/ 或者 /^[啊|哦|嗯|乐|额|好]{1,2}$/
2.  /^\d{1,2}$/
3.  /^[，|、|。|‘]{1,2}$/
