### ISSUE TITLE
有些莫名其妙，就像刚刚发送的弹幕一样无法合并

### ISSUE THREAD

**Issue by kang3185** [xmcp/pakku.js#23]
![qq 1](https://user-images.githubusercontent.com/12120052/27854573-e5ceb9c6-6199-11e7-82b2-2b956eafc907.jpg)
![qq 2](https://user-images.githubusercontent.com/12120052/27854576-e751cac2-6199-11e7-976d-0bb3c3a1222d.jpg)
，刷新即可解决。。

**Comment by xmcp** [comment]
“弹幕护体”默认是在白名单里的吧？是不是这个原因？

**Comment by xmcp** [comment]
![image](https://user-images.githubusercontent.com/6646473/27855229-40393fba-619c-11e7-8d50-88ee9f88c6cf.png)
选项里面有个白名单（根据 https://github.com/xmcp/pakku.js/issues/11#issuecomment-304714376 添加的），默认包括忽略“弹幕护体”的规则，删掉应该就好了。
