### ISSUE TITLE
b站ep视频会吧弹幕变成双份

### ISSUE THREAD

**Issue by djkcyl** [xmcp/pakku.js#230]
打开插件如下所示
![image](https://user-images.githubusercontent.com/59153990/206837352-f8b02f87-76cb-4bae-803d-03260e2aafcb.png)

关闭后正常
![image](https://user-images.githubusercontent.com/59153990/206837400-dddf7d8b-34ca-4e4e-94eb-f71cc122449f.png)

**Comment by xmcp** [comment]
请按issue模板填写。

另外如果你的插件版本是10.2.4的话是已知问题，10.2.5已经修复。chrome和firefox平台已经更新，edge平台已经提交审核，按照经验要等好几个工作日。

**Comment by whc2001** [comment]
似乎等弹幕加载完成之后开关一次（Alt+R）可以暂时解决这个问题，但是仅当次有效，坐等 Edge 更新

**Comment by djkcyl** [comment]
懂了
