### ISSUE TITLE
“弹幕黑名单”功能支持 .json 文件导入？

### ISSUE THREAD

**Issue by MaxHasBeenUsed** [xmcp/pakku.js#234]
B站在挺早之前就不再支持直接导出 `.xml` 文件了，而 pakku 里始终只支持导入 `xml`。是否可以增加 `.json` 文件的导入支持？

两者关系是 `.json` 里：
```
{"type": 1, "filter": "regex", "opened": true, "id": xxxxxxx }
```
相当于 `.xml` 里：
```
<item enabled="true">r=regex</item>
```
这样。

**Comment by xmcp** [comment]
可以加入。目前可以暂时手工转换一下格式

**Comment by xmcp** [comment]
新版pakku将直接读取播放器黑名单，故关闭此issue
