### ISSUE TITLE
一键导出/显示合并次数最高的弹幕？

### ISSUE THREAD

**Issue by dyxang** [xmcp/pakku.js#236]
导出或者显示本视频合并次数最高的弹幕，（可能）帮助用户更好的屏蔽一些弹幕，扩充自己的弹幕黑名单
只是一个想法

**Comment by xmcp** [comment]
可以通过脚本获取pakku处理后的弹幕列表，参考 https://github.com/xmcp/pakku-advanced-filter/blob/master/pakku-advanced-filter.user.js
