### ISSUE TITLE
【BUG】pakku开启后弹幕无法加载

### ISSUE THREAD

**Issue by quinese** [xmcp/pakku.js#238]
**是否可以稳定复现：**

**复现步骤：**

1. 打开pakku后弹幕就一直显示加载中
2. 

**预期行为：**

**实际行为：**
![image](https://user-images.githubusercontent.com/105223922/223111805-eae877d5-c45a-413e-888d-007c11d1fa9a.png)

**禁用pakku后bug是否存在：**
禁用后恢复正常

**禁用其他插件后bug是否存在：**
是

**B站播放器版本号：**
3.27.2-rc.554.0-b980be96

**pakku调试信息：**
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.5

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63`

**Incognito:** `false`

**localStorage:** `{"_ADVANCED_USER":"on","MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","DANMU_MARK":"prefix","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1678105992956","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","THRESHOLD":"20","TRIM_WIDTH":"on","POPUP_BADGE":"percent","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","WHITELIST":"[]","CLOUD_SYNC":"on","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","MAX_COSINE":"60","ENLARGE":"on","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","AUTO_DISABLE_DANMU":"off","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"1746100587":{"identical":59,"edit_distance":97,"pinyin_distance":6,"cosine_distance":2,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":6,"shrink":"","scroll":0,"taolu":1,"total":754,"onscreen":590,"maxcombo":16,"maxdispval":88.25748088714391,"error":null,"cid":"1040734991","parse_time_ms":19},"1746100590":{"identical":7,"edit_distance":16,"pinyin_distance":0,"cosine_distance":0,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":1,"shrink":"","scroll":0,"taolu":0,"total":296,"onscreen":273,"maxcombo":6,"maxdispval":44.14239911909041,"error":null,"cid":"1040933162","parse_time_ms":6}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1678105992956"}

**Tabs:**

- ID=1746100583 status=complete `https://www.bilibili.com/?spm_id_from=333.788.b_696e7465726e6174696f6e616c486561646572.1`

- ID=1746100656 status=complete `undefined`

- ID=1746100659 status=loading `undefined`

- ID=1746100627 status=complete `undefined`

- ID=1746100587 status=complete `https://www.bilibili.com/video/BV1E84y1P7rK/?spm_id_from=333.851.b_7265636f6d6d656e64.2&vd_source=f7e2ceb8f67aa06bc9cc8e47d3f5aff5`

- ID=1746100590 status=complete `https://www.bilibili.com/video/BV16M411471p/?spm_id_from=333.851.dynamic.content.click&vd_source=f7e2ceb8f67aa06bc9cc8e47d3f5aff5`

- ID=1746100630 status=complete `undefined`

- ID=1746100637 status=complete `undefined`

- ID=1746100634 status=complete `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

**Comment by xmcp** [comment]
尚未遇到此问题，大概是因为这个版本的播放器还没灰度到我。此bug（如果真的存在）将在我这里能复现后修复。

**Comment by MC-dusk** [comment]
+1

**Comment by wind-v** [comment]
+1

**Comment by xiaolingtong** [comment]
> 尚未遇到此问题，大概是因为这个版本的播放器还没灰度到我。此bug（如果真的存在）将在我这里能复现后修复。

确认同样遭遇到该问题，仅加载pakku时弹幕如同楼主所示一直显示“弹幕列表填充中”，关闭pakku后恢复正常；确认谷歌浏览器和pakku为最新版本

**Comment by zhangqq008** [comment]
昨天开始一直无法正常加载弹幕找了半天才发现怎么回事，确定只是个别人遇到这个灰度测试的播放器版本的问题？

**Comment by xmcp** [comment]
v10.2.6已修复此问题并提交各平台。

Firefox Addons已更新，Chrome Web Store一般会在一天之内通过审核，Edge商店一般会在大约7天后通过审核。

**Comment by mengke152** [comment]
> **是否可以稳定复现：**
> 
> **复现步骤：**
> 
> 1. 打开pakku后弹幕就一直显示加载中
> 
> **预期行为：**
> 
> **实际行为：** ![image](https://user-images.githubusercontent.com/105223922/223111805-eae877d5-c45a-413e-888d-007c11d1fa9a.png)
> 
> **禁用pakku后bug是否存在：** 禁用后恢复正常
> 
> **禁用其他插件后bug是否存在：** 是
> 
> **B站播放器版本号：** 3.27.2-rc.554.0-b980be96
> 
> **pakku调试信息：**
> 
> [Debug Info]
> **其他说明：**

我也是这样

**Comment by Loss-of-time** [comment]
Edge+1

**Comment by gongfuture** [comment]
再次出现此问题，问题和复现均同上
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.7

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.0.0`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","_ADVANCED_USER":"on","DANMU_MARK":"prefix","TAOLUS":"","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1694752255037","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","REMOVE_SEEK":"off","THRESHOLD":"5","POPUP_BADGE":"percent","TRIM_WIDTH":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"on","WHITELIST":"[]","PROC_TYPE7":"off","PROC_POOL1":"off","CROSS_MODE":"off","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"off","TRIM_PINYIN":"on","ENLARGE":"on","MAX_COSINE":"60","MODE_ELEVATION":"off","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"2080937358":{"identical":410,"edit_distance":665,"pinyin_distance":11,"cosine_distance":50,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":13,"script":0,"enlarge":69,"shrink":1253,"scroll":0,"taolu":4,"total":2418,"onscreen":1282,"maxcombo":42,"maxdispval":433.6973687715303,"error":null,"cid":"1267802177","parse_time_ms":44}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*","https://www.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"off","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"off","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"off","PROC_TYPE7":"off","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","TAOLUS":"","THRESHOLD":"5","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1694752255037"}

**Tabs:**

- ID=2080937264 status=complete `undefined`

- ID=2080937358 status=complete `https://www.bilibili.com/video/av363466092/`

- ID=2080937365 status=complete `undefined`

- ID=2080937368 status=loading `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`


**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by gongfuture** [comment]
> 再次出现此问题，问题和复现均同上
> 
> [Debug Info]

<img width="173" alt="Snipaste_2023-09-15_12-34-40" src="https://github.com/xmcp/pakku.js/assets/60888755/d1ca7989-f71f-40ba-b27a-e4d7c6dadf1d">
<img width="261" alt="Snipaste_2023-09-15_12-34-44" src="https://github.com/xmcp/pakku.js/assets/60888755/bdb76feb-7ba1-416d-ad1f-eb1408aa7f46">

**Comment by Vanadiry** [comment]
+1 同出现此问题
