### ISSUE TITLE
B站播放器居然能加载有编码问题的弹幕XML？

### ISSUE THREAD

**Issue by xmcp** [xmcp/pakku.js#24]
举例来说，[av1278409](http://www.bilibili.com/video/av1278409/) 就会遇到 pakku 提示服务端错误（因为`xhr.responseXML===null`），但播放器能正常加载弹幕的情况。

![image](https://user-images.githubusercontent.com/6646473/28079515-4f25fe10-669b-11e7-99d9-4419bf42e288.png)

发现浏览器也无法正常加载这个XML。

![image](https://user-images.githubusercontent.com/6646473/28079541-5f3031c2-669b-11e7-85b7-36f112623ddc.png)

Traceback 所在的 884 行内容如下：

```xml
<d p="175.51600646973,5,25,16777215,1485244967,0,500d8218,2892823994">av1141873</d>
```

最后面那个特殊符号（好像是个 `\x16`？）就是引发这个问题的原因。

倒是很好奇B站播放器时怎么正常解析这个 XML 文件的。

面白い

**Comment by xmcp** [comment]
B站的操作好像是这个：
```javascript
dz: function(k) {
	try {
		k = k.replace(/[\x00-\x08\x0b-\x0c\x0e-\x1f\x7f]/g, "")
	} catch (c) {
		(undefined)
	}
	return (new window.DOMParser).parseFromString(k, "text/xml")
},
```

**Comment by fanthos** [comment]
通过看源代码发现在处理之前用过了这一行
`string.replace(/[\x00-\x08\x0b-\x0c\x0e-\x1f\x7f]/g,"")`
