### ISSUE TITLE
对点赞数大的弹幕进行放大

### ISSUE THREAD

**Issue by amlkiller** [xmcp/pakku.js#240]
如题，b站现有一功能可以给弹幕点赞，希望可以在合并弹幕的同时对这些点赞数大的弹幕放大，将点赞数作为是否放大弹幕的参考因素。
![image](https://user-images.githubusercontent.com/62412330/224468588-e9499817-e731-429c-b968-8e8b1c459769.png)

**Comment by xmcp** [comment]
目前B站无法批量查询弹幕的点赞数（只有一个布尔状态表示是否显示赞图标），只能分别查询单个弹幕有多少赞（鼠标划过时会查询当前弹幕的赞数）。在可以批量查询所有弹幕的点赞数之前暂不考虑此功能。
