### ISSUE TITLE
将pakku.js集成至哔哩漫游中

### ISSUE THREAD

**Issue by DeltaFlyerW** [xmcp/pakku.js#242]
大佬你好,我最近在哔哩漫游的弹幕过滤功能中,用kotlin重写了pakku的核心功能,希望在手机上也能过滤某些刷屏弹幕.
哔哩漫游本身也是以GPLv3开源的,请问能否将您的代码集成至漫游中呢.
https://github.com/DeltaFlyerW/BiliRoaming/blob/65e1385eb83402fb690c89f0a3ffec5196c65916/app/src/main/java/me/iacn/biliroaming/hook/DanmakuHook.kt#L88

**Comment by xmcp** [comment]
按GPLv3的要求做就可以。如果可以的话最好在相关功能的界面里（比如设置里面对应功能的开关）注明一下来源于pakku.js
