### ISSUE TITLE
希望能过滤掉新出现的大会员彩色弹幕

### ISSUE THREAD

**Issue by zackymony** [xmcp/pakku.js#246]

**Comment by Huan-zhaojun** [comment]
不是本身就可以了吗。我也不明白什么原理，但是目前这个插件就是可以把所有的会员的彩色弹幕全部压成白色。

**Comment by Huan-zhaojun** [comment]
不是本身就可以了吗。我也不明白什么原理，但是目前这个插件就是可以把所有的会员的彩色弹幕全部压成白色。

**Comment by zackymony** [comment]
>

**Comment by zackymony** [comment]
> 不是本身就可以了吗。我也不明白什么原理，但是目前这个插件就是可以把所有的会员的彩色弹幕全部压成白色。

没找到相关的设置...

**Comment by Huan-zhaojun** [comment]
> > 不是本身就可以了吗。我也不明白什么原理，但是目前这个插件就是可以把所有的会员的彩色弹幕全部压成白色。
> 
> 没找到相关的设置...

不用任何设置，只要开启了弹幕优化让这个插件处于工作中，就自动压成白色了。目前是没有单独对“vip专属弹幕”的屏蔽开关的。
![image](https://github.com/xmcp/pakku.js/assets/111294954/066133b5-092b-4fc7-8dbb-55f9e7a3f077)

**Comment by xmcp** [comment]
这是纯粹出于偶然。因为B站更新了protobuf添加了彩色弹幕相关字段，pakku的protobuf定义没有随之更新，处理一遍之后相关字段就丢失了。

**Comment by xmcp** [comment]
打算之后迁移到manifest v3的时候进行一波重构，届时允许更深入的自定义

**Comment by xmcp** [comment]
可以升级到 [v2024.3.1](https://github.com/xmcp/pakku.js/releases/tag/2024.3.1) 后通过 [用户脚本](https://github.com/xmcp/pakku.js/blob/master/userscript_docs/README.md) 实现此功能
