### ISSUE TITLE
Alt+R快捷键与其它网页冲突

### ISSUE THREAD

**Issue by BlueDolphin9527** [xmcp/pakku.js#248]
幕布网页版快捷键Alt+R功能与弹幕过滤器冲突，希望过滤器能增加一个选项，由用户来决定是否开启快捷键；或者只在B站网页端操作时才开启快捷键，在其它网页时不开启。

**Comment by xmcp** [comment]
#247
快捷键可以在浏览器内更改。chrome浏览器的设置在 chrome://extensions/shortcuts
