### ISSUE TITLE
弹幕空降功能建议

### ISSUE THREAD

**Issue by bingyunhe** [xmcp/pakku.js#249]
我使用Bilibili Evolved插件，里面有个弹幕空降功能，作用是为可能含有时间点的弹幕添加下划线, 点击可以跳到视频对应时间。但是弹幕合并后这功能就无效了，不知道是否能改进或者设置时间弹幕不合并

**Comment by xmcp** [comment]
合并后功能无效大概是因为添加了合并数量前缀之后Bilibili Evolved无法识别，虽然我没实际检查。

可以在设置里添加【强制忽略规则】使得时间弹幕不合并。
