### ISSUE TITLE
包含外链播放器的页面会触发播放器兼容提示

### ISSUE THREAD

**Issue by journey-ad** [xmcp/pakku.js#25]
比如[这个页面](https://steamcn.com/t302444-1-1)

系统：Windows 10 1703
浏览器：Chrome 62.0.3196.2 canary x64
pakku v6.8

**Comment by xmcp** [comment]
因为它外链的就是 Flash 播放器呀，这个提示没毛病。

**Comment by journey-ad** [comment]
我的意思是可以考虑排除对外链播放器的提示，因为外链播放器只支持 flash，主站其否启用 html5 播放器对其无影响。目前每次打开相关页面都会提示，这个提示是不必要的。

**Comment by xmcp** [comment]
恩……讲真，Flash 只剩不到三年的历史进程了，HTML5 外链播放器已经有人实现了，比如 [萌百](https://zh.moegirl.org/Template:BilibiliVideo) 就是非常吼的。

**如果你不想要这个提示的话，选项页面最底下是有开关的（`#flash-notif`），关掉就好。**

Flash播放器提示的这个设计我也觉得没必要，但是最开始的时候有一堆人跟我反应 pakku 不工作，一大半都是没切换到 HTML5 播放器。自从我加上这个提示之后就再也没有人问这种问题了。
