### ISSUE TITLE
扩展完全无法使用，显示本页面没有发现B站播放器

### ISSUE THREAD

**Issue by fengixng** [xmcp/pakku.js#250]
**是否可以稳定复现：**
稳定复现

**复现步骤：**
扩展直接显示本页面没有发现B站播放器

**禁用其他插件后bug是否存在：**
全部禁止后只保留本扩展依然存在

**B站播放器版本号：**
4.4.0-802d3d14

**pakku调试信息：**
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.6

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","_ADVANCED_USER":"on","DANMU_MARK":"suffix","TAOLUS":"","FOOLBAR":"on","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1692210679898","FLASH_NOTIF":"on","SHRINK":"on","TRIM_SPACE":"on","MAX_DIST":"3","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","REMOVE_SEEK":"off","THRESHOLD":"20","POPUP_BADGE":"percent","TRIM_WIDTH":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"on","WHITELIST":"[]","PROC_TYPE7":"off","PROC_POOL1":"off","CROSS_MODE":"off","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","MAX_COSINE":"85","MODE_ELEVATION":"on","AUTO_PREVENT_SHADE":"on","AUTO_DISABLE_DANMU":"off","REPRESENTATIVE_PERCENT":"0","TOOLTIP":"on","SCROLL_THRESHOLD":"0"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","AUTO_PREVENT_SHADE":"on","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"on","CROSS_MODE":"off","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"on","FOOLBAR":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"85","MAX_DIST":"3","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"off","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"0","SHRINK":"on","TAOLUS":"","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1692210679898"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=924615784 status=unloaded `undefined`

- ID=924615785 status=complete `undefined`

- ID=924615786 status=unloaded `undefined`

- ID=924615787 status=unloaded `undefined`

- ID=924615788 status=complete `undefined`

- ID=924615789 status=complete `https://space.bilibili.com/480878656/video`

- ID=924615790 status=complete `https://search.bilibili.com/all?vt=09944990&keyword=The%20Carol%20of%20the%20Old%20Ones&from_source=webtop_search&spm_id_from=333.999&search_source=5`

- ID=924615791 status=complete `https://www.bilibili.com/video/BV1M7411p7Jt/?spm_id_from=333.337.search-card.all.click&vd_source=c16f7ea4cab20989337452c3d33dd33e`

- ID=924615792 status=complete `https://www.bilibili.com/video/BV1eu4y197ns/?spm_id_from=333.999.0.0&vd_source=c16f7ea4cab20989337452c3d33dd33e`

- ID=924615793 status=complete `undefined`

- ID=924615940 status=complete `undefined`

- ID=924615943 status=loading `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

**Comment by BJDSYC** [comment]
我这里也出现了相同的问题，尝试关闭其他扩展、重新安装扩展、更换浏览器皆无法解决。

**调试信息：**
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.6

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","_ADVANCED_USER":"off","DANMU_MARK":"suffix","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1692196446531","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","THRESHOLD":"20","TRIM_WIDTH":"on","POPUP_BADGE":"percent","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","CLOUD_SYNC":"off","WHITELIST":"[]","PROC_TYPE7":"off","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","MAX_COSINE":"60","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"209175832":{"identical":18,"edit_distance":0,"pinyin_distance":0,"cosine_distance":0,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":2,"shrink":"","scroll":0,"taolu":0,"total":34,"onscreen":16,"maxcombo":10,"maxdispval":11.875928319450718,"error":null,"cid":"1235465579","parse_time_ms":1}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1692196446531"}

**Tabs:**

- ID=209175994 status=complete `https://www.bilibili.com/video/BV1yP411w7by?p=3`

- ID=209175936 status=complete `https://www.bilibili.com/video/av957293470`

- ID=209176016 status=loading `https://www.bilibili.com/video/BV1hu4y197FV/`

- ID=209175984 status=complete `https://t.bilibili.com/`

- ID=209176019 status=complete `undefined`

- ID=209176022 status=loading `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`


**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by lahexhvrv** [comment]
同样情况，应该就是播放器更新无法识别。

**Comment by LinYanxi0** [comment]
同，但发现B站首页鼠标移到上面的小播放器可以使用

**Comment by fengixng** [comment]
我发现播放器今天又更新了，现在是4.4.1-200c3fd1

**Comment by hardshells** [comment]
我也遇到了这个问题
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.6

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","_ADVANCED_USER":"on","DANMU_MARK":"prefix","TAOLUS":"","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1692287114967","FLASH_NOTIF":"on","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","REMOVE_SEEK":"off","THRESHOLD":"20","POPUP_BADGE":"percent","TRIM_WIDTH":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"off","WHITELIST":"[]","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","MAX_COSINE":"60","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","TAOLUS":"","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1692287114967"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=1450897390 status=complete `https://t.bilibili.com/?spm_id_from=333.788.0.0`

- ID=1450897423 status=complete `https://www.bilibili.com/video/BV1Pu411J7pC/?spm_id_from=444.41.list.card_archive.click&vd_source=eb75180d93670e35e62ceda06316c1dd`

- ID=1450897426 status=complete `undefined`

- ID=1450897429 status=loading `undefined`

- ID=1450897394 status=complete `https://www.bilibili.com/video/BV1pP411s77m/?spm_id_from=444.41.list.card_archive.click&vd_source=eb75180d93670e35e62ceda06316c1dd`

- ID=1450897397 status=complete `https://www.bilibili.com/video/BV1A94y1r7Ax/?spm_id_from=444.41.list.card_archive.click&vd_source=eb75180d93670e35e62ceda06316c1dd`

- ID=1450897400 status=complete `https://www.bilibili.com/video/BV17z4y137Xv/?spm_id_from=444.41.list.card_archive.click&vd_source=eb75180d93670e35e62ceda06316c1dd`

- ID=1450897403 status=complete `https://www.bilibili.com/video/BV1vP411s7w8/?spm_id_from=444.41.list.card_archive.click&vd_source=eb75180d93670e35e62ceda06316c1dd`

- ID=1450897406 status=complete `https://www.bilibili.com/video/BV1od4y1A7pd/?spm_id_from=333.337.search-card.all.click&vd_source=eb75180d93670e35e62ceda06316c1dd`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`


**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by xmcp** [comment]
v10.2.7已适配新版播放器。Firefox和Chrome商店将很快更新，Edge商店预计需要审核一到两周时间。
