### ISSUE TITLE
[下載相關] 請問Firefox擴展是不是下架了 想安裝下載不了

### ISSUE THREAD

**Issue by checkpoint1112** [xmcp/pakku.js#259]
用Firefox無法下載pakku 顯示
如果您是点击其他网站上的链接而来，想寻找某个扩展或主题，该项目却已不可用。这可能是因为：

    开发者主动下架。他们通常会因为不再支持该扩展或主题，或已推出替代版本而这么做。
    Mozilla 已将其下架。这可能是因为在审核扩展或主题的过程中发现问题，或是该扩展或主题违反了 addons.mozilla.org 的使用条款和条件。开发者会有机会解决问题，并重新上架。

暫時解決方法先在[https://web.archive.org/web/20230910191302/https://addons.mozilla.org/firefox/downloads/file/4155308/pakkujs-10.2.7.xpi](url) 下載xpi文件 然後在Firefox擴展頁面安裝本地擴展

**Comment by checkpoint1112** [comment]
不過有一個問題 pakku的Firefox版無法正常運作一直顯示正在下載彈幕

**Comment by xmcp** [comment]
是的

**Comment by xmcp** [comment]
![Uploading image.png…]()
