### ISSUE TITLE
Firefox资磁计划

### ISSUE THREAD

**Issue by xmcp** [xmcp/pakku.js#26]
`v7.0` 大新闻：用 Content Script 魔改 `XMLHttpRequest` 的方式正式完成了对 Firefox 的初步支持。

目前**好像**没太大的问题：

![image](https://user-images.githubusercontent.com/6646473/29907736-cf814b6a-8e4f-11e7-925c-e32d87c0f449.png)

不过由于 Firefox 没有移植带按钮的 `chrome.notifications`，所以右下角的弹窗还不工作。

由于魔改 XHR 太可怕了，我还不确定是否有各种各样的奇怪的 bug，所以现在还不敢发布这个版本。

总而言之：**急需各种各样的测试**

**Comment by xmcp** [comment]
另外，由于微软制杖，对 Edge 的支持暂不考虑：

![image](https://user-images.githubusercontent.com/6646473/29908074-f8a35ef0-8e51-11e7-8a48-c8175fa8fa53.png)

![image](https://user-images.githubusercontent.com/6646473/29908080-075db36e-8e52-11e7-94d7-e6bdfdf933ba.png)

![image](https://user-images.githubusercontent.com/6646473/29908099-278b3fa8-8e52-11e7-89ed-35e3e0e2733f.png)

**Comment by fanthos** [comment]
我之前在油猴里就是用类似的办法，在打开调试控制台的时候有时会出现bug比如视频无法加载。
没有尝试写成扩展形式，不知道WebExtensions是不是支持之前chrome用的接口。

**Comment by xmcp** [comment]
我把 v7.0 提交到 [Firefox 附加组件](https://addons.mozilla.org/zh-CN/firefox/addon/pakkujs/) 上了，Chrome Webstore 可能需要再经过进一步测试再更新（反正这个版本没有新功能）。

**Comment by fanthos** [comment]
之前看过点Firefox扩展文档，基本上是把Chrome里面的chrome.*替换成了browser.*。
https://github.com/mozilla/webextension-polyfill
这玩意估计会有些帮助

**Comment by fanthos** [comment]
不知道Firefox扩展有没有chrome对象

**Comment by xmcp** [comment]
其实不换成 browser，直接用 `chrome.xxx` 都行。

但 pakku 不支持 Firefox（和旧版 Chrome）的原因不在于这个，在于：

- HTML5播放器 AJAX 加载 `http://comment.bilibili.com/xxx.xml`
- 本来这个文件是在 CORS 头的，所以跨域访问可以成功
- 但是 pakku 把它重定向到了 `data:text/xml,xxxxx`
- 显而易见，Data URI 不带 CORS 头，而且跟播放器所在的 bilibili.com 域名是跨域的
- 所以 pakku 认为一切正常，但是页面上的 XHR 抛出异常，弹幕无法加载

Chrome 从某个版本之后放开了 Data URI 的跨域限制，这就是 pakku 为什么之前只支持比较新的 Chrome。

**Comment by xmcp** [comment]
> This version didn't pass review because of the following problems:
> 1.  Your custom CSP allows remote-script injection which is not allowed.
> 2. This add-on is creating DOM nodes from HTML strings containing potentially unsanitized data, by assigning to innerHTML, jQuery.html, or through similar means. Aside from being inefficient, this is a major security risk. For more information, see https://developer.mozilla.org/en/XUL_School/DOM_Building_and_HTML_Insertion . Here are some examples that were discovered:
> tooltip/panel.js line 108, 227


第一条问题与 `background.html` 植入的 CNZZ 统计代码直接相关。我并不打算删除这段代码，因此在 Mozilla 允许我使用第三方统计代码之前，pakku 放弃 Firefox 平台。

**Comment by fanthos** [comment]
刚才试了一下 Google Analytics 居然是国内IP……

**Comment by celeron533** [comment]
Google的广告和统计功能没有被墙

**Comment by fanthos** [comment]
这不是一回事。他们用国内的IP所以肯定能访问，就跟fonts.googleapis.com一样

**Comment by celeron533** [comment]
>这不是一回事。他们用国内的IP所以肯定能访问，就跟fonts.googleapis.com一样

如果这个网站被墙，他们是不可能合法使用国内IP的。
因为没有被墙，所以还是能做IP-域名备案。

**Comment by fanthos** [comment]
他们在国内有分公司，做广告还有一些别的业务。所以可以合法的用互联网服务。另外google.cn也可以正常访问，但是不提供搜索和邮件等服务，ip地址也是在国内
记得dl.google.com在国内dns能获取到国内ip

**Comment by xmcp** [comment]
对 Firefox 的解决方案：把 CNZZ 的代码直接用 Content Script 插入到 bilibili.com 里（每天最多只会插入一次），这样就没有 CSP 什么事了 :)
这样做确实非常不清真，不过反正我也不用 Firefox 所以没啥大问题 :)

**Comment by fanthos** [comment]
他们不让扩展里面执行远程代码大概是安全原因。这么做看起来是个靠谱的办法。问题2需要去解决么还是没问题了

**Comment by xmcp** [comment]
问题2好办啊，https://github.com/xmcp/pakku.js/blob/master/pakkujs/tooltip/panel.js#L17 把那几行 HTML 强行改成 `document.createElement` 就行了，反正也没几行。

直接把 CNZZ 代码注入到 bilibili.com 里其实超级不靠谱，我原来的 iframe 方案可以保证不管 CNZZ 怎么样都只能在 s.xmcp.ml 这个静态的域名里面搞事情，现在的话 CNZZ 的代码直接插入到 bilibili.com 域里了，如果 CNZZ 想搞一波事情直接能拿到B站的cookie，钓个鱼什么的也是非常容易。

**Comment by fanthos** [comment]
那在页面注入一个iframe感觉好像可以

**Comment by xmcp** [comment]
坑点就在这儿。s.xmcp.ml 托管在了 GitHub Pages 上，自定义域名不支持 HTTPS。你自己试一下，访问 https://xmcp.github.io 会跳转到 **http**://s.xmcp.ml 。所以直接GG。

**Comment by fanthos** [comment]
没有尝试过data url，不知道能不能用……

**Comment by xmcp** [comment]
用data url的话CNZZ的代码得不到合法的域名，所以PV会被排除掉。

**Comment by fanthos** [comment]
https://pages.coding.net/
无意间看到了这个，可以尝试

**Comment by xmcp** [comment]
Coding Pages 我现在就在用，但目前仅仅用它来把 xmcp.ml 和 www.xmcp.ml 跳转到 s.xmcp.ml。

Coding Pages 跟 GitHub Pages 相比稳定性比较堪忧（除了偶尔宕机以外，有的时候 push 完新的页面之后要等好几个小时才更新），而且不充会员的话第一次访问会显示一个5秒的广告页面。一开始 s.xmcp.ml 就是托管在 Coding 上面的，后来就换到 GitHub Pages 了。

所以针对 Firefox 的统计就这样了 ┑(￣Д ￣)┍ 安全什么的就不管了，反正我不用 Firefox（逃

**Comment by fanthos** [comment]
大概看了一下，好像有人会在github pages前面加一个CloudFlare就能用HTTPS了。不过免费版需要用CF的dns，在国内比较慢，大概解析需要2秒。

**Comment by xmcp** [comment]
→_→ 我当时也看到这个解决方案了，本来中午想试一下的，但是http://my.freenom.com/ 一直 HTTP 500，从中午一直挂到现在，所以改不成DNS记录。

**Comment by fanthos** [comment]
刚才又试了一下，大概还没恢复。
挂这么长时间也没谁了

**Comment by xmcp** [comment]
现在好像少数页面（域名列表什么的）能访问，官方连个公告都没有真是药丸。

不过Mozilla也好不到哪去呀，你看这都几天了它们才审核了这么点东西。

![image](https://user-images.githubusercontent.com/6646473/30160732-580725e4-9400-11e7-8ff7-8e45aa7c0a3c.png)

**Comment by fanthos** [comment]
我几个月之前对mozilla表示非常失望。Firefox用一天算一天……
等哪天找到个更好用的直接换了（几年前Chrome用出心理阴影）

**Comment by fanthos** [comment]
突然发现审核通过了！2个星期

**Comment by xmcp** [comment]
球球各位谁能在 [addons.mozilla.org](https://addons.mozilla.org/zh-CN/firefox/addon/pakkujs/) 上留个好评啊 :rofl: 现在 “rating: 0/5” 的 Badge 看着好不爽……

**Comment by fanthos** [comment]
没有用户评价的时候不应该是?/5么……

**Comment by jnxyp** [comment]
已赞！！表示很好用

**Comment by xmcp** [comment]
[Extension review wait times are about to get much shorter | Mozilla Add-ons Blog](https://blog.mozilla.org/addons/2017/09/21/review-wait-times-get-shorter/)

(╯‵□′)╯︵┻━┻

**Comment by fanthos** [comment]
Finally.
之前是只有人工审核，现在是机器先预先扫描，然后人工，能节省人力=。=
