### ISSUE TITLE
在360应用商店上架的应用似乎被污染了，会跳转到第三方网站

### ISSUE THREAD

**Issue by NocturneMao** [xmcp/pakku.js#262]
由360极速浏览器从360应用商店安装，打开b站后，会有一定概率跳转到以下网站

扭腰奶爸的趣享
https://60c41b0892e97988c881c073f0296b1c.zunjishoufa.quanfeng.net/?acct=144&site=eG1jcC5tbA==

**是否可以稳定复现：**

任何b站相关网页都会有概率跳转，别的网页就不会。从浏览器，已安装的扩展，开发者网站，会稳定跳转到这个页面。
删除360应用商店版本，从github下载新版本后，已解决此问题。

**复现步骤：**

1. 360应用商店搜索pakku，下载安装；
2. 打开任意b站域名的网页，都有一定概率跳转到下述第三方网页。
扭腰奶爸的趣享
https://60c41b0892e97988c881c073f0296b1c.zunjishoufa.quanfeng.net/?acct=144&site=eG1jcC5tbA==

**预期行为：**

关掉第三方网页，重开之前想看的视频，祈祷不会跳转。

**实际行为：**

打开任意b站域名的网页，都有一定概率跳转到下述第三方网页。
扭腰奶爸的趣享
https://60c41b0892e97988c881c073f0296b1c.zunjishoufa.quanfeng.net/?acct=144&site=eG1jcC5tbA==
<img width="872" alt="e4709ee2489774f1f5958c017a2239c" src="https://github.com/xmcp/pakku.js/assets/67298933/37a22b9f-96b1-44b5-9a90-45764bc2266e">

**禁用pakku后bug是否存在：**

禁用后问题不存在，从360极速浏览器“已安装的扩展”点击“开发者网站”，会稳定跳转到上述网页。

**禁用其他插件后bug是否存在：**

与其他插件无关。

**B站播放器版本号：**

更新历史 4.7.6-efaed801

**pakku调试信息：**

旧版本已删。

**其他说明：**

360应用商店上架版本被第三方篡改，通过跳转到指定网页来谋利。

**Comment by Shabby-666** [comment]
可以用edge浏览器里的“封锁网站”插件来禁止访问这个网站，就很好
