### ISSUE TITLE
请问是否加入了对22年下半开始铺开的新15/16位UID的显示支持？

### ISSUE THREAD

**Issue by neptunium42** [xmcp/pakku.js#264]
RT，查看弹幕发送者细节时会出现有些弹幕不显示发送者的情况（与“找不到 UID”提示有区别），想借此机会询问下这两个问题。
label:question

**Comment by xmcp** [comment]
目前单机计算16位UID速度很慢而且碰撞概率很大，现有算法无法直接迁移过去。如果有其他实现思路欢迎提出。
