### ISSUE TITLE
希望能下载过滤计算过后的弹幕

### ISSUE THREAD

**Issue by douxuebuhui** [xmcp/pakku.js#266]
希望能下载过滤计算过后的弹幕，用于本地观看视频，加载网站上的弹幕，谢谢！

**Comment by xmcp** [comment]
上面那个链接对应的是B站早期的XML API，弹幕数量上限比网页版上实际显示使用的protobuf API要少。

如果想得到目前实际显示的弹幕列表，可以在console里查看 `D` 变量，不过格式可能需要写个脚本转换一下：

![image](https://github.com/xmcp/pakku.js/assets/6646473/2b890a2f-0b8f-4be8-851c-3f11cc3b7375)

**Comment by douxuebuhui** [comment]
> 上面那个链接对应的是B站早期的XML API，弹幕数量上限比网页版上实际显示使用的protobuf API要少。
> 
> 如果想得到目前实际显示的弹幕列表，可以在console里查看 `D` 变量，不过格式可能需要写个脚本转换一下：
> 
> ![image](https://private-user-images.githubusercontent.com/6646473/306628655-2b890a2f-0b8f-4be8-851c-3f11cc3b7375.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTc1ODQsIm5iZiI6MTcwODU5NzI4NCwicGF0aCI6Ii82NjQ2NDczLzMwNjYyODY1NS0yYjg5MGEyZi0wYjhmLTRiZTgtODUxYy0zZjExY2MzYjczNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMTAyMTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTc2MDU4ZmE1MDI2YmIxYTQ4Y2QzZmQ3ZGEwMWU3NTViMWQzNjMxMGIyOTk0YTAyMzE2ZmMzOGFlM2ZhMzM0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Toun-4rK31IX_xR9EB2hHKwUFFGcdWnhxHxc5jvdvl8)

下载的字幕能不能包含字号等信息？比较喜欢合并放大合并功能，现在经过转换变成ass后，只有一种字号了

**Comment by xmcp** [comment]
有字号信息，`p` 属性里面的第三个就是，例如 `<d p="0,5,36,16777215,1290787952,0,95f5c5f3,837810965">` 表示字号是 36px。
