### ISSUE TITLE
屏蔽合并弹幕用户时, 只屏蔽了"被合并到"的唯一用户, 而不是用户集合

### ISSUE THREAD

**Issue by Rocy-June** [xmcp/pakku.js#270]
**是否可以稳定复现：**

是

**复现步骤：**

1. 右键点击被合并的弹幕
2. 点击屏蔽
3. 在"屏蔽设定"中只会增加一条用户id

**预期行为：**

1. 在 **复现步骤** 中的第 3 步, 理应是被合并的所有用户

**实际行为：**

1. 实际上为"被合并者"单条用户被屏蔽

**禁用pakku后bug是否存在：**

1. 功能相关BUG或暂未实现的功能

**禁用其他插件后bug是否存在：**

1. 同上

**B站播放器版本号：**

4.8.5-rc.5479.0-92b399fb

**pakku调试信息：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.10

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0`

**Incognito:** `false`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","_ADVANCED_USER":"on","DANMU_MARK":"suffix","TAOLUS":"","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1697213369257","FLASH_NOTIF":"on","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","REMOVE_SEEK":"off","THRESHOLD":"20","POPUP_BADGE":"percent","TRIM_WIDTH":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"off","WHITELIST":"[]","PROC_TYPE7":"off","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","MAX_COSINE":"60","MODE_ELEVATION":"on","TOOLTIP":"on","AUTO_DISABLE_DANMU":"off","REPRESENTATIVE_PERCENT":"20","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"290360503":{"error":"网络错误","cid":"462721588","details":"undefined\n\nundefined"},"290361043":{"identical":3547,"edit_distance":5880,"pinyin_distance":319,"cosine_distance":178,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":365,"shrink":"","scroll":1,"taolu":25,"total":18807,"onscreen":8883,"maxcombo":648,"maxdispval":759.9763287350506,"error":null,"cid":"462721588","parse_time_ms":1559}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"off","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"20","SCROLL_THRESHOLD":"1200","SHRINK":"off","TAOLUS":"","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1697213369257"}

**Tabs:**

- ID=290360971 status=unloaded `undefined`

- ID=290360258 status=unloaded `https://www.bilibili.com/read/cv18615087/`

- ID=290360261 status=unloaded `undefined`

- ID=290360264 status=unloaded `undefined`

- ID=290360267 status=unloaded `undefined`

- ID=290360270 status=unloaded `undefined`

- ID=290360273 status=unloaded `undefined`

- ID=290360276 status=unloaded `undefined`

- ID=290360279 status=unloaded `undefined`

- ID=290360282 status=unloaded `undefined`

- ID=290360285 status=unloaded `undefined`

- ID=290360288 status=unloaded `undefined`

- ID=290360291 status=unloaded `undefined`

- ID=290360294 status=unloaded `undefined`

- ID=290360297 status=unloaded `https://www.bilibili.com/opus/854140652965855232`

- ID=290360300 status=unloaded `https://www.bilibili.com/opus/854409139977191481`

- ID=290360303 status=unloaded `undefined`

- ID=290360306 status=unloaded `undefined`

- ID=290360513 status=unloaded `https://www.bilibili.com/`

- ID=290360516 status=unloaded `https://www.bilibili.com/anime/?spm_id_from=333.1007.0.0`

- ID=290361043 status=complete `https://www.bilibili.com/bangumi/play/ep445881?from_spmid=666.25.episode.0`

- ID=290361062 status=complete `https://www.bilibili.com/blackboard/webplayer_history.html#html5`

- ID=290360519 status=unloaded `https://www.bilibili.com/video/BV14x4y1y7Wx/?spm_id_from=333.788&vd_source=e8e5133cde2f2cad80d1ec3c91df7a01`

- ID=290360522 status=unloaded `https://www.bilibili.com/bangumi/play/ss4439?from_spmid=666.25.series.0&ab_hit_result=ui_season_selector&pgc_play_new_ui=2`

- ID=290360974 status=unloaded `undefined`

- ID=290360977 status=unloaded `undefined`

- ID=290360965 status=unloaded `undefined`

- ID=290360968 status=unloaded `undefined`

- ID=290360525 status=complete `undefined`

- ID=290361054 status=complete `undefined`

- ID=290361065 status=complete `undefined`

- ID=290361068 status=loading `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,10">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,9">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,8">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,7">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,6">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,5">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,4">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,3"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,2"> 神™·MIDI</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**其他说明：**

功能相关BUG或暂未实现的功能

**Comment by xmcp** [comment]
这是预期现象
