### ISSUE TITLE
开启功能后弹幕全部消失

### ISSUE THREAD

**Issue by moyvxianzhe** [xmcp/pakku.js#275]
**是否可以稳定复现：**

是

**复现步骤：**

1. 正常打开bilibili视频网站
2. 开始播放视频

**预期行为：**

弹幕正常出现，右边弹幕列表有弹幕

**实际行为：**

弹幕全部消失，右边弹幕栏无弹幕

![image](https://github.com/xmcp/pakku.js/assets/149222670/73bb96b0-8040-4405-88b7-fd1954bfdae9)
![image](https://github.com/xmcp/pakku.js/assets/149222670/ea5d8e0c-cf4d-489d-8a33-90cc12ba74eb)

**禁用pakku后bug是否存在：**

禁用后正常

**禁用其他插件后bug是否存在：**

依然存在

**B站播放器版本号：**

4.8.15-17160169

**pakku调试信息：**

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 2024.4.1

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`

**Incognito:** `false`

**Has Session Storage:** `true`

**localStorage:** `{}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/view_result.html?tabid=720680517`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

**Permissions:** `{"origins":["*://*.bilibili.com/*","https://www.bilibili.com/robots.txt?pakku_sandbox"],"permissions":["notifications","storage","declarativeNetRequestWithHostAccess"]}`

**State:** `{"GLOBAL_SWITCH":true,"STATS_720680511":{"combined_cosine_distance":0,"combined_edit_distance":0,"combined_identical":0,"combined_pinyin_distance":0,"deleted_blacklist":404,"download_time_ms":409,"ignored_script":0,"ignored_type":0,"ignored_whitelist":0,"modified_enlarge":0,"modified_scroll":0,"modified_shrink":0,"num_max_combo":0,"num_max_dispval":0,"num_onscreen_danmu":0,"num_taolu_matched":0,"num_total_danmu":404,"parse_time_ms":4,"type":"done"},"STATS_720680517":{"combined_cosine_distance":0,"combined_edit_distance":0,"combined_identical":0,"combined_pinyin_distance":0,"deleted_blacklist":3155,"download_time_ms":422,"ignored_script":0,"ignored_type":0,"ignored_whitelist":0,"modified_enlarge":0,"modified_scroll":0,"modified_shrink":0,"num_max_combo":0,"num_max_dispval":0,"num_onscreen_danmu":0,"num_taolu_matched":0,"num_total_danmu":3155,"parse_time_ms":19,"type":"done"},"STATS_720680556":{"combined_cosine_distance":0,"combined_edit_distance":0,"combined_identical":0,"combined_pinyin_distance":0,"deleted_blacklist":411,"download_time_ms":604,"ignored_script":0,"ignored_type":0,"ignored_whitelist":0,"modified_enlarge":0,"modified_scroll":0,"modified_shrink":0,"num_max_combo":0,"num_max_dispval":0,"num_onscreen_danmu":0,"num_taolu_matched":0,"num_total_danmu":411,"parse_time_ms":2,"type":"done"},"STATS_720680559":{"combined_cosine_distance":0,"combined_edit_distance":0,"combined_identical":0,"combined_pinyin_distance":0,"deleted_blacklist":27,"download_time_ms":850,"ignored_script":0,"ignored_type":0,"ignored_whitelist":0,"modified_enlarge":0,"modified_scroll":0,"modified_shrink":0,"num_max_combo":0,"num_max_dispval":0,"num_onscreen_danmu":0,"num_taolu_matched":0,"num_total_danmu":27,"parse_time_ms":5,"type":"done"},"_INITIALIZED":true}`

**Tabs:**

- ID=720680458 status=complete `https://www.bilibili.com/`

- ID=720680559 status=complete `https://www.bilibili.com/video/BV1gt421J7hm/?spm_id_from=333.1007.tianma.1-3-3.click&vd_source=5631214b52aa84ad0fc6eb4986d05cc1`

- ID=720680565 status=complete `https://www.bilibili.com/blackboard/webplayer_history.html#html5`

- ID=720680556 status=complete `https://www.bilibili.com/video/BV18A4m1w7Zc/?spm_id_from=333.1007.tianma.1-2-2.click&vd_source=5631214b52aa84ad0fc6eb4986d05cc1`

- ID=720680551 status=complete `https://live.bilibili.com/5050?live_from=76001`

- ID=720680517 status=complete `https://www.bilibili.com/video/BV1ix4y1Y7yP/?spm_id_from=333.1007.tianma.1-1-1.click&vd_source=5631214b52aa84ad0fc6eb4986d05cc1`

- ID=720680530 status=complete `undefined`

- ID=720680511 status=complete `https://www.bilibili.com/video/BV18A4m1w7Zc/?spm_id_from=333.1007.tianma.1-2-2.click&vd_source=5631214b52aa84ad0fc6eb4986d05cc1`

- ID=720680527 status=complete `undefined`

- ID=720680574 status=loading `undefined`

- ID=720680562 status=complete `undefined`

- ID=720680545 status=complete `undefined`

- ID=720680540 status=complete `undefined`

**Config:** `{"_LAST_UPDATE_TIME":0,"_CONFIG_VER":1,"ADVANCED_USER":false,"THRESHOLD":20,"MAX_DIST":5,"MAX_COSINE":45,"TRIM_PINYIN":true,"TRIM_ENDING":true,"TRIM_SPACE":true,"TRIM_WIDTH":true,"FORCELIST":[["^23{2,}$","23333"],["^6{3,}$","66666"]],"WHITELIST":[],"CROSS_MODE":true,"PROC_TYPE7":true,"PROC_TYPE4":true,"PROC_POOL1":false,"DANMU_MARK":"prefix","MARK_THRESHOLD":1,"DANMU_SUBSCRIPT":true,"ENLARGE":true,"SHRINK":false,"MODE_ELEVATION":true,"REPRESENTATIVE_PERCENT":20,"TOOLTIP":true,"TOOLTIP_KEYBINDING":true,"AUTO_DISABLE_DANMU":false,"AUTO_DANMU_LIST":false,"FLUCTLIGHT":false,"BREAK_UPDATE":false,"SCROLL_THRESHOLD":1200,"USERSCRIPT":null,"POPUP_BADGE":"percent","COMBINE_THREADS":3}`

**Worker is Simulated:** `false`

**Exception:** `error log is working ("Error: error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:5451")`

**Exception in Promise:** `async error log is working ("Error: async error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:5408\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:5448")`
</details>

**其他说明：**

![image](https://github.com/xmcp/pakku.js/assets/149222670/c2514085-209a-4bea-bff5-a0d03620dad8)
![image](https://github.com/xmcp/pakku.js/assets/149222670/1622df26-20f6-4170-a72e-88a5e33a0d05)

**Comment by xmcp** [comment]
这些弹幕均命中了你设置的黑名单，请检查B站播放器的黑名单设置

**Comment by moyvxianzhe** [comment]
如果是黑名单问题 那无论我是否开启插件应该都是无弹幕吧，但现在是开插件无弹幕，关了就正常，还是说过滤器自己有个黑名单吗

**Comment by xmcp** [comment]
你看下播放器的黑名单是怎么设置的

**Comment by moyvxianzhe** [comment]
![image](https://github.com/xmcp/pakku.js/assets/149222670/2bc80fb5-0942-4a5e-b768-412d6615bc4e)
![image](https://github.com/xmcp/pakku.js/assets/149222670/ef2d9dbf-7ee9-48dd-9b3b-df663792cd21)
![image](https://github.com/xmcp/pakku.js/assets/149222670/84b56e6a-5a02-4f20-9c63-53bb5c38feca)
![image](https://github.com/xmcp/pakku.js/assets/149222670/ec0dc70e-8e97-4ef7-b434-26c006417523)
![image](https://github.com/xmcp/pakku.js/assets/149222670/c1044625-f85b-4c5d-a5e3-fcc38f5c4946)
我是在视频右边弹幕列表上面看的，还是说在哪里看呢？

**Comment by xmcp** [comment]
有点怪。你在视频页面按F12打开开发者工具，点击 console，输入 `localStorage['bpx_player_profile']` 看看它显示什么

![image](https://github.com/xmcp/pakku.js/assets/6646473/4ca9bd98-0e78-406f-a478-0fc4949002af)

**Comment by xmcp** [comment]
好像是播放器的屏蔽列表里面有个怪东西导致的。我修一下

**Comment by xmcp** [comment]
v2024.4.3应该解决了此问题，请等待浏览器自动更新或者 [下载CRX覆盖安装](https://s.xmcp.ltd/pakkujs/?update_banner)

**Comment by moyvxianzhe** [comment]
更新后好了，谢谢大佬修复。
