### ISSUE TITLE
貌似被劫持了还是夹带私活？打开设置主界面会跳转扭腰奶儿子的网页

### ISSUE THREAD

**Issue by wearfa** [xmcp/pakku.js#277]
### 是否可以稳定复现

everytime

### 复现步骤

如题 扭腰奶儿的网页
![QQ截图20240414171744](https://github.com/xmcp/pakku.js/assets/104263147/1e6f11d6-f2b2-479e-8b64-292f1850ebd0)

### 预期行为

打开插件节目会跳转网页

### 实际行为

![QQ截图20240414171744](https://github.com/xmcp/pakku.js/assets/104263147/7c6cbd66-f962-47a8-8071-ccb254962166)

### 禁用 pakku 后 bug 是否存在

1

### 是否与其他插件有关

1

### B 站播放器版本号

10.0.4

### pakku 调试信息

1

### 补充说明

1

**Comment by xmcp** [comment]
pakku从未上架360浏览器市场，这是第三方上传的，而且版本十分老旧，已不兼容最新的B站播放器。

本人已邮件联系360客服请求下架处理。请从 https://s.xmcp.ltd/pakkujs/ 安装最新版。
