### ISSUE TITLE
pakku突然有一天就不工作了，后续一直如此。

### ISSUE THREAD

**Issue by yyqno1** [xmcp/pakku.js#278]
### 是否可以稳定复现

可以

### 复现步骤

打开B站任一视频，都可复现。

### 预期行为

应该出现显示过滤弹幕的百分比。

### 实际行为

打开B站任一视频，然后点击插件，均显示“本页面没有发现B站播放器”。

### 禁用 pakku 后 bug 是否存在

否

### 是否与其他插件有关

否

### B 站播放器版本号

4.8.15-17160169

### pakku 调试信息

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 2024.4.4

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`

**Incognito:** `false`

**Has Session Storage:** `true`

**localStorage:** `{}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Permissions:** `{"origins":["*://*.bilibili.com/*","https://www.bilibili.com/robots.txt?pakku_sandbox"],"permissions":["contextMenus","notifications","storage","declarativeNetRequestWithHostAccess"]}`

**State:** `{"GLOBAL_SWITCH":true,"_INITIALIZED":true}`

**Config:** `{"_LAST_UPDATE_TIME":0,"_CONFIG_VER":1,"ADVANCED_USER":false,"THRESHOLD":20,"MAX_DIST":5,"MAX_COSINE":45,"TRIM_PINYIN":true,"TRIM_ENDING":true,"TRIM_SPACE":true,"TRIM_WIDTH":true,"FORCELIST":[["^23{2,}$","23333"],["^6{3,}$","66666"]],"WHITELIST":[],"CROSS_MODE":true,"PROC_TYPE7":true,"PROC_TYPE4":true,"PROC_POOL1":false,"DANMU_MARK":"prefix","MARK_THRESHOLD":1,"DANMU_SUBSCRIPT":true,"ENLARGE":true,"SHRINK":false,"MODE_ELEVATION":true,"REPRESENTATIVE_PERCENT":20,"TOOLTIP":true,"TOOLTIP_KEYBINDING":true,"AUTO_DISABLE_DANMU":false,"AUTO_DANMU_LIST":false,"FLUCTLIGHT":false,"BREAK_UPDATE":false,"SCROLL_THRESHOLD":1200,"USERSCRIPT":null,"POPUP_BADGE":"percent","COMBINE_THREADS":3}`

**Tabs:**

- ID=2 status=complete `undefined`

- ID=85 status=complete `https://www.bilibili.com/`

- ID=136 status=complete `https://www.bilibili.com/video/BV13T421m7Pq/?spm_id_from=333.1007.tianma.1-3-3.click&vd_source=70640985f50d2b71657c5e0505717503`

- ID=139 status=complete `undefined`

- ID=146 status=complete `undefined`

- ID=149 status=loading `undefined`

**Worker is Simulated:** `false`

**Exception:** `error log is working ("Error: error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:5422")`

**Exception in Promise:** `async error log is working ("Error: async error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:5379\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:5419")`
</details>

### 补充说明

平时打开B站视频播放，pakku都是正常工作（与BewlyBewly插件同时在用），突然有一天（大概一周前，具体记不清了）就无法工作了。我重新安装后不行，禁用掉BewlyBewly插件也不行，特此说明。

**Comment by xmcp** [comment]
请在视频页面按F12打开开发者工具，点击console，截图展示一下完整输出

![image](https://github.com/xmcp/pakku.js/assets/6646473/7a3e8ed1-67b6-4967-8843-c5e049f55822)

**Comment by xmcp** [comment]
拿 Chromium 103 复现了，应该是 [Chrome 111 以下的兼容问题](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#browser_compatibility)。我看一下。

**Comment by xmcp** [comment]
2024.4.6版本将Chrome兼容性从111提高到了99。请更新pakku或者直接更新chrome。

**Comment by yyqno1** [comment]
更新后好了，谢谢大佬如此快速的修复。

**Comment by xmcp** [comment]
> 扩展版本2024.4.6，edge版本123.0.2420.97 (正式版本) (64 位)，遇到了一样的问题

@BladeandSoulLyn 我这里是正常的，如果升级到最新版（目前是2024.4.7）还有问题请单独开一个bug report。
