### ISSUE TITLE
Firefox 试了下弹幕较多的re:0第18集，默认设置会导致弹幕加载失败

### ISSUE THREAD

**Issue by AndurilLi** [xmcp/pakku.js#28]
[B站链接](https://bangumi.bilibili.com/anime/3461/play#89192)
图标上进度大概会停在23%的样子，关闭刷新则可以正常加载

**Comment by xmcp** [comment]
看了一下，应该是 Content Script 没设置 `"all_frames": true` 的锅，所以用 iframe 播放器的 bangumi 就挂掉了。
f9f031efe155593d32d98ea03d5cabf7d049f40c (v7.1.2) 已经修复了。

你看我修 bug 这么迅速，要不要考虑 [在 AMO 上给个五星好评](https://addons.mozilla.org/zh-CN/firefox/addon/pakkujs/) 啊 :rofl:
