### ISSUE TITLE
希望恢复原本的弹幕屏蔽正则的添加功能

### ISSUE THREAD

**Issue by yehuailin** [xmcp/pakku.js#280]

**Comment by xmcp** [comment]
可以利用 [用户脚本](https://github.com/xmcp/pakku.js/tree/master/userscript_docs) 等功能实现正则表达式屏蔽。不过确实不建议添加过多屏蔽规则，如果多到播放器都不让导入的话，可能会有性能问题。

**Comment by yehuailin** [comment]
> 现正则表达式屏蔽。不过确实不建议添加过多屏蔽规则，如果多到播放器都不让导

手动添加了718条屏蔽正则在b站自带的屏蔽设置里，好像运行的挺正常的，和旧版pakku进行对比，命中黑名单的屏蔽弹幕数是相同的，性能不太确定，体感上没有太明显的迟缓。

**Comment by xmcp** [comment]
刚更新的2024.7.1版本将从网页的 `localStorage` 读取额外的用户脚本和屏蔽词。因此如果你有大量的屏蔽词难以导入B站播放器，可以存储在 www.bilibili.com 域的 `localStorage['pakku_extra_blacklist']` 中，格式与B站播放器导出的 JSON 格式相同。例如，在视频页面的 console 中执行以下代码：

```javascript
localStorage['pakku_extra_blacklist'] = JSON.stringify([{type: 1, filter: '^.{1,6}[天时点分钟秒]前', opened: true, id: 0}]);
```

**Comment by yehuailin** [comment]
> 刚更新的2024.7.1版本将从网页的 `localStorage` 读取额外的用户脚本和屏蔽词。因此如果你有大量的屏蔽词难以导入B站播放器，可以存储在 [www.bilibili.com](http://www.bilibili.com) 域的 `localStorage['pakku_extra_blacklist']` 中，格式与B站播放器导出的 JSON 格式相同。例如，在视频页面的 console 中执行以下代码：
> 
> ```js
> localStorage['pakku_extra_blacklist'] = JSON.stringify([{type: 1, filter: '^.{1,6}[天时点分钟秒]前', opened: true, id: 0}]);
> ```

在不知道误删了啥的情况下（可能是edge的本地缓存文件），我手动添加到b站的所有屏蔽正则全部消失了，云同步也是空的，人已经麻了，现在用回自带黑名单功能的10.2.10版本的pakku了。您说的这个从网页控制台操作的办法确实不懂...
