### ISSUE TITLE
扩展不工作，提示本页面没有发现B站播放器

### ISSUE THREAD

**Issue by BladeandSoulLyn** [xmcp/pakku.js#281]
### 是否可以稳定复现

是

### 复现步骤

大约是两三天前出现此问题，进入任何视频均提示本页面没有发现B站播放器。
如果卸载此扩展再从chrome商店重新安装，则这次浏览期间扩展可正常工作；
但如果关掉浏览器的话，下次启动浏览器后访问B站时问题复现。

### 预期行为

扩展能够合并和过滤弹幕

### 实际行为

任何视频均提示本页面没有发现B站播放器

### 禁用 pakku 后 bug 是否存在

否

### 是否与其他插件有关

否。仅启用 pakku时，亦能用上述步骤复现。

### B 站播放器版本号

4.8.17-806fa473

### pakku 调试信息

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 2024.4.7

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0`

**Incognito:** `false`

**Has Session Storage:** `true`

**localStorage:** `{}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Permissions:** `{"origins":["*://*.bilibili.com/*","https://www.bilibili.com/robots.txt?pakku_sandbox"],"permissions":["contextMenus","notifications","storage","scripting","declarativeNetRequestWithHostAccess"]}`

**State:** `{"GLOBAL_SWITCH":true,"_INITIALIZED":true}`

**Config:** `{"_LAST_UPDATE_TIME":0,"_CONFIG_VER":1,"ADVANCED_USER":false,"THRESHOLD":20,"MAX_DIST":5,"MAX_COSINE":45,"TRIM_PINYIN":true,"TRIM_ENDING":true,"TRIM_SPACE":true,"TRIM_WIDTH":true,"FORCELIST":[["^23{2,}$","23333"],["^6{3,}$","66666"]],"WHITELIST":[],"CROSS_MODE":true,"PROC_TYPE7":true,"PROC_TYPE4":true,"PROC_POOL1":false,"DANMU_MARK":"prefix","MARK_THRESHOLD":1,"DANMU_SUBSCRIPT":true,"ENLARGE":true,"SHRINK":false,"MODE_ELEVATION":true,"REPRESENTATIVE_PERCENT":20,"TOOLTIP":true,"TOOLTIP_KEYBINDING":true,"AUTO_DISABLE_DANMU":false,"AUTO_DANMU_LIST":false,"FLUCTLIGHT":false,"BREAK_UPDATE":false,"SCROLL_THRESHOLD":1200,"USERSCRIPT":null,"POPUP_BADGE":"percent","COMBINE_THREADS":3}`

**Tabs:**

- ID=1182699436 status=complete `https://www.bilibili.com/video/BV1ct421N7xA/?vd_source=804f1b7c36f42030e39d3aebfccc9583`

- ID=1182699495 status=complete `undefined`

- ID=1182699498 status=loading `undefined`

**Worker is Simulated:** `false`

**Exception:** `error log is working ("Error: error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:5422")`

**Exception in Promise:** `async error log is working ("Error: async error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:5379\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:5419")`
</details>

### 补充说明

edge版本号为123.0.2420.97 (正式版本) (64 位)
图1是正常工作时的情形；图2是重启浏览器后打开同一个视频的情形。
<img width="773" alt="屏幕截图 2024-04-18 222943" src="https://github.com/xmcp/pakku.js/assets/93634398/fdd1fe37-bca8-4d77-87eb-f34883aff998">
![屏幕截图 2024-04-18 223133](https://github.com/xmcp/pakku.js/assets/93634398/98c0b3ba-9eea-478b-8526-ad98e5c62ef9)

**Comment by BladeandSoulLyn** [comment]
补充：目前发现edge商店里的10.2.10版本没有此问题，重启浏览器后扩展也能正常工作，所以暂时转用edge商店里的版本。
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 10.2.10

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0`

**Incognito:** `false`

**localStorage:** `{"_ADVANCED_USER":"off","MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","DANMU_MARK":"prefix","BLACKLIST":"[]","_LAST_UPDATE_TIME":"0","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","THRESHOLD":"20","TRIM_WIDTH":"on","POPUP_BADGE":"percent","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","WHITELIST":"[]","CLOUD_SYNC":"off","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"on","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","MAX_COSINE":"60","ENLARGE":"on","MODE_ELEVATION":"on","TOOLTIP":"on","REPRESENTATIVE_PERCENT":"0","AUTO_DISABLE_DANMU":"off","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/core/background.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html#show-advanced`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"1182700921":{"identical":10,"edit_distance":35,"pinyin_distance":3,"cosine_distance":0,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":1,"shrink":"","scroll":0,"taolu":1,"total":457,"onscreen":409,"maxcombo":8,"maxdispval":114.09098626693752,"error":null,"cid":"1511652112","parse_time_ms":9},"1182700924":{"identical":11,"edit_distance":35,"pinyin_distance":4,"cosine_distance":0,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":1,"shrink":"","scroll":0,"taolu":1,"total":459,"onscreen":409,"maxcombo":8,"maxdispval":112.35893545936865,"error":null,"cid":"1511652112","parse_time_ms":7},"1182700941":{"identical":15,"edit_distance":40,"pinyin_distance":3,"cosine_distance":0,"blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":2,"shrink":"","scroll":0,"taolu":0,"total":480,"onscreen":422,"maxcombo":8,"maxdispval":74.62893636413327,"error":null,"cid":"1511652112","parse_time_ms":9}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=1182700845 status=complete `https://t.bilibili.com/`

- ID=1182700941 status=complete `https://www.bilibili.com/video/BV17q421F7hK/?vd_source=804f1b7c36f42030e39d3aebfccc9583`

- ID=1182700934 status=complete `undefined`

- ID=1182700948 status=complete `undefined`

- ID=1182700957 status=loading `undefined`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLUCTLIGHT":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"off","THRESHOLD":"20","TOOLTIP":"on","TOOLTIP_KEYBINDING":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"0"}

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.33300,1,25,16777215,1712344580,0,91d6b7d0,1554017991417578752,10">test2</d><d p="0.33300,1,25,16777215,1712344571,0,91d6b7d0,1554017916020604672,10">test1</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,9">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,8">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,7">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,6">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,5">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,4">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,3">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,2"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,1"> 神™·MIDI</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.33300,1,25,16777215,1712344580,0,91d6b7d0,1554017991417578752,10">test2</d><d p="0.33300,1,25,16777215,1712344571,0,91d6b7d0,1554017916020604672,10">test1</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392,9">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586,8">]]][[[</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090,7">]][[</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637,6">好强啊</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713,5">你们都好强啊~~~ orz orz orz orz</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737,4">Ocarina的声音好奇怪</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497,3">   FFT大法好（13行FFT路过）</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017,2"> FFT大法好（13行FFT路过）</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725,1"> 神™·MIDI</d></i>`


**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.js` :: 2 :: 2059
</details>

**Comment by BladeandSoulLyn** [comment]
@xmcp 你好，感谢回复！我测试的时候edge的版本更新至了124.0.2478.51 (正式版本) (64 位)。现回报测试结果如下：
1.重装扩展，确认可用的情况下更改设置，运行命令并展开可以看到正常返回的内容：
![屏幕截图 2024-04-19 023025](https://github.com/xmcp/pakku.js/assets/93634398/2f408100-5362-4e50-b97d-504d1c718eae)
2.重启浏览器，确认扩展不可用。进入设置界面，发现刚才更改的设置是正常保留的，并未被重置。此时运行命令发现返回数组为空：
![屏幕截图 2024-04-19 022712](https://github.com/xmcp/pakku.js/assets/93634398/386900da-323d-438b-9abc-ddefdf480b27)
关于设置同步和自动清理的功能，我尝试关闭了edge://settings/profiles/sync里的扩展同步选项、重新同步和重置同步选项以及edge://settings/reset的还原默认设置，但问题依旧。
不过，当我尝试在edge://settings/profiles里新建一个用户profile而不登录微软账号的情况下测试时，发现问题解决了（重启后运行命令也能正常返回内容，扩展正常生效）。不知道是什么原因造成的在我自己的profile里就不生效的呢...

**Comment by xmcp** [comment]
那现在情况很清晰了，就是edge浏览器在你这个profile下每次重启之后就会丢失扩展程序通过 `chrome.scripting` API 注册的 content script，导致pakku出现问题。

edge浏览器这个行为 [肯定是错误的](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/scripting/RegisteredContentScript#persistacrosssessions)，可能是什么数据文件损坏了导致的，可以试试重置设置或者重装edge浏览器。

虽然这个问题的本质是edge浏览器不对劲，但我感觉微软短时间内也不会解决它（尤其是它难以复现，导致就算报告了bug也大概率没用）。pakku在后续更新edge版本时将临时应对一下，每次浏览器启动后都重新尝试注册 content script。

如果你重装浏览器后也无法解决此问题，可以暂时先使用edge商店的旧版。
