### ISSUE TITLE
此插件与B站自带的"硬核会员弹幕模式"冲突

### ISSUE THREAD

**Issue by HumanicP** [xmcp/pakku.js#282]
### 是否可以稳定复现

重装插件后会BUG短暂消失，最终还是会出现

### 复现步骤

1. 确保Pakku休息中：打开一个视频，然后切换Pakku至工作中，刷新网页
2. 点击弹幕设置，点高级设置，发现“硬核会员弹幕模式（Beta)"选项消失
视频压缩过，orz

https://github.com/xmcp/pakku.js/assets/118138508/cf8f5846-aaa9-4cc0-855f-567342f7403e

### 预期行为

”硬核会员弹幕模式（Beta)"选项 应该存在

### 实际行为

“硬核会员弹幕模式（Beta)"选项 消失
![1714068076893](https://github.com/xmcp/pakku.js/assets/118138508/057b8142-d72c-425c-9995-fcfd3a7231ad)

### 禁用 pakku 后 bug 是否存在

禁用 or 切换休息模式后bug消失

### 是否与其他插件有关

无关

### B 站播放器版本号

4.8.19-8771af2d

### pakku 调试信息

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 2024.5.1

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0`

**Incognito:** `false`

**Has Session Storage:** `true`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"true","_ADVANCED_USER":"off","DANMU_MARK":"prefix","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1714053614661","ADVANCED_USER":"false","SHRINK":"false","DROP_THRESHOLD":"0","TRIM_SPACE":"true","MAX_DIST":"5","USERSCRIPT":"null","TRIM_ENDING":"true","AUTO_DANMU_LIST":"false","THRESHOLD":"20","TRIM_WIDTH":"true","POPUP_BADGE":"percent","_CONFIG_VER":"2","FLUCTLIGHT":"false","FORCELIST":"^23{2,}$,233...,^6{3,}$,666...,^[fF]+$,FFF...,^[hH]+$,hhh...","CLOUD_SYNC":"on","WHITELIST":"","PROC_TYPE7":"true","PROC_POOL1":"false","CROSS_MODE":"true","READ_PLAYER_BLACKLIST":"true","HIDE_THRESHOLD":"0","BREAK_UPDATE":"false","COMBINE_THREADS":"3","DANMU_SUBSCRIPT":"true","PROC_TYPE4":"true","TRIM_PINYIN":"true","ENLARGE":"true","MAX_COSINE":"60","MODE_ELEVATION":"true","TOOLTIP":"true","AUTO_DISABLE_DANMU":"false","REPRESENTATIVE_PERCENT":"0","SHRINK_THRESHOLD":"0","SCROLL_THRESHOLD":"1200"}`

**Views:**

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/options.html`

- `chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/page/troubleshooting.html`

**Permissions:** `{"origins":["*://*.bilibili.com/*","https://www.bilibili.com/robots.txt?pakku_sandbox"],"permissions":["contextMenus","notifications","storage","scripting","declarativeNetRequestWithHostAccess"]}`

**Content Scripts:** `[{"allFrames":true,"css":["generated/injected.css"],"excludeMatches":["https://www.bilibili.com/robots.txt?pakku_sandbox"],"id":"pakku-ajax","js":["generated/xhr_hook.js"],"matchOriginAsFallback":false,"matches":["*://*.bilibili.com/*"],"persistAcrossSessions":true,"runAt":"document_start","world":"MAIN"}]`

**DNR Rules:** `[]`

**State:** `{"GLOBAL_SWITCH":true,"STATS_1056181862":{"combined_cosine_distance":37,"combined_edit_distance":838,"combined_identical":408,"combined_pinyin_distance":15,"deleted_blacklist":93,"deleted_blacklist_each":{" /[1-9][0-9]{4,8}/":7," /^.*大学$/":6," /^[哈呵哼6xswlawsl]+嗝?$/":75," /【0-9】(秒|分钟|小时|时|天)【热乎|热热|还能吃|刚刚|我出息了】/":5},"deleted_dispval":0,"download_time_ms":1059,"ignored_script":0,"ignored_type":0,"ignored_whitelist":0,"modified_enlarge":70,"modified_scroll":0,"modified_shrink":0,"num_max_combo":30,"num_max_dispval":0,"num_onscreen_danmu":3922,"num_taolu_matched":1,"num_total_danmu":5305,"parse_time_ms":184,"type":"done"},"_INITIALIZED":true}`

**Config:** `{"ADVANCED_USER":true,"AUTO_DANMU_LIST":true,"AUTO_DISABLE_DANMU":false,"BLACKLIST":"[]","BREAK_UPDATE":false,"CLOUD_SYNC":"on","COMBINE_THREADS":3,"CROSS_MODE":true,"DANMU_MARK":"prefix","DANMU_SUBSCRIPT":true,"DROP_THRESHOLD":0,"ENLARGE":true,"FLUCTLIGHT":false,"FORCELIST":[["^23{2,}$","233..."],["^6{3,}$","666..."],["^[fF]+$","FFF..."],["^[hH]+$","hhh..."]],"HIDE_THRESHOLD":"0","MARK_THRESHOLD":1,"MAX_COSINE":60,"MAX_DIST":5,"MODE_ELEVATION":true,"POPUP_BADGE":"percent","PROC_POOL1":false,"PROC_TYPE4":true,"PROC_TYPE7":true,"READ_PLAYER_BLACKLIST":true,"REPRESENTATIVE_PERCENT":0,"SCROLL_THRESHOLD":1200,"SHRINK":false,"SHRINK_THRESHOLD":0,"THRESHOLD":20,"TOOLTIP":true,"TOOLTIP_KEYBINDING":true,"TRIM_ENDING":true,"TRIM_PINYIN":true,"TRIM_SPACE":true,"TRIM_WIDTH":true,"USERSCRIPT":null,"WHITELIST":[],"_ADVANCED_USER":"off","_CONFIG_VER":2,"_LAST_UPDATE_TIME":1714066725869}`

**Tabs:**

- ID=1056181838 status=complete `undefined`

- ID=1056181862 status=complete `https://www.bilibili.com/video/BV1kt421n7o8/?vd_source=489072d4b95c6f1a6d889e5129fd13a5`

- ID=1056181776 status=complete `undefined`

- ID=1056181876 status=complete `undefined`

- ID=1056181879 status=loading `undefined`

**Worker is Simulated:** `false`

**Exception:** `error log is working ("Error: error log is working\n    at chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/generated/troubleshooting.js:1:5966")`

**Exception in Promise:** `async error log is working ("Error: async error log is working\n    at chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/generated/troubleshooting.js:1:5923\n    at chrome-extension://lnfcfeidnipnphibahlkdhalpkpmccoc/generated/troubleshooting.js:1:5963")`
</details>

### 补充说明

N/A

**Comment by xmcp** [comment]
我自己不是硬核会员，所以看不到这个选项，也不知道为什么开启 pakku 之后此功能会消失。按理说 pakku 只是遵循B站的格式修改弹幕内容，没有触及播放器设置，应该不会造成这种情况。

当我能复现此问题之后会考虑修复。

不过目前B站播放器的所谓 “硬核会员弹幕模式” 在实现上只是把弹幕屏蔽等级调整为 11，如下图所示：
![image](https://github.com/xmcp/pakku.js/assets/6646473/fddb568e-c677-4df6-8800-72897da45bf3)

因此把播放器的云屏蔽等级拉到 10 即可起到和此功能大差不差的效果。也可以利用 [pakku 的用户脚本功能](https://github.com/xmcp/pakku.js/blob/master/userscript_docs/README.md) 筛选 weight 为 11 的弹幕来 1:1 复刻此功能。

根据我的观察来看，将屏蔽等级调整到 10 或者 11 会错过太多有价值的弹幕，因此并不建议这样做。如果只是感觉有时弹幕密度过高，可以考虑将 pakku 的 “自动弹幕优选” 功能拉到强力档位。

**Comment by xmcp** [comment]
噢找到问题了，是pakku在预加载请求的时候没带上cookie导致丢失了个人设置。

此问题将在下个版本修复，不过依然不建议在大多数视频上打开硬核会员弹幕模式。

**Comment by HumanicP** [comment]
好，谢了
