### ISSUE TITLE
长时间放置标签页在后台是否会导致内存泄漏？

### ISSUE THREAD

**Issue by lingsamuel** [xmcp/pakku.js#284]
今天一下午不在电脑前，发现浏览器把内存吃满了
![(`T1GI676F386IG`{ QC 4](https://github.com/xmcp/pakku.js/assets/14567045/9ac89309-3e38-4549-b19d-92aae71d795d)

打开浏览器任务管理器发现每个哔哩哔哩标签页都吃了1G多的内存
![KMGS7UZ55J0PJ}(8}B49 46](https://github.com/xmcp/pakku.js/assets/14567045/8c761d91-421e-444e-9ca7-af65150463af)

之前没有发现这个现象，最近的变更只有把pakku不能工作的问题整好了。
是否有可能是长时间放置在后台导致的？有没有什么验证方法呢？

**Comment by xmcp** [comment]
F12里的memory工具可以看内存占用。用heap snapshot看当前内存，或者打开allocation sampling挂机一小时看看谁在分配内存。我有点怀疑是B站的PCDN导致的，可以试试把pakku禁用之后看是否还泄漏内存。

![image](https://github.com/xmcp/pakku.js/assets/6646473/eeed804a-4889-4dbb-9563-06c7acc48f8d)
