### ISSUE TITLE
EDGE浏览器中一直弹幕加载中

### ISSUE THREAD

**Issue by HatsukiH** [xmcp/pakku.js#285]
### 是否可以稳定复现

每次都出现

### 复现步骤

不开启其他插件的情况下, 无法显示弹幕, 弹幕栏一直是加载中
![image](https://github.com/xmcp/pakku.js/assets/99108047/ba189ceb-fe1f-4397-a29f-9eaa65097553)

### 预期行为

有弹幕出现

### 实际行为

弹幕栏一直加载弹幕中

### 禁用 pakku 后 bug 是否存在

禁用后弹幕正常

### 是否与其他插件有关

关闭其他插件后仍然如此

### B 站播放器版本号

4.8.19-8771af2d

### pakku 调试信息

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 2024.5.3

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0`

**Incognito:** `false`

**Has Session Storage:** `true`

**localStorage:** `{}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html#show-advanced`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/view_result.html?tabid=2086235774`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html#threshold`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Permissions:** `{"origins":["*://*.bilibili.com/*","https://www.bilibili.com/robots.txt?pakku_sandbox"],"permissions":["contextMenus","notifications","storage","scripting","declarativeNetRequestWithHostAccess"]}`

**Content Scripts:** `[{"allFrames":true,"css":["generated/injected.css"],"excludeMatches":["https://www.bilibili.com/robots.txt?pakku_sandbox"],"id":"pakku-ajax","js":["generated/xhr_hook.js"],"matchOriginAsFallback":false,"matches":["*://*.bilibili.com/*"],"persistAcrossSessions":true,"runAt":"document_start","world":"MAIN"}]`

**DNR Rules:** `[]`

**State:** `{"GLOBAL_SWITCH":true,"STATS_2086235774":{"combined_cosine_distance":0,"combined_edit_distance":3,"combined_identical":6,"combined_pinyin_distance":0,"deleted_blacklist":0,"deleted_blacklist_each":{},"deleted_dispval":0,"download_time_ms":4,"ignored_script":0,"ignored_type":0,"ignored_whitelist":0,"modified_enlarge":1,"modified_scroll":0,"modified_shrink":0,"num_max_combo":6,"num_max_dispval":13.491710209302887,"num_onscreen_danmu":37,"num_taolu_matched":0,"num_total_danmu":46,"parse_time_ms":1202,"type":"done"},"_INITIALIZED":true}`

**Tabs:**

- ID=2086235680 status=complete `undefined`

- ID=2086235690 status=complete `undefined`

- ID=2086235695 status=complete `undefined`

- ID=2086235696 status=complete `undefined`

- ID=2086235791 status=complete `undefined`

- ID=2086235799 status=complete `undefined`

- ID=2086235803 status=complete `undefined`

- ID=2086235806 status=complete `undefined`

- ID=2086235779 status=complete `undefined`

- ID=2086235769 status=complete `https://space.bilibili.com/1072544514/video?tid=0&pn=1&keyword=&order=pubdate`

- ID=2086235774 status=complete `https://www.bilibili.com/video/BV1SJ4m157K2/?p=12&vd_source=9afcbbebf2c88251ad0dbcc69157cc66`

- ID=2086235816 status=complete `undefined`

- ID=2086235819 status=loading `undefined`

- ID=2086235813 status=complete `undefined`

- ID=2086235701 status=complete `undefined`

- ID=2086235708 status=complete `undefined`

- ID=2086235788 status=complete `undefined`

**Config:** `{"_LAST_UPDATE_TIME":11714631176984,"_CONFIG_VER":2,"ADVANCED_USER":true,"THRESHOLD":20,"MAX_DIST":5,"MAX_COSINE":45,"TRIM_PINYIN":true,"TRIM_ENDING":true,"TRIM_SPACE":true,"TRIM_WIDTH":true,"FORCELIST":[["^23{2,}$","23333"],["^6{3,}$","66666"]],"WHITELIST":[],"CROSS_MODE":true,"PROC_TYPE7":true,"PROC_TYPE4":true,"PROC_POOL1":false,"DANMU_MARK":"prefix","MARK_THRESHOLD":1,"DANMU_SUBSCRIPT":true,"ENLARGE":true,"SHRINK_THRESHOLD":70,"DROP_THRESHOLD":240,"MODE_ELEVATION":true,"REPRESENTATIVE_PERCENT":20,"TOOLTIP":true,"TOOLTIP_KEYBINDING":true,"AUTO_DISABLE_DANMU":false,"AUTO_DANMU_LIST":false,"FLUCTLIGHT":false,"BREAK_UPDATE":false,"SCROLL_THRESHOLD":1200,"USERSCRIPT":null,"POPUP_BADGE":"percent","COMBINE_THREADS":3,"READ_PLAYER_BLACKLIST":true}`

**Worker is Simulated:** `false`

**Exception:** `error log is working ("Error: error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:6453")`

**Exception in Promise:** `async error log is working ("Error: async error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:6410\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:6450")`
</details>

![image](https://github.com/xmcp/pakku.js/assets/99108047/dd937a15-5dc9-44e7-8430-66df8ea4f62a)

### 补充说明

chrome浏览器使用正常

**Comment by HatsukiH** [comment]
![image](https://github.com/xmcp/pakku.js/assets/99108047/82d976ca-3425-4a45-9f49-37ed79242bd6)

**Comment by xmcp** [comment]
console里面的requests.js和iframe.html是什么东西？你确定关闭其他插件了吗

**Comment by HatsukiH** [comment]
> console里面的requests.js和iframe.html是什么东西？你确定关闭其他插件了吗

抱歉 有个隐藏的插件忘记了 删除插件后功能正常

**Comment by xmcp** [comment]
能说下是具体是哪个插件吗，我看看能不能做下兼容处理

**Comment by HatsukiH** [comment]
> 能说下是具体是哪个插件吗，我看看能不能做下兼容处理

抱歉 之前一口气删了太多插件 试了下无法复现了
