### ISSUE TITLE
点击展开弹幕信息 与 Bilibili-Evolved 启用弹幕空降 冲突

### ISSUE THREAD

**Issue by WilliamK7** [xmcp/pakku.js#286]
### 是否可以稳定复现

可以

### 复现步骤

在开启 [Bilibili-Evolved](https://github.com/the1812/Bilibili-Evolved) 启用弹幕空降 和 pakku 的点击展开弹幕信息 后，点击含有空降信息的弹幕

### 预期行为

不按住 Ctrl 键的情况下，应该正常触发空降功能，不会显示弹幕详细信息

### 实际行为

在不按住 Ctrl 键的情况下，点击弹幕就会显示详细信息，且空降功能不生效

### 禁用 pakku 后 bug 是否存在

否

### 是否与其他插件有关

是

### B 站播放器版本号

4.8.27-8beb90e8

### pakku 调试信息

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 2024.6.2

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36`

**Incognito:** `false`

**Has Session Storage:** `true`

**localStorage:** `{"MARK_THRESHOLD":"1","TOOLTIP_KEYBINDING":"on","_ADVANCED_USER":"on","DANMU_MARK":"prefix","TAOLUS":"","BLACKLIST":"[]","_LAST_UPDATE_TIME":"1708761037488","SHRINK":"off","TRIM_SPACE":"on","MAX_DIST":"5","TRIM_ENDING":"on","AUTO_DANMU_LIST":"off","REMOVE_SEEK":"off","THRESHOLD":"10","POPUP_BADGE":"percent","TRIM_WIDTH":"on","FLUCTLIGHT":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","CLOUD_SYNC":"on","WHITELIST":"[]","PROC_TYPE7":"on","PROC_POOL1":"off","CROSS_MODE":"off","HIDE_THRESHOLD":"0","BREAK_UPDATE":"off","DANMU_SUBSCRIPT":"on","PROC_TYPE4":"on","TRIM_PINYIN":"on","ENLARGE":"on","MAX_COSINE":"60","MODE_ELEVATION":"off","TOOLTIP":"off","AUTO_DISABLE_DANMU":"off","REPRESENTATIVE_PERCENT":"20","SCROLL_THRESHOLD":"0"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Permissions:** `{"origins":["*://*.bilibili.com/*","https://www.bilibili.com/*","https://www.bilibili.com/robots.txt?pakku_sandbox","ws://*.bilibili.com/*","wss://*.bilibili.com/*"],"permissions":["contextMenus","notifications","storage","scripting","declarativeNetRequestWithHostAccess"]}`

**Content Scripts:** `[{"allFrames":true,"css":["generated/injected.css"],"excludeMatches":["https://www.bilibili.com/robots.txt?pakku_sandbox"],"id":"pakku-ajax","js":["generated/xhr_hook.js"],"matchOriginAsFallback":false,"matches":["*://*.bilibili.com/*"],"persistAcrossSessions":true,"runAt":"document_start","world":"MAIN"}]`

**DNR Rules:** `[]`

**State:** `{"GLOBAL_SWITCH":true,"STATS_314748248":{"combined_cosine_distance":0,"combined_edit_distance":4,"combined_identical":3,"combined_pinyin_distance":0,"deleted_blacklist":0,"deleted_blacklist_each":{},"deleted_dispval":0,"download_time_ms":1140,"ignored_script":0,"ignored_type":0,"ignored_whitelist":0,"modified_enlarge":0,"modified_scroll":0,"modified_shrink":0,"num_max_combo":4,"num_max_dispval":0,"num_onscreen_danmu":304,"num_taolu_matched":0,"num_total_danmu":310,"num_userscript":0,"parse_time_ms":617,"type":"done"},"_INITIALIZED":true}`

**Tabs:**

- ID=314747384 status=complete `undefined`

- ID=314747385 status=complete `undefined`

- ID=314747386 status=complete `undefined`

- ID=314748191 status=complete `undefined`

- ID=314748199 status=complete `undefined`

- ID=314748157 status=complete `undefined`

- ID=314748158 status=complete `undefined`

- ID=314748162 status=complete `undefined`

- ID=314748165 status=complete `undefined`

- ID=314748248 status=complete `https://www.bilibili.com/video/BV1nH4y1Y7gV/?p=46`

- ID=314748281 status=complete `undefined`

- ID=314748276 status=complete `undefined`

- ID=314748376 status=complete `undefined`

- ID=314748380 status=complete `undefined`

- ID=314748428 status=loading `undefined`

- ID=314748409 status=complete `undefined`

**Config:** `{"_LAST_UPDATE_TIME":11717853664828,"_CONFIG_VER":2,"ADVANCED_USER":true,"THRESHOLD":10,"MAX_DIST":5,"MAX_COSINE":60,"TRIM_PINYIN":true,"TRIM_ENDING":true,"TRIM_SPACE":true,"TRIM_WIDTH":true,"FORCELIST":[["^23{2,}$","233..."],["^6{3,}$","666..."],["^[fF]+$","FFF..."],["^[hH]+$","hhh..."],["^[yYoO0][yYoO0\\s~]+$","yoo..."]],"WHITELIST":[],"CROSS_MODE":false,"PROC_TYPE7":true,"PROC_TYPE4":true,"PROC_POOL1":false,"DANMU_MARK":"prefix","MARK_THRESHOLD":1,"DANMU_SUBSCRIPT":true,"ENLARGE":true,"SHRINK_THRESHOLD":0,"DROP_THRESHOLD":0,"MODE_ELEVATION":false,"REPRESENTATIVE_PERCENT":20,"TOOLTIP":true,"TOOLTIP_KEYBINDING":true,"AUTO_DISABLE_DANMU":false,"AUTO_DANMU_LIST":false,"FLUCTLIGHT":true,"BREAK_UPDATE":false,"SCROLL_THRESHOLD":0,"USERSCRIPT":null,"POPUP_BADGE":"percent","COMBINE_THREADS":3,"READ_PLAYER_BLACKLIST":true}`

**Worker is Simulated:** `false`

**Exception:** `error log is working ("Error: error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:6469")`

**Exception in Promise:** `async error log is working ("Error: async error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:6426\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:6466")`
</details>

**Comment by WilliamK7** [comment]
https://github.com/the1812/Bilibili-Evolved/issues/4786

**Comment by xmcp** [comment]
给个可以复现的链接

**Comment by WilliamK7** [comment]
https://www.bilibili.com/video/BV1R24y1v7wE/
此视频中有大量的空降链接，在开启 pakku 的 点击展开弹幕信息 后，无需按住 Ctrl 键就会展开详细信息，且空降功能不生效

**Comment by xmcp** [comment]
pakku v2024.6.3已修复此问题
