### ISSUE TITLE
装上插件后我的弹幕都不见了，加载弹幕显示为0

### ISSUE THREAD

**Issue by Loqiai** [xmcp/pakku.js#287]
### 是否可以稳定复现

每次都出现

### 复现步骤

打开b站的任何视频，都显示加载弹幕为0，卸载后就都有了，
无论我是关闭插件，还是开启插件，弹幕的加载都为0
而且我去设置界面设置好了参数，再打开，参数都不见了

### 预期行为

应该是应用到视频弹幕中

### 实际行为

弹幕为0
![屏幕截图 2024-06-13 115158](https://github.com/xmcp/pakku.js/assets/124015909/4a76b2e8-6d63-4bd9-842a-a30276a5495f)

### 禁用 pakku 后 bug 是否存在

不存在

### 是否与其他插件有关

无关

### B 站播放器版本号

4.8.27-8beb90e8

### pakku 调试信息

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 2024.6.2

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36`

**Incognito:** `false`

**Has Session Storage:** `true`

**localStorage:** `{}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Permissions:** `{"origins":["*://*.bilibili.com/*","https://www.bilibili.com/robots.txt?pakku_sandbox"],"permissions":["contextMenus","notifications","storage","scripting","declarativeNetRequestWithHostAccess"]}`

**Content Scripts:** `[]`

**DNR Rules:** `[]`

**State:** `{"GLOBAL_SWITCH":true,"_INITIALIZED":true}`

**Tabs:**

- ID=1814881192 status=complete `https://www.bilibili.com/`

- ID=1814881223 status=complete `https://www.bilibili.com/video/BV1ix411c7Ye/?p=1&vd_source=25162ded55c54a483385717e480c7ad4`

- ID=1814881235 status=complete `https://www.bilibili.com/blackboard/webplayer_history.html#html5`

- ID=1814881234 status=complete `undefined`

- ID=1814881243 status=complete `undefined`

- ID=1814881244 status=loading `undefined`

**Worker is Simulated:** `false`

**Exception:** `error log is working ("Error: error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:6469")`

**Exception in Promise:** `async error log is working ("Error: async error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:6426\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:6466")`
</details>

**Comment by xmcp** [comment]
看着像是浏览器的保存设置功能出现了问题。请尝试在设置页面按F12，在console中运行以下代码，看看有没有输出：

`await chrome.storage.sync.get()`

**Comment by xmcp** [comment]
邮件回复好像显示不了图片

**Comment by xmcp** [comment]
打算下个版本改进一下读取设置时的错误提示。不过我还是不知道具体报错是什么，你可以发一下文字，或者在github.com网页上回复可以粘贴图片。

**Comment by Loqiai** [comment]
我重装了Chrome，问题解决了

xmcp ***@***.***> 于2024年6月15日周六 02:48写道：
