### ISSUE TITLE
请问在当前（v2024.6.3_C）版本下如何实现先前版本的自定义黑名单功能

### ISSUE THREAD

**Issue by mark9804** [xmcp/pakku.js#288]
xmcp 你好，

曾经的 pakku 版本是有黑名单功能的，但是在某一个版本之后黑名单变成了自定义脚本功能，并且脚本长度不能超过 8kb。

我自己用的黑名单长度已经远远超过了 8kb，因此似乎在当前 pakku 版本下不能通过硬编码实现。我目前正在考虑使用 fetch 功能从云端获取黑名单，但是这个功能需要 `tweak_before_pakku` 支持结果为 `Promise` 的返回值，从类型定义上来看 pakku 暂时还不支持该功能。

请问目前我还有其他实现自定义黑名单的思路吗？希望作者能够指点一二。

**Comment by xmcp** [comment]
噢，用户脚本其实是可以通过 [`importScripts`](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#importing_scripts_and_libraries) 函数引入外部代码的。类似这样：

```javascript
importScripts('https://s.xmcp.ltd/sample/large_data.js');
// ↑ const LARGE_DATA = ['hello', 'world'];

let regexps = LARGE_DATA.map(s => new RegExp(s, 'i'));

tweak_before_pakku(r=>{
  r.objs = r.objs.filter(d=>
    !regexps.some(r => r.test(d.content))
  );
});
```

我在文档里写一下吧，这样就能绕过 8KB 的限制了。

**Comment by xmcp** [comment]
刚更新的2024.7.1版本将从网页的 `localStorage` 读取额外的用户脚本和屏蔽词。因此如果你有大量的屏蔽词难以导入B站播放器，可以存储在 www.bilibili.com 域的 `localStorage['pakku_extra_blacklist']` 中，格式与B站播放器导出的 JSON 格式相同。例如，在视频页面的 console 中执行以下代码：

```javascript
localStorage['pakku_extra_blacklist'] = JSON.stringify([{type: 1, filter: '^.{1,6}[天时点分钟秒]前', opened: true, id: 0}]);
```

**Comment by mark9804** [comment]
感谢，天才的想法
