### ISSUE TITLE
ctrl展开弹幕功能失效

### ISSUE THREAD

**Issue by shibuyameltdown** [xmcp/pakku.js#289]
### 是否可以稳定复现

可以稳定复现

### 复现步骤

按住ctrl

### 预期行为

弹幕出现黄色背景填充，看到详细信息

### 实际行为

视频进度条和暂停图标（如果当前屏幕上有的话）会被隐藏，松手后出现

### 禁用 pakku 后 bug 是否存在

是

### 是否与其他插件有关

无关

### B 站播放器版本号

4.8.34-rc.7035.0-1fd2be51

### pakku 调试信息

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 2024.7.1

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`

**Incognito:** `false`

**Has Session Storage:** `true`

**localStorage:** `{}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Permissions:** `{"origins":["*://*.bilibili.com/*","https://www.bilibili.com/robots.txt?pakku_sandbox"],"permissions":["contextMenus","notifications","storage","scripting","declarativeNetRequestWithHostAccess"]}`

**Content Scripts:** `[{"allFrames":true,"css":["generated/injected.css"],"excludeMatches":["https://message.bilibili.com/*","https://www.bilibili.com/robots.txt?pakku_sandbox"],"id":"pakku-ajax","js":["generated/xhr_hook.js"],"matchOriginAsFallback":false,"matches":["*://*.bilibili.com/*"],"persistAcrossSessions":true,"runAt":"document_start","world":"MAIN"}]`

**DNR Rules:** `[]`

**State:** `{"GLOBAL_SWITCH":true,"STATS_1030112145":{"combined_cosine_distance":0,"combined_edit_distance":0,"combined_identical":0,"combined_pinyin_distance":0,"deleted_blacklist":0,"deleted_blacklist_each":{},"deleted_dispval":0,"download_time_ms":538,"ignored_script":0,"ignored_type":0,"ignored_whitelist":0,"modified_enlarge":0,"modified_scroll":0,"modified_shrink":0,"num_max_combo":1,"num_max_dispval":0,"num_onscreen_danmu":5,"num_taolu_matched":0,"num_total_danmu":5,"num_userscript":0,"parse_time_ms":264,"type":"done","userscript_time_ms":0},"_INITIALIZED":true}`

**Tabs:**

- ID=1030112140 status=complete `https://www.bilibili.com/`

- ID=1030112141 status=complete `https://www.bilibili.com/video/BV1aS411w7dj/`

- ID=1030112142 status=complete `https://www.bilibili.com/video/BV1Br421K7bX/`

- ID=1030112143 status=complete `https://www.bilibili.com/video/BV1oW42197TG/`

- ID=1030112144 status=complete `https://www.bilibili.com/video/BV1E2421Z7ve/`

- ID=1030112145 status=complete `https://www.bilibili.com/video/BV17i421a7R4/`

- ID=1030112243 status=loading `undefined`

- ID=1030112246 status=loading `undefined`

- ID=1030112148 status=complete `undefined`

**Config:** `{"_LAST_UPDATE_TIME":11721386637022,"_CONFIG_VER":3,"ADVANCED_USER":true,"THRESHOLD":15,"MAX_DIST":3,"MAX_COSINE":85,"TRIM_PINYIN":true,"TRIM_ENDING":true,"TRIM_SPACE":true,"TRIM_WIDTH":true,"FORCELIST":[["^6{3,}$","666..."],["^[fF]+$","FFF..."],["^[hH]+$","hhh..."],["^[yYoO0][yYoO0\\s~]+$","yoo..."]],"WHITELIST":[["哈哈",""],["233",""],["前方高能",""],["高能",""],["啊",""]],"CROSS_MODE":true,"PROC_TYPE7":true,"PROC_TYPE4":true,"PROC_POOL1":false,"DANMU_MARK":"suffix","MARK_THRESHOLD":5,"DANMU_SUBSCRIPT":true,"ENLARGE":false,"SHRINK_THRESHOLD":0,"DROP_THRESHOLD":0,"MODE_ELEVATION":true,"REPRESENTATIVE_PERCENT":20,"TOOLTIP":true,"TOOLTIP_KEYBINDING":true,"AUTO_DISABLE_DANMU":false,"AUTO_DANMU_LIST":false,"FLUCTLIGHT":false,"BREAK_UPDATE":false,"SCROLL_THRESHOLD":1200,"USERSCRIPT":null,"POPUP_BADGE":"percent","COMBINE_THREADS":3,"READ_PLAYER_BLACKLIST":true}`

**Worker is Simulated:** `false`

**Exception:** `error log is working ("Error: error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:8973")`

**Exception in Promise:** `async error log is working ("Error: async error log is working\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:8930\n    at chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/generated/troubleshooting.js:1:8970")`
</details>

### 补充说明

以前也出现过（一年不到几次的频率），但是等个几天时间他就自己好了，至今不清楚什么原因

**Comment by xmcp** [comment]
隐藏进度条和暂停图标是预期行为，但为什么点击弹幕不显示信息就不清楚了。可能是播放器显示弹幕的方式有变化，我这里复现不出来。

**Comment by rslika** [comment]
遇到了同样的问题

**Comment by shibuyameltdown** [comment]
今天复活了，不清楚什么情况

**Comment by xmcp** [comment]
我这里播放器版本号升级到了4.8.36-511a5548，依然无此问题。疑似4.8.34版本灰度测试发现改挂了什么东西，现在又改回来了。

**Comment by shibuyameltdown** [comment]
嗯。。。今天又失效了

**Comment by xmcp** [comment]
播放器 4.8.38-979a66e3 版本可以复现此问题，已在 pakku 2024.8.1 修复。
