### ISSUE TITLE
在 Firefox Esr 52.4.0 下无法保存设置

### ISSUE THREAD

**Issue by lm789632** [xmcp/pakku.js#29]
如题，Chrome 下修改设置会出现已保存的提示，而在 Firefox 下没有任何提示，修改也不会生效
7.1.3版

**Comment by xmcp** [comment]
设置页面F12的 console 有显示任何错误吗？如果有的话求相关信息。

**Comment by xmcp** [comment]
bug 在 ESR 52.4.1 复现成功，原因是 `chrome.permissions === undefined`，所以 core.js 挂掉了。马上修复。

**Comment by lm789632** [comment]
看了一下，就这两条
TypeError: chrome.permissions is undefined[详细了解]  options.js:3:1
	<匿名> moz-extension://4ac4647b-fb54-4c9d-a7ba-62f40119022b/options/options.js:3:1
利用 document.write() 写入不平衡树引发来自网络的数据被重新解析。更多信息参见 https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  options.html:2

**Comment by lm789632** [comment]
感谢，速度好快啊

**Comment by xmcp** [comment]
ESR 上还有一个恶性 bug，就是 `XMLHttpRequest` hook 之后不知为何请求还是发出去了，导致请求了两遍。也将一并修复。

**Comment by xmcp** [comment]
bugfix 已提交 AMO 审核，应该很快能够上架。

另外 ESR 52 对 WebExtension 的支持是比较弱的，个人还是建议你换回正常分支。

**Comment by lm789632** [comment]
谢谢，麻烦了
