### ISSUE TITLE
能实现过去b站按等级屏蔽弹幕的功能么？

### ISSUE THREAD

**Issue by Cyiming** [xmcp/pakku.js#290]
### 功能内容

现在b站官方下架了这个功能 太难受了

**Comment by xmcp** [comment]
6，前一阵是不让关闭云屏蔽，现在又一转不让打开云屏蔽了，不知道阿姨在干什么。

目前可以通过 [用户脚本功能](https://github.com/xmcp/pakku.js/tree/master/userscript_docs) 重现云屏蔽的功能，代码大概这样：

```javascript
const FILTER_LEVEL = 3; // 仅保留权重大于等于此值的弹幕，权重范围一般为1到11

tweak_after_pakku(c=>{
  let orig_len = c.objs.length;
  c.objs = c.objs.filter(d => d.weight >= FILTER_LEVEL);
  console.log('weight filtering:', orig_len, '->', c.objs.length);
});
```

暂时先不打算在pakku直接实现这个功能，先观望一下B站的状况，没准过几周它又改回来了。

**Comment by WakelessSloth56** [comment]
6。不能打开云屏蔽的是哪个版本的播放器？目前至少我还没有遇到，[这边](https://github.com/the1812/Bilibili-Evolved/discussions/4920)还在和关不掉的屏蔽斗争呢🤣

**Comment by Cyiming** [comment]
> 6。不能打开云屏蔽的是哪个版本的播放器？目前至少我还没有遇到，[这边](https://github.com/the1812/Bilibili-Evolved/discussions/4920)还在和关不掉的屏蔽斗争呢🤣

![Clip_2024-09-27_17-45-12](https://github.com/user-attachments/assets/e9fc2680-4e66-4a45-bf19-6995aa22faca)
我好几个月都这样
![Clip_2024-09-27_17-58-53](https://github.com/user-attachments/assets/6aa4007a-2a57-4da2-af48-c2654b40890b)

**Comment by WakelessSloth56** [comment]
这个版本就是这个[讨论中的版本 3](https://github.com/the1812/Bilibili-Evolved/discussions/4920)，不能自己调等级，等级根据弹幕区域和弹幕密度计算。
上面的 xmcp 的评论已经给出解决方案了（ https://github.com/xmcp/pakku.js/issues/290#issuecomment-2368449729 ）。

**Comment by xmcp** [comment]
v2024.10.1已增加相关设置，可以勾选【阻止弹幕云屏蔽】，不再需要使用用户脚本

![image](https://github.com/user-attachments/assets/62b92164-b1ab-4c3b-97c7-ee7c122a0c03)
