### ISSUE TITLE
有可能使用 WebAssembly 来提升计算时的性能吗？

### ISSUE THREAD

**Issue by Anz-03** [xmcp/pakku.js#295]
### 功能内容

大部分扩展基本不会进行运算，所以一般WebAssembly 不会用于扩展。
pakku 不一样，它有很多数学计算，感觉非常适合用 C/C++或者 rust 编译出WebAssembly 加速

**Comment by xmcp** [comment]
目前运算速度基本不是瓶颈，在使用了正常数量的worker线程后，最极端的情况也能在几秒钟之内处理完毕。如果你确实觉得这个功能有必要，请举一个在默认的使用3个线程时处理弹幕用时超过10秒的视频作为例子。

**Comment by xmcp** [comment]
看了下如果把合并时间阈值设置得比较高，在部分弹幕密集的视频里处理时间确实可能逼近10秒。确实可以搞wasm

**Comment by xmcp** [comment]
2024.12.1已解决
