### ISSUE TITLE
能不能选择弹幕上限。

### ISSUE THREAD

**Issue by lanmaoaiwo** [xmcp/pakku.js#31]
假设视频总弹幕10000，弹幕池上限6000，过滤1500，目前还剩4500。

能不能变成按10000过滤了2500，弹幕池上限还是6000或突破到7500。

**Comment by xmcp** [comment]
pakku 本身并没有设置弹幕数量上限，设置上限的是B站，即B站服务器提供给浏览器的弹幕数量就只有 6000 个，我能怎么办？

B站没有提供下载所有弹幕 (aka. 全弹幕) 的方式，必须一个个下载历史弹幕然后合并起来。这样还会使网络错误的几率指数级增加。

我觉得这项功能实现起来意义不大。如果有人觉得全弹幕功能很有必要就发 PR 过来。
