### ISSUE TITLE
添加弹幕套路正则

### ISSUE THREAD

**Issue by LvWind** [xmcp/pakku.js#32]
默认屏蔽或者合并类似 “x小时前”，“第一！”，这样的无意义弹幕

供参考：
`/^\s*(前|第)\s*(\d+|(一|二|三|四|五|六|七|八|九|十).*)/`
`/.+小时|.+分钟/`

**Comment by xmcp** [comment]
弹幕套路自带的那几个规则，它们的作用主要是教会用户“这是什么东西”。
目前没有添加更多默认规则的打算，你有这个需要的话自己设置就行。

原因主要有：
- 不是所有的用户都会看设置页面，如果我给他默认设置了什么东西他不知道，他反倒会认为这是一个bug。比如 #23
- 不是所有的用户都觉得这些内容需要被合并（我到更倾向于认为它们应该直接被屏蔽掉，这也是B站官方的态度）

另外类似的规则你可以参考 https://github.com/xmcp/bilibili-ban-list/blob/master/tv.bilibili.player.xml#L15-L25

**Comment by LvWind** [comment]
好吧。。
顺便感谢更多规则
