### ISSUE TITLE
增加“默认开启防挡弹幕”功能

### ISSUE THREAD

**Issue by AnnAngela** [xmcp/pakku.js#33]
RT，每次需要防挡弹幕时都要手动开很麻烦，不知道作者有没有兴趣搞一搞2333

**Comment by xmcp** [comment]
*pakku本身只修改弹幕的XML，所以在这个XML以外的任何设置（包括防挡弹幕的设置）都是改不了的。*

↑ 这是理论上的情况

然而实际上，pakku 的“弹幕信息显示框”功能要求它必须注入一段 JS 到页面里。
所以在那个 JS 里加一段 `document.querySelector('input.bilibili-player-setting-preventshade').click()` 之类的东西似乎就能搞定这个功能了。

这个 feature 似乎非常可做的样子 ✓
有空我可以实现一下，以及之前在 Chrome Web Store 上有个“默认关闭弹幕”的 feature request 似乎也可以一块实现了。
