### ISSUE TITLE
在 Firefox 上使用，切换为”休息中“时无法加载出正常弹幕

### ISSUE THREAD

**Issue by hiikii** [xmcp/pakku.js#34]
开发者你好！
首先感谢你的这个扩展，让我看视频时眼睛舒服了很多，不过我遇到了一个问题。就是当在 B 站打开视频时扩展可正常工作，但将状态切换为”休息中“并再次刷新页面时（也试过关闭页面再打开），B 站弹幕栏无法加载出弹幕，会提示”弹幕列表装填失败“。
我的使用环境：Firefox 56.0（64 位），Windows 系统。

**Comment by xmcp** [comment]
目测是在修 #29 的时候不小心引入的……
