### ISSUE TITLE
在Firefox上，可能需要重启浏览器才可以保存配置？

### ISSUE THREAD

**Issue by Dorl121** [xmcp/pakku.js#35]
在Firefox 53.0.3 上，安装脚本后无法修改配置页面后保存，需要重启浏览器才可以？这个是正常的吗？

另外，有没有tg啊？我想问点其他问题，关于 **【数据删除】** 的

**Comment by xmcp** [comment]
什么意思？保存之后不生效是吗？这不应该呀……
是页面没有显示“已保存”，还是显示了但重启才生效？F12的控制台有显示异常吗？
不在电脑边上，如果你能提供一些错误的细节是极好的。

关于你说的heroku那个，我只能告诉你那个东西是 github.com/xmcp/tiroFinale ，其他一律无可奉告，闷声发大财才是坠吼的。

**Comment by Dorl121** [comment]
是页面没出现“已保存”。就出现过我第一次安装的时候，后来我在移除，在安装就不会出现。。。
我是用github直接布置在heroku，因为傻瓜。。。但是需要nodejs，也能用，但是比较麻烦。。。我是一个完全的菜鸟，估计是看不懂你那个了
