### ISSUE TITLE
UID显示用户名是什么操作

### ISSUE THREAD

**Issue by tetsaicn** [xmcp/pakku.js#36]
直接通过弹幕发送UID判断用户名？但是有很多UID没有收录，这是大爬B站吗。

**Comment by xmcp** [comment]
这是调用的 biliquery.typcn.com 的接口，具体的详情可以看 [作者本人的博客](http://blog.eqoe.cn/posts/bilibili-comment-sender-digger.html)。
因为B站对UID的“加密”只是简单的CRC32哈希，只要事先把各种UID对应的值计算出来，存到数据库里，用的时候就可以直接查表了。

biliquery.typcn.com 只存储了UID比较小的那部分数据，所以新注册的用户很多都没有收录。

对于这个问题，我在2017.7.13发邮件建议过 typcn 扩充数据库，他的回复是：

> 您好，目前数据库的 uid 最大到 4 千万，稍后进行扩展

但好像一直没有动静的样子。

**Comment by xmcp** [comment]
（其实在选项里面的 “弹幕信息显示框” 下面有一个小小的 credit，但没什么能注意到 :rofl: ）

**Comment by typcn** [comment]
抱歉，事情比较多没有什么时间，当前服务器负载已经超过 100，硬盘也满了，我随后迁移到新的服务器上。

**Comment by tetsaicn** [comment]
就是没有服务器，不然我也跑一个

**Comment by fanthos** [comment]
做成静态放到cdn上面应该会好一些吧

**Comment by typcn** [comment]
新 uid 数据有 6GB 左右，今晚部署到服务器上

**Comment by tetsaicn** [comment]
Email也可以直接发布回复了吗，好评

 
发件人： typcn
发送时间： 2017-10-27 18:01
收件人： xmcp/pakku.js
抄送： Tetsai; Author
主题： Re: [xmcp/pakku.js] UID显示用户名是什么操作 (#36)
新 uid 数据有 6GB 左右，今晚部署到服务器上

**Comment by xmcp** [comment]
@fanthos 静态的不好查询呀，hash → UID 的映射是离散的，你是打算用 `Accept-Ranges` 请求头二分查找吗？:rofl:

**Comment by fanthos** [comment]
每256个（大概）放到一个文件里

**Comment by typcn** [comment]
跳票一下，数据已经导入了，事情比较多，明天早上去机场设置，最迟明天晚上应该就可以看到新版 API了，另外新版 API 对于 hash 冲突的用户会返回多个 UID

**Comment by typcn** [comment]
已经部署，大约 15 分钟后 API 将自动扩展到 3 亿数据
另外我把服务器端开源了 https://github.com/typcn/biliquery_db
大家也可以自己部署，大约需要 15GB 内存

**Comment by dramforever** [comment]
昨天把本机反查做了，各位有这个需求的来更新一下看有没有啥问题
https://github.com/xmcp/pakku.js/pull/39
