### ISSUE TITLE
希望增加导出 XML/ASS 弹幕文件的功能

### ISSUE THREAD

**Issue by Sg4Dylan** [xmcp/pakku.js#37]
之前使用 Bilibili 助手下载 XML 弹幕文件，下载得到的文件默认是被 pakku.js 处理过的。
虽然 HTML5 播放器下 pakku.js 工作正常，但现在下载的 XML 弹幕未经处理（fallback 到 #27 ）。
~其实摸到 XML 的 URL，append 上 `?debug` 再打开就能触发 pakku.js 了，只是懒而已~
所以麻烦作者增加导出 XML/ASS 弹幕文件的功能（
至于转换 ASS，能一起做便是极好的。
具体的可以调用这个脚本：
https://tiansh.github.io/us-danmaku/bilibili/

浏览器：`Chrome 64.0.3251.0 (正式版本) dev （64 位）`

**Comment by xmcp** [comment]
想导出XML的话，点 Browser Action 里面的这个链接，然后 Ctrl+S 就行了。
![image](https://user-images.githubusercontent.com/6646473/32132186-a38bf40e-bbf1-11e7-9474-6c4166648ad6.png)

至于转换 ASS，那个[在线转换](https://tiansh.github.io/us-danmaku/bilibili/) 挺好用的，你就用那个吧 ┑(￣Д ￣)┍

<hr>

通过 Bilibili 助手下载弹幕未被处理的原因我看了一下，应该是 Bilibili 助手自己的用法比较奇妙导致的。

相关代码如下：

```javascript
// bilibili_injected.js
$bhDownLink.click(function(e) {
    e.preventDefault();
    chrome.runtime.sendMessage({
        command: 'requestForDownload',
        url: $(e.target).attr('href'),
        filename: $(e.target).data('download'),
    });
});

// background.js
chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    switch (request.command) {
    // ...
    case 'requestForDownload':
        chrome.downloads.download({
            saveAs: true,
            url: request.data ? URL.createObjectURL(new Blob([request.data], {
                type: 'application/octet-stream',
            })) : request.url,
            filename: 'Bilibili/' + request.filename,
        });
        return true;
    // ...
    }
});
```

所以你点那个下载按钮的时候，下载的请求其实是从 Bilibili 助手的 Background Script 通过 `chrome.downloads.download` 发出的……
文档里没有写，但 pakku 的 `chrome.webRequest.onBeforeRequest` Listener 根本抓不到这个请求，所以我们对这个无能为力 [摊手]。

<hr>

pakku 跟 Bilibili 助手确实会有一些冲突。除上述问题之外，Bilibili 助手会卡在 “正在加载全部弹幕, 请稍等…” 的状态，并抛出异常：

```
Uncaught (in promise) TypeError: Failed to fetch
Fetch API cannot load http://comment.bilibili.com/xxxxx.xml. Redirects to data: URL are allowed only when mode is "no-cors".
```
（在 Bilibili 助手的 [bilibili_injected.js#L490](https://github.com/zacyu/bilibili-helper/blob/d8322fa231d6098fe9326251a5c387a3e7338f58/src/bilibili_injected.js#L490) 里面。）

这个不兼容也不是我的锅，是 Bilibili 助手自己用了 fetch 结果不支持 Data URI 的问题。在此把锅暂时甩给对面：@zacyu 。

<hr>

我只能尽量避免跟其他插件同时使用时产生的恶性 bug，但这种不兼容也不是我自己就能解决的。

**Comment by zacyu** [comment]
第一个问题是为了命名下载文件以及建议保存目录需要, 我可以看一下有什么更好的解决方案. 第二个冲突并不是 fetch API 而是 CORS 的问题. 有时间一起看一下怎么解决吧（ ・∀・）

**Comment by xmcp** [comment]
@zacyu

关于第一个问题，可以让 content script 直接把要下载的数据发回 background page 而不是发 URL。

第二个问题看起来比较困难，其实旧版的 Chrome 连 XHR 都不支持 Data URI，也会报跨域的错，但从某个版本之后就支持 XHR 里面的 Data URI 了（fetch 还是不行）。一个 workaround 是拿 XHR 替代 fetch，不知道还有没有更优雅的写法。

**Comment by xmcp** [comment]
@zacyu 

https://github.com/xmcp/bilibili-helper/commit/275b48e58a178c2d2070383c4973f2337142bd16
https://github.com/xmcp/bilibili-helper/commit/c840a4e8d647c786f6f445e4b035f9e0175bfa2e

这两个问题的 workaround（不知道 fetch 有没有更优雅的办法）。
