### ISSUE TITLE
既然能根据弹幕反查用户，能不能加一个屏蔽弹幕发送者的功能？

### ISSUE THREAD

**Issue by excosy** [xmcp/pakku.js#38]
这个屏蔽的用户可以放在本地，以后可以考虑共享到云端，甚至添加到B站登录用户的屏蔽列表。需要先自行实现根据用户屏蔽弹幕的功能吗？

**Comment by xmcp** [comment]
个人觉得屏蔽发送者没有什么用啊……而且B站不是本来就能屏蔽发送者吗？
