### ISSUE TITLE
考虑使用 page action 而不是 browser action

### ISSUE THREAD

**Issue by dramforever** [xmcp/pakku.js#4]
> - **Do** use page actions for features that make sense for only a few pages.
> (https://developer.chrome.com/extensions/pageAction)

**Comment by xmcp** [comment]
然而我需要显示GLOBAL_SWITCH开关啊。改成pageAction之后你把GLOBAL_SWITCH关掉了就再也恢复不了了怎么办。

你看隔壁ABP用的就是browserAction。

ps. 现在的chrome已经基本不区分pageAction和browserAction了，即使是pageAction也不会显示在omnibo上，只是把browserAction位置的图标变灰而且点不动。
