### ISSUE TITLE
与下载弹幕的脚本有冲突

### ISSUE THREAD

**Issue by sakuyaa** [xmcp/pakku.js#41]
是这样的，我有一个user脚本[bilibiliDanmaku.user.js
](https://github.com/sakuyaa/gm_scripts/blob/master/bilibiliDanmaku.user.js)
用它来查看或下载弹幕的，其中下载弹幕这个用到了XMLHttpRequest，responseType为blob。
但是由于这个扩展改变了XMLHttpRequest的原型，使用addEventListener('load')得到的response是字符串类型，且开头丢失了`<?xml version="1.0" encoding="UTF-8"?>`这一段。
请问什么办法可以解决呢，可否不对responseType为blob的XMLHttpRequest进行处理，或者返回原response？

**Comment by xmcp** [comment]
魔改 XMLHttpRequest 的代码是为了适配 Firefox而秉承能用就行的方针瞎写的 :rofl:，所以没考虑那么多。
临时的 workaround 是在 URL 里随便加个参数，pakku 就不会管了，大概。

**Comment by sakuyaa** [comment]
只要URL加的参数不是debug，跳过正则判断就可以了，感谢
