### ISSUE TITLE
 在 Firefox 上,状态"工作中"没有发现B站播放器

### ISSUE THREAD

**Issue by z456321abc** [xmcp/pakku.js#42]
FF版本为50.1.0,以切换到HTML5播放器,状态"工作中",但都是提示本页面没有发现B站播放器。且重启电脑还是浏览器都无法保存设置

**Comment by xmcp** [comment]
50.1.0太老了，升级到 Firefox 52+

**Comment by xmcp** [comment]
Firefox 50 上报的错乱七八糟的。
如果有人能解决就发 PR 过来，我就不管了。
