### ISSUE TITLE
建议增加配置保存或者导入导出的功能

### ISSUE THREAD

**Issue by Raynss** [xmcp/pakku.js#43]
自己加了几个屏蔽的正则表达式，更新以后什么也没有了……

加了以后也看不到自己加的有哪些……

**Comment by xmcp** [comment]
按住ctrl+alt点击版本号可以导入导出。
不过升级的话设置应该保留才对呀……你是不是先把旧版本删掉了，再装的新版？

**Comment by Raynss** [comment]
其实我的需求是多个平台和浏览器直接导出导入设置——主要是屏蔽关键字的同步。

或者说希望强化一下弹幕黑名单功能，可以方便的查看编辑导入导出。

PS：试了一下，好像在选项页面ctrl+alt点击版本号不能导出弹幕黑名单里面的内容。

**Comment by xmcp** [comment]
点版本号肯定是会把所有设置都导出的，这点绝对没有问题。

pakku 的黑名单主要是为了避免xN标记影响少数含有^和$标记的正则识别，不是主要功能。
B站播放器本身的屏蔽词就能实现云同步，使用体验也很好。pakku 弱化了黑名单功能，意在避免与官方功能重叠。所以你不如去用B站本身的弹幕屏蔽。
