### ISSUE TITLE
开启过滤功能，导致弹幕列表装填失败，刷新无效。

### ISSUE THREAD

**Issue by wjw97** [xmcp/pakku.js#44]
开启过滤功能，导致弹幕列表装填失败，刷新无效。视频无法显示弹幕，关闭后点击重试即恢复正常。该现象在Firefox58.0上一定出现，在UC国际版上有时出现。

**Comment by xmcp** [comment]
诶？我这里没有发现问题呀（Firefox 58.0b12、pakku 8.0.3）。
![image](https://user-images.githubusercontent.com/6646473/34263481-a4267c70-e6aa-11e7-9987-53bf3c2d3cb0.png)

UC国际版是chrome内核，和firefox同时出现问题不太应该呀……
没准是插件之间有冲突？试试把其他扩展（包括tampermonkey之类的）禁用掉管用吗？
或者是你网络比较奇怪？比如试试连到别的网络，或者拿手机开热点，再看看问题有没有消失？

另外，在网页上按F12，在控制台里有任何提示吗？麻烦截张图，谢谢。（如下图）
![image](https://user-images.githubusercontent.com/6646473/34263623-131182ba-e6ab-11e7-908c-c956017ef1aa.png)

**Comment by wjw97** [comment]
您好，我的火狐版本：Firefox Quantum 58.0b12（x64）
目前问题表现情况如下：
1.不关闭任何附加组件的情况下（正常浏览网页）
![bug1](https://user-images.githubusercontent.com/34747040/34264615-70341748-e6ae-11e7-8549-d93dcb2ec6bd.png)


2.关闭可能冲突的组件后（几乎关闭了所有第三方组件）

![bug3](https://user-images.githubusercontent.com/34747040/34264618-70a93672-e6ae-11e7-870f-516034f2bcdf.png)
3.我的组件
![bug2](https://user-images.githubusercontent.com/34747040/34264617-706ee148-e6ae-11e7-8fee-173966e42595.png)
（在进行关闭组件测试时，只启用了附加插件管理利器、哔哩哔哩助手、网页截图、网银支付助手）
4.无论哪个视频都是一样的，另外发现开启了弹幕密度分析后，在进度条可见弹幕(如图)
，但是仍然无法正常读取弹幕。
![bug4](https://user-images.githubusercontent.com/34747040/34264619-70e32594-e6ae-11e7-9ea6-5aea9d05c568.png)

目前UC一切正常。
我不知道刚才在邮箱直接回复bounces+848413-72b3-742725930=qq.com@sgmail.github.com是否有效。

**Comment by xmcp** [comment]
诶……控制台里真的没有 `pakku ajax: injecting hook` 那行吗？不应该呀……
你是从 addons.mozilla.org 安装的 pakku 吗？

**Comment by wjw97** [comment]
23333,问题解决。由于我是在Chrome商店安装的pakku，经过Chrome store foxified处理后的插件可能存在问题。（用火狐的习惯，经常在火狐商店找不到想要的插件，所以直接上google了。）安装火狐商店的版本后，正常。感谢作者！

**Comment by fanthos** [comment]
firefox有cors问题才用的注入
