### ISSUE TITLE
[建议]颜色不同但文本内容相同的弹幕在开启弹幕合并功能后进行合并

### ISSUE THREAD

**Issue by AnnAngela** [xmcp/pakku.js#45]
在观看小樱S02E02的时候我发现有不同颜色但是文本内容相同的弹幕在刷屏：
![image](https://user-images.githubusercontent.com/9762652/34912988-0c05c9b2-f92b-11e7-9295-d7a11080f319.png)
但是却没有合并=。=如果可以的话请将他们合并起来，颜色就选最早出现的那种就OK拉=w=

**Comment by xmcp** [comment]
![image](https://user-images.githubusercontent.com/6646473/34913141-f834d9b4-f92f-11e7-86fa-faf28f7e9e4b.png)
可是本来就是这么做的呀……你是不是设了白名单（现在改名叫“强制忽略”）什么的？

**Comment by xmcp** [comment]
啊……懂了，这些弹幕是你看视频看到一半的时候才发出来的，由于扩展程序没法监听websocket，所以pakku对这些无能为力。
pakku设置里面“阻止弹幕动态更新”的选项就是防止这种情况用的。

**Comment by AnnAngela** [comment]
了解

**Comment by ipcjs** [comment]
监听WebSocket还是可以做到的吧，代理一下WebSocket那个类就行了。

关键是已有的算法能不能处理新加一条数据的情况，以前应该是对所有数据做比较的吧？

**Comment by xmcp** [comment]
算法是一个问题，但更关键的是播放器不支持修改已有的弹幕，这样原来的脚标数字就不能改了。

**Comment by ipcjs** [comment]
修改内容也不是完全没有办法，就是方法特别歪😅

最终的弹幕列表是一个Array，WebSocket推送过来的弹幕会通过push方法添加到Array中，所以hook push方法，就能改写弹幕列表的内容了。。。
