### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by nofon** [xmcp/pakku.js#46]
插件文字全是省略号如图
![图片](https://user-images.githubusercontent.com/35449002/34934541-ceed7570-fa15-11e7-8b33-83297c627ea1.png)

<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 8.2.2

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36`

**localStorage:** `{"AUTO_DISABLE_DANMU":"off","AUTO_PREVENT_SHADE":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"off","FOOLBAR":"off","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","SCROLL_THRESHOLD":"900","SHRINK":"off","TAOLUS":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/options/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/options/troubleshooting.html`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=287 status=complete `undefined`

- ID=303 status=complete `undefined`

- ID=295 status=complete `undefined`

- ID=299 status=complete `undefined`

- ID=309 status=complete `undefined`

- ID=313 status=loading `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>2</chatid><mission>0</mission><maxlimit>1500</maxlimit><realname>0</realname><source>k-v</source><d p="0.00000,1,25,16777215,1441941098,0,e661a0e4,1202067477">fafafa</d><d p="5.49300,1,25,16777215,1455343346,0,15d09664,1589246009">123</d><d p="0.65400,1,25,16777215,1366373286,0,8c7c6214,208402166">··········</d><d p="8.42700,1,25,16777215,1370174903,0,17e31502,229404976">同步</d><d p="1.01800,1,25,16777215,1370174909,0,17e31502,229409010">能发送吗</d><d p="29.83000,1,100,1,1431166012,0,f512421f,892707883">什么鬼</d><d p="25.72300,1,100,16777215,1431166015,0,f512421f,892711968">什么鬼</d><d p="4.20000,1,25,16777215,1431925298,0,f512421f,900576077">test</d><d p="0.00000,1,25,16777215,1433070453,0,f512421f,914183339">test</d></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>2</chatid><mission>0</mission><maxlimit>1500</maxlimit><realname>0</realname><source>k-v</source><d p="0.00000,1,25,16777215,1441941098,0,e661a0e4,1202067477">fafafa</d><d p="5.49300,1,25,16777215,1455343346,0,15d09664,1589246009">123</d><d p="0.65400,1,25,16777215,1366373286,0,8c7c6214,208402166">··········</d><d p="8.42700,1,25,16777215,1370174903,0,17e31502,229404976">同步</d><d p="1.01800,1,25,16777215,1370174909,0,17e31502,229409010">能发送吗</d><d p="29.83000,1,100,1,1431166012,0,f512421f,892707883">什么鬼</d><d p="25.72300,1,100,16777215,1431166015,0,f512421f,892711968">什么鬼</d><d p="4.20000,1,25,16777215,1431925298,0,f512421f,900576077">test</d><d p="0.00000,1,25,16777215,1433070453,0,f512421f,914183339">test</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/options/troubleshooting.js` :: 67 :: 1
</details>

**Comment by xmcp** [comment]
虽然不知道为什么，但好像是我加的防盗版代码把整个 Background Page 干没了。

我稍微改了一下实现方式，现在应该没问题了，大概。
你清一下缓存然后重启浏览器试试，看看解决没有。

**Comment by nofon** [comment]
刚刚已经正常了，感谢修复
