### ISSUE TITLE
今天突然显示：弹幕列表装填失败，点击重试。

### ISSUE THREAD

**Issue by mazhen8u8** [xmcp/pakku.js#48]
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 8.5

**Channel:** firefox

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0`

**localStorage:** `{"FLUCTLIGHT":"off","BREAK_UPDATE":"off","FOOLBAR":"off","MAX_COSINE":"60","TRIM_SPACE":"on","DANMU_SUBSCRIPT":"on","POPUP_BADGE":"percent","REMOVE_SEEK":"off","TOOLTIP":"on","MAX_DIST":"5","SCROLL_THRESHOLD":"900","WHITELIST":"[]","AUTO_PREVENT_SHADE":"off","DANMU_MARK":"prefix","PROC_TYPE7":"on","SHRINK":"on","TRIM_ENDING":"on","MARK_THRESHOLD":"1","CROSS_MODE":"on","BLACKLIST":"[]","PROC_POOL1":"off","ENLARGE":"on","TRIM_WIDTH":"on","AUTO_DISABLE_DANMU":"off","TAOLUS":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","PROC_TYPE4":"on","_pakku_stats_time":"118/0/22","HIDE_THRESHOLD":"0","FLASH_NOTIF":"on","THRESHOLD":"20","_ADVANCED_USER":"off"}`

**Views:**

- `moz-extension://544be7a4-8273-411d-baa8-b952b33fd51e/core/background.html`

- `moz-extension://544be7a4-8273-411d-baa8-b952b33fd51e/options/options.html`

- `moz-extension://544be7a4-8273-411d-baa8-b952b33fd51e/options/troubleshooting.html`

- `moz-extension://544be7a4-8273-411d-baa8-b952b33fd51e/options/troubleshooting.html`

- `moz-extension://544be7a4-8273-411d-baa8-b952b33fd51e/options/troubleshooting.html`

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"2":{"identical":255,"edit_distance":459,"cosine_distance":63,"player_seek":"已禁用","blacklist":0,"count_hide":"已禁用","whitelist":0,"batch_ignore":0,"script":0,"enlarge":13,"shrink":200,"scroll":5,"taolu":61,"total":3000,"onscreen":2223,"maxcombo":61,"maxdispval":165.08816635772374,"error":null,"cid":"30309279"},"191":{"identical":2,"edit_distance":0,"cosine_distance":0,"player_seek":"已禁用","blacklist":0,"count_hide":"已禁用","whitelist":0,"batch_ignore":0,"script":0,"enlarge":0,"shrink":0,"scroll":0,"taolu":0,"total":9,"onscreen":7,"maxcombo":2,"maxdispval":9.611767402951557,"error":null,"cid":"2"},"193":{"identical":2,"edit_distance":0,"cosine_distance":0,"player_seek":"已禁用","blacklist":0,"count_hide":"已禁用","whitelist":0,"batch_ignore":0,"script":0,"enlarge":0,"shrink":0,"scroll":0,"taolu":0,"total":9,"onscreen":7,"maxcombo":2,"maxdispval":9.611767402951557,"error":null,"cid":"2"}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*","ws://*.bilibili.com/*","wss://*.bilibili.com/*","moz-extension://544be7a4-8273-411d-baa8-b952b33fd51e/*","*://*.bilibili.com/*"],"permissions":["webRequest","webRequestBlocking","notifications"]}`

**Tabs:**

- ID=3 status=complete `undefined`

- ID=1 status=complete `undefined`

- ID=4 status=complete `undefined`

- ID=5 status=complete `undefined`

- ID=6 status=complete `undefined`

- ID=7 status=complete `undefined`

- ID=8 status=complete `undefined`

- ID=9 status=complete `undefined`

- ID=10 status=complete `undefined`

- ID=11 status=complete `undefined`

- ID=12 status=complete `undefined`

- ID=13 status=complete `undefined`

- ID=14 status=complete `undefined`

- ID=15 status=complete `undefined`

- ID=16 status=complete `undefined`

- ID=17 status=complete `undefined`

- ID=18 status=complete `undefined`

- ID=19 status=complete `undefined`

- ID=20 status=complete `undefined`

- ID=21 status=complete `undefined`

- ID=22 status=complete `undefined`

- ID=23 status=complete `undefined`

- ID=24 status=complete `undefined`

- ID=25 status=complete `undefined`

- ID=26 status=complete `undefined`

- ID=27 status=complete `undefined`

- ID=2 status=loading `undefined`

- ID=148 status=complete `undefined`

- ID=194 status=loading `undefined`

- ID=193 status=complete `undefined`

- ID=191 status=complete `undefined`

- ID=192 status=complete `undefined`

- ID=190 status=complete `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>2</chatid><mission>0</mission><maxlimit>1500</maxlimit><realname>0</realname><source>k-v</source><d p="0.00000,1,25,16777215,1441941098,0,e661a0e4,1202067477">fafafa</d><d p="5.49300,1,25,16777215,1455343346,0,15d09664,1589246009">123</d><d p="0.65400,1,25,16777215,1366373286,0,8c7c6214,208402166">··········</d><d p="8.42700,1,25,16777215,1370174903,0,17e31502,229404976">同步</d><d p="1.01800,1,25,16777215,1370174909,0,17e31502,229409010">能发送吗</d><d p="29.83000,1,100,1,1431166012,0,f512421f,892707883">什么鬼</d><d p="25.72300,1,100,16777215,1431166015,0,f512421f,892711968">什么鬼</d><d p="4.20000,1,25,16777215,1431925298,0,f512421f,900576077">test</d><d p="0.00000,1,25,16777215,1433070453,0,f512421f,914183339">test</d></i>`

**Request / Normal XML:** load, status=200 `<i><chatserver>chat.bilibili.com</chatserver><chatid>2</chatid><mission>0</mission><maxlimit>1500</maxlimit><realname>0</realname><source>k-v</source><d p="0.00000,1,25,16777215,1441941098,0,e661a0e4,1202067477">fafafa</d><d p="0.00000,1,25,16777215,1433070453,0,f512421f,914183339">₍₂₎test</d><d p="0.65400,1,25,16777215,1366373286,0,8c7c6214,208402166">··········</d><d p="1.01800,1,25,16777215,1370174909,0,17e31502,229409010">能发送吗</d><d p="5.49300,1,25,16777215,1455343346,0,15d09664,1589246009">123</d><d p="8.42700,1,25,16777215,1370174903,0,17e31502,229404976">同步</d><d p="25.72300,1,100,16777215,1431166015,0,f512421f,892711968">₍₂₎什么鬼</d></i>`

**! Exception:** `ReferenceError: test_error_log is not defined`

`moz-extension://544be7a4-8273-411d-baa8-b952b33fd51e/options/troubleshooting.js` :: 67 :: 1

</details>

**Comment by xmcp** [comment]
好像现在B站用上了ServiceWorker……这就不好整了……淦……

![image](https://user-images.githubusercontent.com/6646473/35226880-8e91edb4-ffc7-11e7-95d2-182668580a57.png)

目前先把 Worker 设成 `null` 糊弄一下B站播放器，之后可能要考虑用 [webRequest.filterResponseData()](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/filterResponseData) *(Firefox 57+)* 了……

**Comment by xmcp** [comment]
先赶紧放个能用的 v8.5.1，之后再彻底解决这个问题。

**Comment by jhdxr** [comment]
如果非得57+就尴尬了。。。为了legacy addon还停留在56的用户路过_(:з」∠)_

**Comment by xmcp** [comment]
@jhdxr Firefox<=56 仍然可以用，但是作为兼容手段，会禁用掉 bilibili.com 上的所有 ServiceWorker。
现在B站没用 ServiceWorker 干什么事所以没问题，之后可能会影响一些功能。

**Comment by jhdxr** [comment]
@xmcp 明白了，多谢
