### ISSUE TITLE
请问能不能针对底部弹幕增大字号？

### ISSUE THREAD

**Issue by feise** [xmcp/pakku.js#49]
也不知道B站是怎么想的，没有相关配置可以更改。再看视频的时候，弄的滚动弹幕字号比字幕弹幕，底端/顶端固定弹幕还要大。
开启弹幕等比缩放以后，底端弹幕看的清了，滚动弹幕又非常大。不开等比缩放，甚至底端弹幕都看不清楚。笔记本1366X768的小屏幕，简直无语。

开了等比缩放的效果
https://i.loli.net/2018/02/01/5a727a663c65a.png
没开等比缩放的效果
https://i.loli.net/2018/02/01/5a727a8ee5bce.png

**Comment by xmcp** [comment]
感觉 pakku 杂七杂八的功能已经有点多了，这样小众的需求可能不会加。
（未来也许会考虑用类似于 User Script 的某种方式实现高级用户的各种花式需求。）
<hr>
不过教你一个奇技淫巧，可以实现底部弹幕增大字号：

首先，确认你用的是Chrome，而且版本比较新

![image](https://user-images.githubusercontent.com/6646473/35668704-79a72d94-076d-11e8-8d6c-88376b41257a.png)

![image](https://user-images.githubusercontent.com/6646473/35668780-b5b6d636-076d-11e8-8ade-b0102fa51362.png)

在如图所示的位置输入 `if(dm.mode==4) dm.size*=2;` 然后按 Ctrl+S 保存。

关掉 DevTools，**在关闭浏览器之前**该修改将持续生效。
