### ISSUE TITLE
Firefox下“数量标记显示成下标”选项的字体问题

### ISSUE THREAD

**Issue by guyigenius** [xmcp/pakku.js#51]
Firefox下勾选“数量标记显示成下标”这个选项以后数字下标显示经常出现字体问题，尤其是当合并了大量重复弹幕以后，显示的两位数或者三位数下标数字字体并不会按照设置的弹幕字体改变而是显示成各种各样不同的字体，上下错位观感上显得很奇怪，如附件图片所示。我的播放器设置都是默认的，弹幕字体是黑体，勾选了粗体，很奇怪的是如果不勾选粗体就一切正常了……
![1](https://user-images.githubusercontent.com/7352378/35887320-c1b1d812-0b48-11e8-9d8c-b3f48f2a2cbd.png)
![2](https://user-images.githubusercontent.com/7352378/35887323-c5039366-0b48-11e8-8cc3-8f72ad2d8252.png)

**Comment by xmcp** [comment]
我这里无法复现，可能是你电脑上字体有问题吧。
你试试拿粗体黑体显示 `₀₁₂₃₄₅₆₇₈₉` 这些字，是不是有一样的问题？

**Comment by guyigenius** [comment]
我用粗体黑体显示₀₁₂₃₄₅₆₇₈₉这些数字一切正常。我觉得应该不是我电脑上字体的问题，因为我两台Windows下的Firefox都有这个问题。

**Comment by xmcp** [comment]
不懂啊。
你可以试试调一下播放器的渲染类型？

我这里Firefox 58.0b12不管设成CSS3还是canvas，都看起来很正常的样子：

![image](https://user-images.githubusercontent.com/6646473/35898631-ad9ed0cc-0c02-11e8-988b-c235b6d8c954.png)

（画面乱码不要在意）

**Comment by guyigenius** [comment]
奇了怪了，我这里Firefox 58.0.1不管设置成CSS3还是Canvas都很不正常：
![1](https://user-images.githubusercontent.com/7352378/35898818-c44cde98-0b7d-11e8-95f5-5fc990870076.png)

**Comment by xmcp** [comment]
所以说我觉得是你字体的问题啦。
你看那个1和4怎么看都不像是黑体的样子。

**Comment by fireattack** [comment]
发 bugzilla了 https://bugzilla.mozilla.org/show_bug.cgi?id=1436535

**Comment by guyigenius** [comment]
嗯，在CSS3下就是如楼上所说，不过我又看了看，有些视频1234在CSS3下会出现问题，然后在Canvas下显示一切正常，说明和渲染也有一定的关系，不过这仅限于一部分视频，其他视频在CSS3和Canvas下渲染出来的1234都还是有上面的Fallback问题。也不太清楚具体是什么鬼……

**Comment by xmcp** [comment]
我觉得pakku可以考虑对Firefox加个patch，拿 `!important` 把字体覆盖掉。但用什么字体合适啊……

**Comment by fanthos** [comment]
这个bug跟很久以前用Linux桌面的时候中文文字大小不同类似
