### ISSUE TITLE
问下大佬，可以直接根据主站等级屏蔽弹幕么

### ISSUE THREAD

**Issue by Deemo1995** [xmcp/pakku.js#52]
RT，看热门番剧的时候好多跟风弹幕都是3级以下的，想屏蔽掉

**Comment by xmcp** [comment]
B站没有提供批量查询用户等级的接口，目前如果要强行实现该功能，会使弹幕加载时间大到无法接受。因此暂不考虑。

**Comment by xmcp** [comment]
发现一个可以批量查询（每次最多100个）用户信息的接口：
`https://account.bilibili.com/api/member/getInfoByMid?mid=1,2,3,4,5`

感觉这个功能有希望呀……

**Comment by celeron533** [comment]
会不会导致请求数过多然后被服务器枪毙？

**Comment by xmcp** [comment]
据观测，两万条以内不会

**Comment by xmcp** [comment]
因为批量查询用户信息可能会对B站服务器造成一些压力，因此 pakku 应该不会 *直接光明正大地* 添加这个功能。

但是可以通过 pakku 的“弹幕屏蔽Pro”（原Foolbar） 或 [一些第三方(?)脚本](https://github.com/xmcp/pakku-advanced-filter) 实现按用户等级屏蔽弹幕。

**Comment by CPCer** [comment]
@xmcp 大佬好，我发现我在登录状态下、使用油猴脚本时， `pakku` 会异常😓……
![2020-01-26 (5)](https://user-images.githubusercontent.com/8787958/73135944-53db5d00-4083-11ea-8ce1-5c9fcd82f5b9.png)

新建了 `User Profile` 测试，所以应该能排除其他扩展、油猴脚本干扰的可能……暴力猴和Tempermonkey都试了。
我使用的是 `Centbrowser`，Chromium 内核 74.0.3729.169

而出现上图中“0条弹幕”的情况，是可以凑合的——通过按 Alt+R 两次来重启pakku。但是这样会有后遗症……无法显示右侧弹幕列表。一旦试图查看弹幕发送者，则概率性会出现浏览器卡死的情况……

试了下火狐是正常的，暂时打算用火狐上B站了……

**Comment by xmcp** [comment]
@CPCer 我也在用tampermonkey，Chrome版本号是79，没有遇到这样的情况。

因为Chrome没有提供修改HTTP响应的接口（Firefox提供了，表扬一个），pakku在Chrome平台魔改了`XMLHttpRequest`来实现修改弹幕。如果你在用弹幕相关的油猴脚本，确实有可能出现冲突。

建议排查哪个脚本有问题，或者按F12看Console里报了什么错。

**Comment by CPCer** [comment]
请大佬参阅 Console
![2020-01-26_232002](https://user-images.githubusercontent.com/8787958/73137420-a6704580-4092-11ea-9244-b3a2f3a60d77.png)

其他脚本的问题似乎可以排除。我测试时新创的 chrome 用户，只有 pakku 的油猴脚本。而且不登录 B站 帐号是正常的……
（所以是不是用户的弹幕屏蔽策略导致的问题呢？
好像也不是，因为测试时并没有同步用户弹幕吧…
![截图_20200126092921](https://user-images.githubusercontent.com/8787958/73137436-edf6d180-4092-11ea-8514-19e44a2d1d40.png)
）

> @CPCer 我也在用tampermonkey，Chrome版本号是79，没有遇到这样的情况。
> 
> 因为Chrome没有提供修改HTTP响应的接口（Firefox提供了，表扬一个），pakku在Chrome平台魔改了`XMLHttpRequest`来实现修改弹幕。如果你在用弹幕相关的油猴脚本，确实有可能出现冲突。
> 
> 建议排查哪个脚本有问题，或者按F12看Console里报了什么错。
