### ISSUE TITLE
Firefox隐私浏览模式下的相关问题

### ISSUE THREAD

**Issue by guyigenius** [xmcp/pakku.js#53]
问题一是隐私浏览模式下第一次打开视频，在播放加载完毕以后会重新加载一遍整个网页，感觉可能和之前Firefox下单独定义了字体有关？
问题二是隐私浏览模式下点击扩展程序角标不能显示正确的内容。
真是不好意思，我又来了，又是motherfucking Firefox下的问题😅。

**Comment by xmcp** [comment]
问题一：对的，为了使字体的patch生效，pakku会自动刷新页面来重新加载播放器。应该可以把这个patch提前在播放器加载之前进行来修复此问题。

问题二：**Firefox果然给开发者留下了很多惊喜**:rofl:。[Firefox在隐私模式中禁止其他页面调用 getBackgroundScript 与主程序直接沟通](https://bugzilla.mozilla.org/show_bug.cgi?id=1329304)，这个问题修复起来比较麻烦，但我会加上相应的提示。

**Comment by guyigenius** [comment]
非常感谢这么及时的回复！
问题一：现在虽然不会自动刷新页面了，但是似乎也不会加载字体的Patch了……
问题二：加上“隐私浏览”模式下本页面无效这一句提示就挺好的。

**Comment by xmcp** [comment]
应该还是会patch的，只是时机调整到了网页载入的时候。
pakku只会patch一次字体，所以如果你之后手动把字体设置改回来pakku就不管了。

**Comment by guyigenius** [comment]
我又看了一下，我这里似乎并没有patch，我没有手动更改过字体，没有patch上去一直显示的是黑体。还请麻烦确认一下，谢谢！

**Comment by xmcp** [comment]
可能是pakku改完播放器设置之后不知道为什么没有生效。
清除bilibili.com的缓存，再随便开一个视频，再刷新一下页面应该能够强制重新patch。
你要是不想清缓存的话直接在自定义字体的最前面加一个 `Segoe UI Symbol, ` 就行了。

**Comment by guyigenius** [comment]
那我觉得还是reset回去吧，以前的重新加载播放器比较好，至少能稳定patch，因为隐私浏览模式本身就是不保存缓存的，你的方法并没有什么用啊。

**Comment by guyigenius** [comment]
我明白了，现在相当于第一次打开视频的时候虽然在LocalStorage里面改了，但是实际起效要第二次打开视频的时候……感觉还是以前直接location.reload()好，这样第一次打开视频的时候就能起效。谢谢！
