### ISSUE TITLE
生日快乐彩蛋应可控

### ISSUE THREAD

**Issue by TinkoLiu** [xmcp/pakku.js#56]
RT
各自喜欢的角色并不一样，为了避免可能出现什么乱七八糟的事情还是有个开关为好
可以写得含糊一点，但是最好还是有个开关可控

**Comment by xmcp** [comment]
各自喜欢的角色可能不一样，但**我喜欢的角色**是一样的，so，wontfix。

另外【我是高级用户】开关目前是可以控制彩蛋的。

**Comment by ipcjs** [comment]
😅我还以为是有人在那里ky刷屏
