### ISSUE TITLE
如何击杀「紫妈脸滚键盘」弹幕？

### ISSUE THREAD

**Issue by zcyzcy88** [xmcp/pakku.js#57]
[就是这个](https://www.bilibili.com/video/av394281)，一群小鬼看到紫妈就开始「脸滚键盘」
我没有想出办法来有效屏蔽，各位有什么好办法？

**Comment by fanthos** [comment]
赞，不知道有什么特点

**Comment by xmcp** [comment]
![image](https://user-images.githubusercontent.com/6646473/38173343-639378b8-35ef-11e8-80b0-d356a5d1b80c.png)

试了一下效果还可以。v8.6.6已经提交webstore，此贴终结。
