### ISSUE TITLE
pakku没有正常工作

### ISSUE THREAD

**Issue by Thiece** [xmcp/pakku.js#58]
在使用pakku观看https://www.bilibili.com/bangumi/play/ep14760
pakku没有正常工作

<summary>[Debug Info]</summary>

**Version:** 8.6.6

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"AUTO_DISABLE_DANMU":"off","AUTO_PREVENT_SHADE":"off","BLACKLIST":"[[\"#ver.0.1.7\",\"\"],[\"#Time.2016\\\\/8\\\\/31\",\"\"],[\"^.$\",\"\"],[\"^([▂▅▇█▆=o0O_\\\\-:з3」∠≧∇≦v^ー°Д∀´｀ω★])\\\\1*?.+\\\\1+$\",\"\"],[\"^\\\\s{4,}$\",\"\"],[\"^[\\\\S\\\\s]{35,}$\",\"\"],[\"\\\\d{2,4}[:|\\\\/| |：|年|-]\\\\d{1,2}[:|\\\\/| |：|月|-](\\\\d{1,2})?\",\"\"],[\"\\\\d{1,2}[:|\\\\/| |：|-]\\\\d{1,2}([:|\\\\/| |：|-]\\\\d{0,2})?\",\"\"],[\"((?:[^[:punct:]](?!bili))+)\\\\1{3,}\",\"\"]]","BREAK_UPDATE":"off","CROSS_MODE":"on","DANMU_MARK":"suffix","DANMU_SUBSCRIPT":"off","ENLARGE":"off","FLASH_NOTIF":"on","FLUCTLIGHT":"off","FOOLBAR":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"off","REMOVE_SEEK":"off","SCROLL_THRESHOLD":"900","SHRINK":"off","TAOLUS":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0s~]+$\",\"yoo...\"]]","THRESHOLD":"15","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[[\"弹\\\\s*幕\\\\s*护\",\"\"]]","_ADVANCED_USER":"on"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/options/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/options/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=383 status=complete `https://www.bilibili.com/`

- ID=525 status=complete `https://search.bilibili.com/all?keyword=%E9%9B%B6%E4%B9%8B%E4%BD%BF%E9%AD%94&from_source=banner_search`

- ID=529 status=complete `https://www.bilibili.com/bangumi/play/ep14760`

- ID=537 status=complete `undefined`

- ID=545 status=loading `undefined`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>2</chatid><mission>0</mission><maxlimit>1500</maxlimit><state>1</state><real_name>0</real_name></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>2</chatid><mission>0</mission><maxlimit>1500</maxlimit><state>1</state><real_name>0</real_name></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/options/troubleshooting.js` :: 69 :: 1
</details>

**Comment by xmcp** [comment]
你的黑名单设置里面有一条规则 `((?:[^[:punct:]](?!bili))+)\\1{3,}`，格式好像不太对。
在选项页面选择【重置所有设置】应该可以解决这个问题。

**Comment by Thiece** [comment]
@xmcp 我重置了之后确实恢复了，但是这条规则实际上是一条正常的正则，且在昨天之前pakku也是能够正常运行的，并不是一条新增的规则。

**Comment by Thiece** [comment]
@xmcp 我发现了问题所在了，抱歉，很奇怪的是我之前写的正则是`((?:[^[:punct:]](?!bili))+)\1{3,}` 但是它中间被多添加了一个`\`导致错误。

**Comment by xmcp** [comment]
pakku昨天的v8.6.6更新给正则表达式添加了Unicode (`u`) flag。
有意思的是，加上这个flag之后它就变成非法的正则了。

![image](https://user-images.githubusercontent.com/6646473/38199988-3a9366a4-36c5-11e8-978c-6dbd3c3ff093.png)
