### ISSUE TITLE
本页面没有发现B站播放器

### ISSUE THREAD

**Issue by sola97** [xmcp/pakku.js#59]
`<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 8.6.6

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3381.1 Safari/537.36`

**Incognito:** `false`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/options/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/options/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=80 status=complete `https://www.bilibili.com/video/av21597412`

- ID=324 status=complete `undefined`

- ID=328 status=loading `undefined`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>2</chatid><mission>0</mission><maxlimit>1500</maxlimit><state>1</state><real_name>0</real_name></i>`

**Request / Normal XML:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>2</chatid><mission>0</mission><maxlimit>1500</maxlimit><state>1</state><real_name>0</real_name></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/options/troubleshooting.js` :: 69 :: 1
</details>`

**Comment by xmcp** [comment]
- 你给的调试信息一定不全
- 应该是因为你的黑名单规则里面有一些非法的正则表达式（与 #58 类似）
- 点【重置所有设置】可以暂时解决这一问题

*考虑到这个bug可能比较严重，我觉得有必要删掉正则表达式的 Unicode flag 了:rofl:*

**Comment by sola97** [comment]
因为正则列表比较长，我没贴出来
看了下的确也是正则表达式方括号的问题
本来我这配置都已经稳定用了用了大半年了，发现不能用了才跑过来的

**Comment by xmcp** [comment]
因为这个bug的影响可能比较大，v8.6.7会换回原来的正则表达式模式 :sweat: ，你更新到 v8.6.7 应该就好了。
