### ISSUE TITLE
请问可以做个屏蔽或合并所有表情弹幕的功能吗

### ISSUE THREAD

**Issue by z456321abc** [xmcp/pakku.js#61]
RT,那些刷火箭和其他表情的弹幕没有办法很好的合并或者直接屏蔽,可以更新一下添加这功能吗
-->

**Comment by xmcp** [comment]
你说emoji？这个可以用正则表达式屏蔽。
参考 [StackOverflow](https://stackoverflow.com/questions/18862256/how-to-detect-emoji-using-javascript)、[bilibili用户反馈论坛](http://link.acg.tv/forum.php?mod=viewthread&tid=11557)。
