### ISSUE TITLE
这个链接没有弹幕密度图

### ISSUE THREAD

**Issue by HaloWang** [xmcp/pakku.js#67]
[怪物之子](https://www.bilibili.com/blackboard/topic/TheBoyandtheBeast.html) 

可能是 B 站为这种动画改了页面上的某些代码？《你的名字》《刀剑神域》都是有的

**Comment by xmcp** [comment]
播放器iframe的域是 `bilibili.com`，跟top的域（`www.bilibili.com`）不一样。
直接改 `top.document.domain` 应该能解决，但不知道有没有更靠谱的解决办法。

**Comment by celeron533** [comment]
我记得 刀剑神域 以前是爱奇异还是乐视上面托管的
