### ISSUE TITLE
B站推出“不挡脸”弹幕 , 能增加这个选项吗

### ISSUE THREAD

**Issue by zerokos** [xmcp/pakku.js#69]
B站针对弹幕功能进行了升级，推出“不挡脸”弹幕。打开一则舞蹈视频右下角的“智能防挡弹幕”功能后，弹幕就不会再覆盖人像，而是呈现从人体身后穿过的效果。
该功能只适用于舞蹈和鬼畜区 ， 作者能添加“不挡脸”弹幕选项吗？

**Comment by xmcp** [comment]
这个功能目前需要服务器处理视频，所以加不了。
