### ISSUE TITLE
[疑问]Pakku 对 B 站用 WebSocket 加载的新弹幕有应用过滤规则吗？

### ISSUE THREAD

**Issue by AnnAngela** [xmcp/pakku.js#70]
B 站的视频的弹幕不仅仅是加载视频时加载的那个弹幕 XML 文件，同时还有从
 `wss://broadcast.chat.bilibili.com:4095/sub` 不停下载的实时新弹幕。我想问的是Pakku 对 B 站用 WebSocket 加载的新弹幕有应用过滤规则吗？如果有就当我啥也没说_(:зゝ∠)_，如果没有希望能加上=w=

**Comment by xmcp** [comment]
没有。
主要的技术难点有两个：
- Chrome 本身没有为扩展程序提供监控 WebSocket 的 API，要是 patch 页面上的 `WebSocket.prototype` 就有点玄学了
- 如果把新弹幕过滤了就需要更新原来弹幕的角标，但目前做不到实时修改已有的弹幕，倒是 [有人尝试过 patch 页面上的 `Array.prototype`](https://github.com/ipcjs/pakku.js/commit/f8cd1310792ac30a3057dee5e94ac96debbe4453)，但这实在太玄学了

综上，目前 pakku 没有管 WebSocket 下载的弹幕，但是在设置里有选项可以【阻止弹幕动态更新】，直接屏蔽 WebSocket 的连接。

**Comment by fanthos** [comment]
我之前写过油猴脚本就patch了xhr好像

**Comment by AnnAngela** [comment]
自己这段时间 path 了 EventTarget.prototype.addEventListener
太玄学了，能理解你的痛苦
