### ISSUE TITLE
批量屏蔽的同时批量屏蔽用户

### ISSUE THREAD

**Issue by along-emacs** [xmcp/pakku.js#71]
开发者你好，我希望pakku能添加一个新功能，就是比如合并了10条弹幕后，我在播放器里右键弹幕->屏蔽之后，希望把所有发了这10条弹幕的10个用户一起屏蔽了。目前只会屏蔽一个用户。不知道这个功能能实现吗？期待！

**Comment by xmcp** [comment]
这个功能暂时不考虑
