### ISSUE TITLE
建议：弹幕按照时间更改透明度

### ISSUE THREAD

**Issue by kaaass** [xmcp/pakku.js#73]
建议增加弹幕按照发送时间更改透明度，越老透明度越小，越新透明度越大……能在一定程度上优化老视频弹幕体验。以及我自己写的油猴脚本和这个插件冲突了，故建议。

**Comment by xmcp** [comment]
弹幕透明度是播放器整体设置，弹幕本身并不包含透明度信息。
<del>除非你在页面上hook `appendChild`，但我强烈不建议这么做。</del>

另外你可以看看README里面提到的API。[这里有一个demo](https://greasyfork.org/zh-CN/scripts/42635-pakku-advanced-filter)
