### ISSUE TITLE
[建议] 在那个弹幕信息显示框里显示被屏蔽的弹幕的屏蔽来源

### ISSUE THREAD

**Issue by AnnAngela** [xmcp/pakku.js#74]
又是我_(:зゝ∠)_
建议加入在弹幕信息显示框（就是按住ctrl点弹幕弹出的灰色的框）里显示被屏蔽的弹幕的屏蔽来源（比如这条弹幕是因为命中屏蔽文本/正则/用户列表才被屏蔽的，命中的规则是啥啥啥）（不知道表达清楚了没有_(:зゝ∠)_）（感谢大大辛苦付出~）

**Comment by xmcp** [comment]
被屏蔽的弹幕根本不显示，也不会出现在弹幕列表里，怎么按住ctrl点击？
