### ISSUE TITLE
播放视频后不显示弹幕

### ISSUE THREAD

**Issue by BenjaminGao** [xmcp/pakku.js#76]
插件版本：pakku v9.1.2（最新版）
Chrome版本：68.0.3440.106 (正式版本) （64 位）
问题：播放视频后无弹幕，必须要暂停视频才可以。有时候暂停视频也不行，必须要左键点一下插件，并且暂停视频才可以。

**Comment by xmcp** [comment]
请提供更多信息，比如：
- 你修改了pakku的什么设置
- 每次都出现这个问题还是偶尔出现
- 出现问题时右上角pakku的图标显示了什么
- 出现问题时播放器右边的弹幕列表显示了什么
- 出现问题时有没有任何错误信息
- 你在用新版还是旧版播放器

等等

**Comment by BenjaminGao** [comment]
@xmcp 这是我录制的视频地址：https://pan.baidu.com/s/1_vbIQ3qtvrAGL8s_i3mq2g 密码: geg7。GIF 没法录制

虽然视频当中我只要暂停视频就会恢复弹幕，但是有时候暂停不管用，必须先暂停识破，然后 __左键__ 点一下插件图标，然后再恢复视频播放，弹幕才会再次出现。

- pakku 设置是默认的，我没有做任何改动
- 这个问题在每个视频都出现
- pakku的图标显示：![2018-08-26 7 07 31](https://user-images.githubusercontent.com/16028320/44627604-56ec8e00-a963-11e8-864d-6ea6d5bad905.png)
- 播放器右边的弹幕列表显示：![2018-08-26 7 09 02](https://user-images.githubusercontent.com/16028320/44627628-8b604a00-a963-11e8-8438-74ddec719cd4.png) 弹幕列表正常
- 没有提示任何错误信息
- 新版播放器

**Comment by xmcp** [comment]
感觉像是B站播放器的bug呀……你停用pakku能解决问题吗？

**Comment by BenjaminGao** [comment]
好吧，我停用了一下，确实是 B 站的 Bug。抱歉，这个是我没仔细检查是不是插件的原因就上报 issus。
