### ISSUE TITLE
[建议]添加一项合并弹幕文件功能

### ISSUE THREAD

**Issue by AnnAngela** [xmcp/pakku.js#77]
有的 UP 主会选择在上传视频时上传 2 个分段，一个是非大会员 60 帧，一个是大会员 60 帧。
然后我就突发奇想：能不能提供一个将其他分段的弹幕合并到当前分段中的功能呢？
入口就放在 page/popup.html 里，提供一个分段列表，打勾后点击加载按钮就能加载进来？
（技术细节个人脑补：重载页面，在重载过程中劫持弹幕获取 XHR ，然后将两个列表下载后给播放器返回？）

**Comment by xmcp** [comment]
感觉这个功能比较小众啊。
有需要的话用油猴脚本实现好了。

**Comment by AnnAngela** [comment]
emmm，油猴脚本怎么做呀

**Comment by xmcp** [comment]
你看readme里的开放API啊
