### ISSUE TITLE
弹幕密度分析图无法显示

### ISSUE THREAD

**Issue by StellarHe** [xmcp/pakku.js#78]
已经尝试过重置及关闭其他插件，未解决问题qaq

**Comment by StellarHe** [comment]
又试了一下，只在B站新版播放页会这样，但是两天前使用新版页面也并没有此问题，是B站更新了吗……

**Comment by xmcp** [comment]
很有可能。我这几天在军训，最早也是下周fix了😂

**Comment by XDcedar** [comment]
新版播放页按ctrl也没法显示合并的弹幕了
