### ISSUE TITLE
提供google签名认证过的crx文件下载

### ISSUE THREAD

**Issue by celeron533** [xmcp/pakku.js#8]
可能有些用户无法第一时间采取正确的科学上网姿势，所以有的项目会直接提供crx文件下载。
https://github.com/FelisCatus/SwitchyOmega/issues/1046#issuecomment-294007166

> 这个项目的 Release 页面的所有 CRX 包都是从 Chrome Web Store 下载的。在开发者面板上，对于所有上传并且审核通过的版本，都会有一个下载 CRX 的链接。这样下载的 CRX 文件一般会被 Chrome 信任，因为其含有 Chrome Web Store 的签名。我们从不自己打 CRX 包。

**Comment by xmcp** [comment]
其实在 http://s.xmcp.ml/pakkujs 上是有签过名的CRX的，但我好像没在README里说这事……

总之谢谢提醒，马上加。

**Comment by celeron533** [comment]
![image](https://cloud.githubusercontent.com/assets/3608762/25068396/c314b776-2294-11e7-8932-473a70061222.png)
