### ISSUE TITLE
合并后弹幕的出现时间

### ISSUE THREAD

**Issue by Sam0523** [xmcp/pakku.js#83]
目前似乎是合并后按照出现最早的弹幕的时间出现？但是这导致了部分空耳弹幕出现时间与视频不匹配，可否添加选项让合并后的弹幕按照平均时间或者中位数时间出现？

**Comment by xmcp** [comment]
我尝试过合并后的弹幕使用平均时间，但这么做之后会让一些“名台词”弹幕出现时间与视频更加不匹配（因为很多人发弹幕不暂停 / 暂停不及时，所以会晚几秒），还不如按照最早时间显示的效果好。

**Comment by Sam0523** [comment]
但是我目前见到的情况是，被合并的弹幕出现最多早了17秒，已经差了好几句歌词了……

https://www.bilibili.com/bangumi/play/ep759 1:27 - 1:45

（我个人的感觉是，晚发弹幕的不是特别多啊……个人感觉）
