### ISSUE TITLE
希望可以按发送时间屏蔽远古弹幕

### ISSUE THREAD

**Issue by IlluminateDarkheat** [xmcp/pakku.js#84]
希望增加按发送时间屏蔽弹幕的功能，在某些视频里远古弹幕有些影响观看。。（例如远古版本的游戏视频，弹幕对游戏理解过于古老）

**Comment by xmcp** [comment]
pakku为Pro User提供了高级屏蔽功能。
可以在选项里打开“弹幕屏蔽 Pro”，然后输入 `sendtime>(new Date('2018/8/1')/1000)` 之类的规则即可
