### ISSUE TITLE
[建议]在弹幕框处于输入状态时不响应ctrl键显示弹幕信息显示框

### ISSUE THREAD

**Issue by AnnAngela** [xmcp/pakku.js#85]
不知道描述清楚没，我的意思是开启显示“弹幕信息显示框”功能后我在弹幕框想按ctrl+v粘贴文字时会被pakku响应ctrl键导致无法粘贴，能不能改进一下使其不会响应呢？

**Comment by xmcp** [comment]
我试了Chrome 69和Firefox 62，在弹幕框上都不会响应ctrl啊？
