### ISSUE TITLE
兼容性

### ISSUE THREAD

**Issue by jjj201200** [xmcp/pakku.js#86]
目前助手在着手1.x.x的改版，其中发现弹幕查询和pakku会有兼容问题，如下：
由于pakku需要替换官方弹幕池，在onBeforeRequest时重定向了弹幕池资源，助手无法获取用户需要查询的历史弹幕池日期（当天的弹幕池获取只需要cid，所以倒是没什么大碍）

如果pakku监听onBeforeSendHeaders而不是onBeforeRequest会不会更好一些（或者尽可能的延后）？如此包括助手在内的其他扩展就可以在pakku之前监听到需要的请求

如果几个扩展同时监听onBeforeRequest而其中有一个将其redirect掉，那只能看谁的监听事件先注册了，就有点玄。。

有没有什么方法可以提供pakku处理过的弹幕池给其他扩展？

**Comment by xmcp** [comment]
根据 [chrome.webRequest 的文档](https://developer.chrome.com/extensions/webRequest)，只有 onBeforeRequest 事件的 callback 里可以重定向请求，所以这个真的改不了。

目前 pakku 已经有利用 HTML5 Messaging API 提供弹幕池给第三方的接口：

- 当弹幕池更新时，pakku 的 Content Script 会用 `window.postMessage` 发送消息 `{type: 'pakku_event_danmaku_loaded', pakku_version: chrome.runtime.getManifest().version}` 到当前播放器页面
- 当 Content Script 收到 `{type: 'pakku_get_danmaku'}` 消息时，会发送消息 `{type: 'pakku_return_danmaku', flag: null, resp: D}` 到播放器页面，其中 D 是一个包含当前所有弹幕的 Array

[pakku advanced filter](https://greasyfork.org/zh-CN/scripts/42635-pakku-advanced-filter) 是一个 demo。

**Comment by jjj201200** [comment]
确实监听到了，不过这种方式仍旧有缺陷：
需要在pakku发送message之前助手就先注册监听事件，不然当天弹幕的message就无法获取到

不过历史弹幕倒是可以用这个方法，但是如果可以提供原始数据就好了，毕竟用户也并非都只希望得到处理后的弹幕池。

**Comment by jjj201200** [comment]
就历史弹幕的问题解决了~thx~
