### ISSUE TITLE
非官方 Firefox 浏览器支持

### ISSUE THREAD

**Issue by FrankHB** [xmcp/pakku.js#89]
现在 addons.mozilla.org 上要求 Firefox 版本至少 56.0 ，然而一些其它基于 Mozilla 代码的浏览器实际上可能能够支持（例如 [Basilisk](www.basilisk-browser.org) ，识别为 52.9 ，但不少加载项相关代码来自 FF 56 以后的）。是否可以提供放宽版本限制要求的方法（以便至少可以测试），或者直接提供支持？

备注：

* 之前使用 v9.1.5_F ，没有发现问题，但一直没有更新。
* 因为 addons.mozilla.org 经常卡翔，所以之前安装还是费了不少劲……
* 至于为啥不用其它浏览器呢……
  * 首先<s>我不得不用 Windows （虽然非 Windows 除了自己编译浏览器可能会容易以外经常都会更糟）</s>，开多个浏览器是 workaround as last sorts <s>（除多开 `mstsc`  之类的外）</s>。
    * 基于 Windows 捉急的 IPC 效率以及主流浏览器实现的质量，我甚至不愿意碰 e10s ——同时免得我要腾出 CPU 保证最大时钟频率 benchmark 时<s>/撸 osu 时</s>还先得 suspend 一溜儿进程<s>并 `taskkill /f /im explorer.exe`</s>。（相比之下，组策略配置的 IE 反而效果还更能接受点……）
  * 因为同时需要用到基于 XPCOM 和 XUL 的加载项以及使用 WebExtension 的扩展。没有被支持的官方版本 Firefox 可以做到。由于 WebExtension *自身 API 功能并不完善*的原因，不可能提供其它加载项的完全的替代（即便有人来开发除了浏览器以外的替代品）。
  * Mozilla 已[移除 Panorama](https://bugzilla.mozilla.org/show_bug.cgi?id=1222550) 。替代的 [Tab Groups](https://github.com/Quicksaver/Tab-Groups) 不支持 Firefox 57 以后的版本。经测试，最后可正常工作的 Firefox Nightly 版本为 55.0a1 (2017-04-19) 。
  * Firefox 56 以后的正式版本有其它琐碎的兼容性问题。

**Comment by xmcp** [comment]
我曾经发现在Firefox 52 ESR上有网络请求死循环的奇妙bug，56没有问题，就把版本要求改到56+了（因为56是支持旧版插件的最后版本）。

要测试的话可以把代码 clone 下来，`grunt firefox` 然后手动打包。

**Comment by FrankHB** [comment]
OK. Thx.
