### ISSUE TITLE
b站弹幕xml文件路径似乎已经更改

### ISSUE THREAD

**Issue by bgli100** [xmcp/pakku.js#9]
原: http://comment.bilibili.com/[blahblah].xml
现: http://comment.bilibili.com/rc/[blahblah].xml

我这边扩展失效了, 看F12应该是这个原因, 不知道是不是普遍性的

更新: 
本地修改扩展加载之后已经重新生效, 应该可以确定的是虽然原地址还能访问, 但新的弹幕xml文件路径已经开始上线

**Comment by xmcp** [comment]
我这还是原来的网址呀。这个新地址是不是梯度发布的？

你能给一个用了新url的av号码？

![image](https://cloud.githubusercontent.com/assets/6646473/25070084/7ce6b3c6-22c6-11e7-9ae3-d9f1eab87a5f.png)

**Comment by bgli100** [comment]
昨天用来测试的视频是 av9795355
我本地访问所有av号现在都有/rc/
三四天了，没发现没有/rc/的
估计是灰度发布了

**Comment by xmcp** [comment]
新旧网址在内容上没差别吧

**Comment by bgli100** [comment]
随便找了1个视频两个文件都拉下来hash相同

只改了扩展里url的情况下看了10个左右视频没有发现行为异常

**Comment by xmcp** [comment]
挖个坟：URL里出现 `/rc` 当且仅当打开了“云推荐弹幕”选项。
（所以说B站这个云推荐弹幕的功能卵用都没有是吗……）
