### ISSUE TITLE
黑名单设置界面 Bug

### ISSUE THREAD

**Issue by BenjaminGao** [xmcp/pakku.js#91]
Google Chrome | 71.0.3578.98 (正式版本) （64 位）
MacOS：10.13.0
pakku.js：v9.2.1_C
Bug：红色字体下边，__目前黑名单的数量__ 显示的是 42，但是下边并没有黑名单的正则规则。我导入的黑名单规则是下边 __官方安利__ 的规则，复制全选粘贴。正常来说导入规则后应该显示导入的规则，然而这里没有显示，只是显示数量。如果以后需要修改，除非清空黑名单，要不然没法修改。
![bug](https://user-images.githubusercontent.com/16028320/50329032-6609d400-0530-11e9-957c-ad990377245d.png)

**Comment by Last-Order** [comment]
能不能加个<载入当前黑名单>的按钮，至少能看到黑名单内容。因为平时并不使用B站播放器的黑名单功能来着，这个不能改就有点麻烦的样子。
https://github.com/Last-Order/pakku.js/commit/08569a552f20784ab5f17b203a3731b1702585da
示意↑

**Comment by xmcp** [comment]
等我考完试就做修改黑名单的功能
