### ISSUE TITLE
无法加载弹幕列表

### ISSUE THREAD

**Issue by AnnAngela** [xmcp/pakku.js#92]
控制台提示：
````
Access to XMLHttpRequest at 'data:text/xml;charset=utf-8,%3Ci%3E%3Cchatserver%3Echat.bilibili.com%3C%2F....%3E' (redirected from 'https://api.bilibili.com/x/v1/dm/list.so?oid=67937293') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
````
（中间省略号是弹幕列表内容）
扩展版本：v9.2.1_C
浏览器版本：版本 71.0.3578.98（正式版本） （64 位）

**Comment by xmcp** [comment]
无法复现

**Comment by AnnAngela** [comment]
![image](https://user-images.githubusercontent.com/9762652/50376513-76ad6d80-0648-11e9-9bc8-07252919b18e.png)
但是是真的有呀_(:зゝ∠)_

**Comment by Nebelwerfer-G** [comment]
这个问题不是pakku的锅，具体可以查看一下这个issue_(:зゝ∠)_
https://github.com/zacyu/bilibili-helper/issues/87
一句话：大概B站的视频服务器被运营商缓存了还把响应头删了_(:зゝ∠)_试试换DNS吧
