### ISSUE TITLE
无法使用sql过滤功能

### ISSUE THREAD

**Issue by jnxyp** [xmcp/pakku.js#93]
**无法使用sql过滤功能，alert提示alasql未加载。**

**复现过程**
- 打开pakku的`高端用户`>`弹幕屏蔽PRO`功能
- 打开任意视频
- 在视频下方sql输入框内输入任意内容按下回车

**控制台警告和报错**
```
⚠
xhr_hook.js:2 
pakku: [to developers] Web Worker is disabled for compatibility reasons
(anonymous) @ xhr_hook.js:2
(anonymous) @ xhr_hook.js:2

❌
all_injected.js:2 
    Uncaught Error: alasql not ready
    at init_db (all_injected.js:2)
    at do_execute (all_injected.js:2)
```
无其他异常，弹幕合并功能正常。
坐标加拿大，可能是网络问题吗？

下附pakku调试信息：
<details>
如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 9.2.1

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"AUTO_DANMU_LIST":"on","AUTO_DISABLE_DANMU":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"on","FOOLBAR":"on","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"off","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"1200","SHRINK":"on","TAOLUS":"","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"on","_LAST_UPDATE_TIME":"1545555854074"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"243":{"identical":1105,"edit_distance":857,"pinyin_distance":66,"cosine_distance":369,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":101,"shrink":331,"scroll":1,"taolu":895,"total":8000,"onscreen":5603,"maxcombo":107,"maxdispval":131.90630672851478,"error":null,"cid":"68059971"},"296":{"identical":95,"edit_distance":74,"pinyin_distance":29,"cosine_distance":3,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":7,"shrink":12,"scroll":0,"taolu":11,"total":568,"onscreen":367,"maxcombo":64,"maxdispval":73.9560248719353,"error":null,"cid":"67962918"}}`

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=225 status=complete `https://www.bilibili.com/`

- ID=296 status=complete `https://www.bilibili.com/video/av38660509/?spm_id_from=333.334.b_63686965665f7265636f6d6d656e64.16`

- ID=278 status=complete `undefined`

- ID=306 status=complete `undefined`

- ID=309 status=loading `undefined`

**Request / Normal XML:** load, status=0 `<i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">₍₂₎]][[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017">₍₂₎ FFT大法好(13行FFT路过)</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>k-v</source><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 1761
</details>

**Comment by xmcp** [comment]
[alasql.min.js](https://cdnjs.cloudflare.com/ajax/libs/alasql/0.4.5/alasql.min.js) 这个文件能访问吗？

如果能的话，在pakku的选项页面打开控制台，输入 `chrome.storage.local.get('alasql_src',console.log)` 显示什么？

**Comment by jnxyp** [comment]
@xmcp 
不好意思，貌似是ISP网络故障...手动设定dns并刷新全部缓存后就可以访问alasql.min.js的链接了。
实在是非常抱歉耽误您时间...
