### ISSUE TITLE
[建议] 内置一些忽略规则

### ISSUE THREAD

**Issue by oudoubleyang** [xmcp/pakku.js#94]
大佬好。
建议下个版本可以内置一些常用的忽略规则，如：
- 放行计数君：*[xX×\*]\d
- 放行恶臭弹幕：[んh][?？]
- （不会写通配符可能是错的）

（小声）还有个建议，估计应该不可能的吧_(:з」∠)_：
合并弹幕时数量动态上涨，即与当前一次显示数量不同，小括号内数字按时间增长。

**Comment by xmcp** [comment]
pakku本来内置过默认的忽略规则，但是有些不明真相的群众把它当成bug（比如 #23），后来就删掉了。高级用户自己添加规则就好了。

弹幕数量动态上涨这个想法是很好的，但B站没有提供相关API，技术上目前实现不了不清屏的情况下更新弹幕内容。（虽然BAS弹幕可以修改弹幕文字，但是BAS弹幕无法达到与滚动弹幕一样的排版样式，而且在弹幕列表里面看起来非常丑）
