### ISSUE TITLE
一个关于联合的想法

### ISSUE THREAD

**Issue by jjj201200** [xmcp/pakku.js#95]
助手重构的目标就是为了能够更加方便的扩展，能够集众家之长，但并非臃肿的事无巨细什么小功能都有的扩展。接下去开始助手官网重构，并且后续可能会上线一些需要后端计算的服务。
想问一下，是否有想法一起搞呢？
我知道不太可能说请谁合并到谁的项目里。
如果有可能的话，是否接受创建新的库，使用一个基础框架呢？
例如统一一个框架，解决如api如何开放，如何约定等等问题。
就像助手现在重构的模块化热插拔结构那样。仅仅是拿助手举个例子。
又或者是否持有或者接受其他想法或者方案呢？

当然我知道想要实现这个目标是有一个比较长的过程的，在此仅想询问一下想法和意向。
谢谢~

**Comment by xmcp** [comment]
目前Chrome扩展之间“公用基础框架”好像没有很好的解决方案，据我所知扩展之间只能互相发消息以及[共享文件](https://developer.chrome.com/extensions/shared_modules)，实现API级别的互通是非常困难的。如果把与B站相关的所有功能整合到一个扩展里，模块的升级又非常麻烦。按目前情况来看，我认为把 pakku 整个往新框架移植的代价是远大于收益的（感觉只有AV号识别、CID识别、弹幕请求处理这有限几个功能是B站相关扩展通常都会用到的，别的地方可以共用基础库的地方不多）

模块化肯定是好的，但目前 pakku 模块化的难度比较大。看 core.js 应该也能看出来，弹幕合并的那些运算（弹幕密度计算、弹幕字号修改、弹幕文字修改等等）都是互相耦合的，然后整个 core.js 再跟 Content Script 的弹幕提示框、Browser Action 的统计信息高度耦合……要想把 pakku 改成模块化的样子，我估计得几乎重写一遍。而且 pakku 的体量本身就比助手里面那些“领瓜子”、“自动宽屏”之类的功能大好多，没有可比性。

所以，我的态度是：
- 支持统一框架和模块化这个方向，但显然在 Chrome 扩展的限制下，技术难度是比较高的。
- pakku 本体功能由于体量过大、耦合度较高，可能不适合加入到助手这个框架中。
- 对于 pakku 的那些附加功能，我倒是很希望能用模块化的方式管理，如果能由 pakku 和哔哩哔哩助手作为底层框架提供 API 实现有趣的功能肯定是很好的（其实 pakku 的 HTML5 Messaging API 就有提供底层框架的想法）。
- 具体来说，pakku 选项页面 “播放器增强”、“实验室” 两个部分的那些小功能有模块化开发的需求，其他部分暂时不需要。

**Comment by xmcp** [comment]
关于需要后端计算的服务，pakku 这边基本都是在本地运算，唯一一个涉及到后端服务的痛点就是：修改之后的弹幕如果用 Data URI 返回给网页是没有 CORS 头的，播放器会直接报错，目前我不得不靠魔改 XMLHttpRequest 苟活下来。如果能有一个类似于 Echo Service 的后端服务，返回带 CORS 头的弹幕 XML 给网页，就没这么麻烦了，兼容性也会提升。

如果开发一些基于机器学习和大数据的弹幕净化功能什么的，可能会用到后端计算，但我在这方面造诣不深 ┓( ´∀` )┏ 并没有成型的 idea

**Comment by jjj201200** [comment]
非常感谢赞同模块化的方向。

之前没有提重构后的效果，其实在我重构过程中，对于扩展涉及到的几个主要过程差不多都涵盖了。
从功能点的
1.  功能点依赖载入
2. 鉴权（浏览器权限，登录状态，隐私模式状态等）
3. 模块状态同步
4. UI的依赖注入
5. 与注入页面的异步通信
6. 模块间的通信等

每一个功能点都会或多或少涉及到这几个过程，而助手已经在诸多不同性质的功能中统一使用这个约定过程。同时也是尽可能松散耦合的，比如GA模块，如果用户禁用了GA功能，并不会造成任何影响~
所以说难度的话需要剩下考虑的问题已经不是很多了鸭~

而对pakku来说功能其实就是弹幕过滤了吧。其他都是该功能点的配置，这里就功能特点来说确实是不在一个数据处理级别上的，毕竟功能点侧重都不同嘛。

再者功能点内部强耦合也是必然的，不然就可能会再进行细分了。就pakku来说其配置项目当然没有必要模块化，本身就是功能点的一部分。助手中也将一部分配置隐藏在二级页面。

就助手目前的现状而言，根据文档添加一个功能点十分的简单。而助手新的配置页面更是为了解决像pakku这样拥有较多配置的功能而存在的。比起之前的一页流将更多选项放入二级页面，另外还有modal组件（弹出窗，写了但是还没有用到）。

另外关于浏览器兼容，主要是chrome和ff的话其实问题也都不大~毕竟此类兼容问题可以交给鉴权过程处理。我已经在ff里测试过，比如画中画功能，处于隐私模式等，在没有相关特性或权限下会自动禁用并显示相应错误信息，禁用配置。

在我的考量范围内有这么几个难点：
1. 两者的设计风格，助手目前的风格和pakku差别还是蛮大的。
2. pakku的popup页面如何整合
3. pakku的设置页面的交互方式如何与助手融合

这三点都非常的不同。兄台是否有考虑删减pakku对于一般用户来说默认的信息显示呢？
另外助手目前已经使用GA模块全面打点了，知道各个功能点，哪怕是每个配置项的情况都知道，方便功能的默认调整和增删。兄台是否有考虑这个呢？

如果整合的话，助手的弹幕发送者查询也将可以去掉，而pakku设计也将会更加友好一些，毕竟是直接基于原生弹幕列表的嘛~

最后其实要说代码量的话其实还好的啦~ 也并非很多的说~ 我可以代劳鸭~ 
我很期待xmcp兄能够一起维护助手的说~ 
毕竟同是作为开源项目，还是希望可以合作的鸭~

有空的话兄台可以看下我目前已经写了的文档，并不是很复杂~ [Document](https://github.com/zacyu/bilibili-helper/blob/master/docs/main.md)
这里的文档主要是一个思路的描述和一些关键模块的说明。还需要进行一些代码阅读。
目前正要对各个环节进行进行错误搜集的设计和约定，在逻辑明确的情况下也必然不是难事了~

期待期待~

**Comment by xmcp** [comment]
你的意思是把 pakku 整个作为一个 Feature 加到助手里？

这样的话，一来 pakku 里面有些硬编码的逻辑（比如 `setBadgeText` 和 Content Script 里面 `chrome.runtime.sendMessage` 调用）可能要改，二来模块的升级要怎么办？必须跟着哔哩哔哩助手一块升级吗？如果是热更新的话，Firefox 端的审核可能会出问题。

关于隐藏默认设置这件事，我觉得现在关掉 “高级用户” 的选项之后显示的设置项目已经不算多了，而且剩下的配置项基本上是作为 “功能介绍” 而存在的。

**Comment by jjj201200** [comment]
emmmm我的想法是再开一个新项目，毕竟这是一个需要尝试的事情，如果进展顺利的话就在时机成熟时以新项目的名义覆盖原产品发布呗？
而且两个项目star也不少惹想要转移流量也需要时间的嘛，不过我也不介意合并到助手里，只是我觉得兄台肯定是不愿意的=、=

关于硬编码部分肯定是要改的呀，不可能什么都不改直接合并的嘛

关于升级和维护也肯定是一起的鸭，毕竟统一标准后既然一起维护肯定都是凡是商量着来嘛，这才是开源合作嘛~

目前我这边除紧急重要更新外是已经进入月更状态了~

**Comment by xmcp** [comment]
没太明白你的思路……
是要新开一个项目，把B站相关的功能（弹幕合并、pakku的其他小功能、哔哩哔哩助手的相关功能）都用模块的形式做进一个扩展是吗？

**Comment by jjj201200** [comment]
是的，新开一个项目，在成型之前肯定仍旧保持各自独立维护。

关于pakku中webRequest的问题，因为需要及时redirect，这并不是问题啊
并没有说一定要完全异步的呀，各模块根据自己需要进行实现，框架只是约定了从载入，鉴权，状态更新，到依赖注入的一个统一流程而已，具体如使用同步还是异步当然是因地制宜的啦~

另外你提到过一些页面数据的共享，其实我这里的想法是，每个模块独立监听捕获自己需要的数据。如果需要数据共享，则根据依赖加载和注入规则，也能够保证通讯顺序。
