### ISSUE TITLE
切换历史弹幕时使用弹幕密度分析图功能会导致进度条不正常

### ISSUE THREAD

**Issue by ShadowLyin** [xmcp/pakku.js#98]
<details>

如果 pakku 完全无法工作，请完整地复制蓝框里的所有文字，并在反馈 bug 时附上。

<summary>[Debug Info]</summary>

**Version:** 9.2.2

**Channel:** chrome

**User Agent:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36`

**Incognito:** `false`

**localStorage:** `{"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","AUTO_PREVENT_SHADE":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"on","FOOLBAR":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"900","SHRINK":"off","TAOLUS":"","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1548907097511"}`

**Views:**

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/core/background.html`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/options.html#batch-ignore-panel`

- `chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.html`

**Background / IS_FIREFOX:** false

**Background / GLOBAL_SWITCH:** true

**Background / HISTORY:** `{"138":{"identical":0,"edit_distance":0,"pinyin_distance":0,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":0,"total":0,"onscreen":0,"maxcombo":0,"maxdispval":"","error":null,"cid":"74078003","parse_time_ms":0},"142":{"identical":769,"edit_distance":669,"pinyin_distance":31,"cosine_distance":7,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":51,"shrink":"","scroll":0,"taolu":6,"total":3000,"onscreen":1524,"maxcombo":300,"maxdispval":131.0333549270512,"error":null,"cid":"73777692","parse_time_ms":230},"153":{"identical":1,"edit_distance":1,"pinyin_distance":0,"cosine_distance":0,"player_seek":"","blacklist":"","count_hide":"","whitelist":"","batch_ignore":0,"script":0,"enlarge":0,"shrink":"","scroll":0,"taolu":0,"total":9,"onscreen":7,"maxcombo":2,"maxdispval":7.656854249492381,"error":null,"cid":"12664443","parse_time_ms":1}}`

**Storage / Sync:** {"AUTO_DANMU_LIST":"off","AUTO_DISABLE_DANMU":"off","AUTO_PREVENT_SHADE":"off","BLACKLIST":"[]","BREAK_UPDATE":"off","CLOUD_SYNC":"off","CROSS_MODE":"on","DANMU_MARK":"prefix","DANMU_SUBSCRIPT":"on","ENLARGE":"on","FLASH_NOTIF":"on","FLUCTLIGHT":"on","FOOLBAR":"off","FORCELIST":"[[\"^23{2,}$\",\"233...\"],[\"^6{3,}$\",\"666...\"],[\"^[fF]+$\",\"FFF...\"],[\"^[hH]+$\",\"hhh...\"],[\"^[yYoO0][yYoO0\\\\s~]+$\",\"yoo...\"]]","HIDE_THRESHOLD":"0","MARK_THRESHOLD":"1","MAX_COSINE":"60","MAX_DIST":"5","MODE_ELEVATION":"on","POPUP_BADGE":"percent","PROC_POOL1":"off","PROC_TYPE4":"on","PROC_TYPE7":"on","REMOVE_SEEK":"off","REPRESENTATIVE_PERCENT":"0","SCROLL_THRESHOLD":"900","SHRINK":"off","TAOLUS":"","THRESHOLD":"20","TOOLTIP":"on","TRIM_ENDING":"on","TRIM_PINYIN":"on","TRIM_SPACE":"on","TRIM_WIDTH":"on","WHITELIST":"[]","_ADVANCED_USER":"off","_LAST_UPDATE_TIME":"1548907097511"}

**Permissions:** `{"origins":["*://*.bilibili.com/*"],"permissions":["notifications","storage","webRequest","webRequestBlocking"]}`

**Tabs:**

- ID=2 status=complete `https://www.bilibili.com/`

- ID=127 status=complete `https://t.bilibili.com/?tab=512`

- ID=142 status=complete `https://www.bilibili.com/bangumi/play/ep259772`

- ID=158 status=complete `undefined`

- ID=161 status=loading `undefined`

- ID=135 status=complete `undefined`

**Request / Normal XML:** load, status=0 `<i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>e-r</source><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">₍₂₎]][[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017">₍₂₎ FFT大法好(13行FFT路过)</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d></i>`

**Request / XML With Param:** load, status=200 `<?xml version="1.0" encoding="UTF-8"?><i><chatserver>chat.bilibili.com</chatserver><chatid>12664443</chatid><mission>0</mission><maxlimit>1000</maxlimit><state>0</state><real_name>0</real_name><source>e-r</source><d p="14.63900,1,25,16777215,1482851465,0,f571e8a8,2788066725"> 神™·MIDI</d><d p="20.53300,1,25,16777215,1482851465,0,f571e8a8,2788068017"> FFT大法好（13行FFT路过）</d><d p="28.72500,1,25,16777215,1482851466,0,f571e8a8,2788069497">   FFT大法好（13行FFT路过）</d><d p="49.37700,1,25,16777215,1482851466,0,f571e8a8,2788070737">Ocarina的声音好奇怪</d><d p="65.91800,1,25,16777215,1482851467,0,f571e8a8,2788072713">你们都好强啊~~~ orz orz orz orz</d><d p="299.26400,1,25,16777215,1482851480,0,f571e8a8,2788118637">好强啊</d><d p="0.00000,1,25,16777215,1524407489,0,91d6b7d0,4480700090">]][[</d><d p="0.00000,1,25,16777215,1524407554,0,91d6b7d0,4480703586">]]][[[</d><d p="0.03400,1,25,16777215,1530370137,0,91d6b7d0,1692382060347392">test!@#$%^&amp;*()_+-={}[];':",./&lt;&gt;?</d></i>`

**! Exception:** `Uncaught ReferenceError: test_error_log is not defined`

`chrome-extension://jklfcpboamajpiikgkbjcnnnnooefbhh/page/troubleshooting.js` :: 2 :: 1873
</details>
截图如下：

[![批注 2019-01-31 120059.jpg](https://i.loli.net/2019/01/31/5c52736e7203c.jpg)](https://i.loli.net/2019/01/31/5c52736e7203c.jpg)

**Comment by xmcp** [comment]
#97
